# original path (under https://trixti.com.br/) -> (filename in WP, alt text)
MEDIA = {
 "images/39.png": ("trix-logo.png","Trix Tecnologia Inteligente"),
 "images/01.png": ("trix-logo-rodape.png","Trix TI"),
 "images/02.jpg": ("trix-empresa.jpg","Equipe Trix Tecnologia Inteligente"),
 "images/21.png": ("trix-fundo-marca.png","Elemento gráfico da marca Trix"),
 "images/22.png": ("trix-destaque-fabrica.png","Fábrica de software Trix"),
 "images/29.png": ("trix-destaque-consultoria.png","Consultoria especializada Trix"),
 "images/30.png": ("trix-destaque-saw.png","SAW - Sistema de Atendimento Web"),
 "images/24.png": ("trix-rodape-recorte.png","Detalhe do rodapé"),
 "images/06.png": ("icone-email.png","E-mail"),
 "images/07.png": ("icone-endereco.png","Endereço"),
 "images/12.png": ("icone-produtos.png","Produtos e soluções"),
 "images/13.png": ("icone-fabrica.png","Fábrica de software"),
 "images/14.png": ("icone-consultoria.png","Consultoria"),
 "images/15.png": ("icone-solucoes.png","Soluções e automação"),
 "images/16.png": ("icone-processos.png","Escritório de processos"),
 "images/08.png": ("logo-saw.png","SAW - Sistema de Atendimento Web"),
 "images/09.png": ("logo-gedai.png","GEDAI - Gerenciador Eletrônico de Documentos e Arquivo Inteligente"),
 "images/10.png": ("logo-integrador.png","Integrador Trix"),
 "images/11.png": ("logo-intranet.png","Intranet Trix"),
 "images/27.png": ("logo-portal-unimed.png","Portal Operadora"),
 "images/28.png": ("marcos-soares.png","Marcos Soares, Diretor Executivo da Trix"),
 "images/31.png": ("saw-titulo.png","SAW"),
 "images/32.png": ("gedai-titulo.png","GEDAI"),
 "images/33.png": ("integrador-titulo.png","Integrador"),
 "images/37.png": ("intranet-titulo.png","Intranet Trix"),
 "images/41.png": ("cliente-41.png","Cliente Trix"),
 "images/logo_biometria.png": ("logo-biometria-facial.png","Biometria facial Aspect Face"),
 "images/logo_aspect_face.png": ("logo-aspect-face.png","Aspect Face - API de reconhecimento facial"),
 "images/logo_oracle.png": ("logo-oracle-partner.png","Oracle PartnerNetwork"),
 "images/logo_swagger.png": ("logo-swagger.png","Swagger - documentação de API"),
 "images/monitor.png": ("monitor-sistemas.png","Sistemas Trix em tela"),
 "images/img_face.jpg": ("aspect-face-reconhecimento.jpg","Reconhecimento facial"),
 "images/img_antifraude.jpg": ("aspect-face-antifraude.jpg","Antifraude com inteligência artificial"),
 "images/img_identificador.jpg": ("aspect-face-identificador.jpg","Identificação 1:1, 1:N e N:N"),
 "images/img_prova_vida.jpg": ("aspect-face-prova-de-vida.jpg","Prova de vida (liveness)"),
 "images/img_swagger.jpg": ("aspect-face-swagger.jpg","Integração via Swagger"),
 "images/img_gerenciador_web.jpg": ("aspect-face-gerenciador.jpg","Gerenciador web de acessos e fraudes"),
 "images/img_dashboard.jpg": ("aspect-face-dashboard.jpg","Dashboards de visualização"),
 "images/img_port_opera.png": ("portal-operadora.png","Portal Operadora"),
 "images/desenvolvimento.jpg": ("desenvolvimento-software.jpg","Desenvolvimento de software"),
 "images/economus.jpg": ("cliente-economus.jpg","Economus"),
 "images/prontow/prontow_logo.png": ("prontow-logo.png","Prontow - software para clínicas e consultórios"),
 "images/prontow/agenda.png": ("prontow-agenda.png","Agenda do Prontow"),
 "images/prontow/filas.png": ("prontow-filas.png","Filas de atendimento em tempo real no Prontow"),
 "images/prontow/fluxo-caixa.png": ("prontow-fluxo-de-caixa.png","Fluxo de caixa no Prontow"),
 "images/prontow/tiss-painel.png": ("prontow-tiss.png","Painel TISS do Prontow"),
 "images/prontow/appstore.png": ("app-store.png","Disponível na App Store"),
 "images/prontow/gplay.png": ("google-play.png","Disponível no Google Play"),
 "images/xieldimg/xield_01.png": ("xield-plataforma-web.png","Xield: plataforma 100% web"),
 "images/xieldimg/xield_02.png": ("xield-controle-de-acesso.png","Xield: controle de acesso com biometria facial"),
 "images/xieldimg/xield_03.png": ("xield-mapa-de-presenca.png","Xield: mapa de presença em tempo real"),
 "images/xieldimg/xield_04.png": ("xield-automacao.png","Xield: automação inteligente de ambientes"),
 "images/xieldimg/xield_05.png": ("xield-integracoes.png","Xield: integração com equipamentos e protocolos"),
 "images/xieldimg/xield_06.png": ("xield-recursos.png","Xield: recursos exclusivos"),
 "images/xieldimg/xield_07.png": ("xield-casos-de-uso.png","Xield: casos de uso"),
 "images/xieldimg/xield_08.png": ("xield-por-que.png","Por que escolher o Xield"),
 "lgpd/img/comite-01.png": ("comite-compliance.png","Comitê de Compliance"),
 "lgpd/img/comite-02.png": ("comite-protecao-de-dados.png","Comitê de Proteção de Dados"),
 "lgpd/img/comite-03.png": ("comite-seguranca.png","Comitê de Segurança e Qualidade"),
 "lgpd/img/treinamento.png": ("trix-academy.png","Trix Academy - treinamento e capacitação"),
 "webinario/assets/img/trixti.png": ("trixti-webinario.png","Trix TI"),
 "favicon.ico": ("favicon.png","Ícone Trix"),
}
UNIMED = ["40","41","42","43","45","46","47","49","50","51","52","53","55","56","57","58","59","61","62","65","66","67","69","70","71"]
for n in UNIMED: MEDIA[f"images/unimed/{n}.png"]=(f"cliente-unimed-{n}.png","Cliente Trix (Unimed)")
for n in ["unimed-curitiba","unimed-sao-joao","unimed-serra-minas","unimed-uba"]: MEDIA[f"images/unimed/{n}.jpg"]=(f"cliente-{n}.jpg","Cliente Trix "+n.replace('-',' ').title())
