export const meta = {
  name: 'telix-pages',
  description: 'Redige e revisa adversarialmente as 19 páginas restantes do site Télix',
  phases: [
    { title: 'Write', detail: 'um redator por página (HTML do design system + SEO)' },
    { title: 'Review', detail: 'revisor adversarial corrige fatos, completude, validador, SEO e a11y' },
  ],
}
const REPO = '/home/user/OutrosProjetos/telix-site'
const R = args.research
const COMMON = `
You are writing ONE page of the new corporate website of TÉLIX Comunicação e Relacionamento (legal name Telix Comunicações Ltda., CNPJ 16.881.685/0001-62, founded 06/09/2012 — "desde 2012", 14 years in 2026; the old site says "mais de 10 anos"). Télix is a contact-center specialised in Saúde Suplementar (health plan operators, mainly the Unimed system). Operational unit: Brasil Center Shopping, 1º piso, Av. Marginal da BR-040, Parque Esplanada III, Valparaíso de Goiás/GO, CEP 72876-359; matriz: SIG Quadra 4, Lote 75, Bloco A, Sala 15, Brasília/DF. Phone (61) 3771-1100; e-mails falecom@telixcom.com.br, ouvidoria@telixcom.com.br, dpo@telixcom.com.br (Encarregado/DPO: Sanclé Landim Albuquerque). Portfolio: 15 client cooperatives/operators in 7 states (MT, MS, GO, MA, AL, RO, PA). Remoção/regulação central works 24h/7 via phone and WhatsApp.
Site language: Brazilian Portuguese (pt-BR). Audience: decision makers at operadoras de planos de saúde (Unimed singulares/federações, other operators), hospitals, clinics; also beneficiaries, candidates, suppliers, regulators, data subjects, whistleblowers.

MANDATORY READING before writing (use the Read tool):
1. ${REPO}/docs/AUTHORING.md — page format, META header, tokens, component classes, form markup, content rules. Follow it strictly.
2. ${REPO}/src/pages/inicio.html and ${REPO}/src/pages/canal-lgpd.html — reference pages that define the quality bar, structure and component usage. Match their style.
3. Research (facts ONLY from these; never invent numbers, certifications, awards, testimonials, SLAs, client results):
   - ${R}/original_inventory.md (everything on the old site — text you must preserve/improve), ${R}/original_privacy_policy.txt
   - ${R}/regulatory.md (verified norms; PART C "Frases seguras / Frases a evitar" is binding)
   - ${R}/company_data.json, ${R}/location.md, ${R}/digital_presence.md, ${R}/clients.json, ${R}/clients_summary.json
   - ${R}/copy_strategy.md and ${R}/master_brief.md IF they exist (they may not yet).
4. ${REPO}/config/site.json (clients list, tokens) and ${REPO}/docs/icons.txt (valid icon names for [[i:name]]).

HARD RULES:
- Write ONLY your page file (path given below). Do NOT edit CSS, JS, tools, config or other pages.
- Use only existing design-system classes/components from AUTHORING.md; no <style> blocks, no <script> except none (the runtime handles everything). Inline style only for tiny spacing tweaks.
- Internal links root-relative and only to pages listed in AUTHORING.md. Exactly one <h1>. Headings in order. Every <img> with meaningful alt. Unique ids.
- Page hero: use the .tx-pagehero pattern with visible breadcrumb (nav > ol.tx-breadcrumb) and eyebrow/h1/lead/buttons; a 3D visual in .tx-pagehero__3d when it adds value (data-tx-3d="network" with data-variant="light" and 3-5 short data-labels relevant to the page; "shield" for compliance/privacy/security topics; "route" for remoção/regulação).
- Persuasion with ethical triggers (authority via norms/specialisation, social proof via real clients, risk reduction, clarity via step lists, reciprocity via useful content/FAQ, progressive CTAs). Benefit-first headlines. Short paragraphs. Every page ends with a CTA and 2–4 related internal links.
- SEO: META.seo.title 30–60 chars (brand at the end "| Télix"), description 140–160 chars, keywords, pageType, and schema entries where relevant (Service for solution pages with "provider":"org", "areaServed":"BR", "url":"{home}/..."; AboutPage/CollectionPage/FAQPage context via pageType). Include natural keyword usage in h1/h2/body. Add a FAQ block (.tx-faq[data-schema]) with 3–6 genuinely useful Q&As on commercial/solution pages.
- Regulatory accuracy: RN ANS 623/2024 (in force since 01/07/2025, replaced RN 395), RN 566/2022 (prazos máximos, replaced RN 259), RN 490/2022 (cobertura de remoção in hospital plans after carência) + Lei 9.656/1998 art. 12 II "e" + Resolução CONSU 13/1998 (urgência/emergência) + CFM 1.672/2003 and 2.110/2014. Say Télix "apoia" operators; never promise total compliance; never use "regulação médica" or "vaga zero"; decisions clínicas são do médico. ANPD = "Agência Nacional de Proteção de Dados" (Lei 15.352/2026). PL 2338/2023 is NOT law. No ISO certification claims (you may say "tomamos como referência a ISO/IEC 27001" etc.).
- Personal data: do not publish names of people other than the DPO (Sanclé Landim Albuquerque). Do not mention the Trix group/holding.
- Validate before finishing: run \`cd ${REPO} && python3 tools/validate.py src/pages/<your-file>\` and fix until 0 errors (warnings about SEO length should also be fixed).
Your final answer: a short summary (<= 200 words) of the page structure, which original-site items you included, and any fact you deliberately left out or could not verify.`

const PAGES = [
  { file: 'a-telix.html', slug: 'a-telix', parent: '', order: 10, brief: `"A Télix" (Quem somos, AboutPage). Must include, improved: original sections 1.4 "A Empresa / NOSSO FOCO É A GERAÇÃO DE RESULTADOS" (both paragraphs), Missão (full quote), Visão (full quote) and the 8 Valores (Satisfação, Atendimento Humanizado, Resolutividade, Foco no cliente, Ética, Transparência, Valorização dos colaboradores, Qualidade no serviço) — present Missão/Visão as 3D flip cards (.tx-flip) and the 8 values in the 3D ring (.tx-ring with --i:0..7, short descriptions per value) inside a section with id="missao-visao-valores". A section id="diferenciais" with 6+ differentiators (from original: excelência, foco no resultado, gestão interna proativa, ferramental tecnológico, especialistas em atendimento e regulação, experiência com ANS, treinamento constante). A timeline (.tx-timeline) using ONLY verified facts: 2012 fundação (CNPJ matriz aberto em 06/09/2012); 2015 palestra "Call Center, ANS e Legislação" apresentada em evento do setor (SlideShare, see digital_presence.md) — phrase carefully; 2021 abertura da unidade de Valparaíso de Goiás no Brasil Center Shopping (filial aberta em 02/08/2021); 2026 novo site com canais de conformidade (LGPD, denúncia) e acessibilidade. "Nossa estrutura": unit in Valparaíso + matriz Brasília, 24/7 central. Stats (only true ones: desde 2012, 15 clientes, 7 estados, 24/7). Images: {{IMG_CENTRAL_A}}, {{IMG_SARH2}}. Link to /clientes/, /conformidade/, /trabalhe-conosco/.` },
  { file: 'especialistas-em-saude-suplementar.html', slug: 'especialistas-em-saude-suplementar', parent: '', order: 11, brief: `"Especialistas em Saúde Suplementar". Must include the full original section 1.9 "Experiência em Atendimento Saúde Suplementar" (Télix é especialista em atendimento privado de saúde; profissionais altamente qualificados; larga experiência no mercado e na agência reguladora ANS; definition of saúde suplementar; actors: governo/Ministério da Saúde, ANS, ANVISA, operadoras, seguradoras, prestadores) — rewritten for clarity. Add an explainer of the regulatory landscape that matters for customer service (from regulatory.md: RN 623/2024 protocol & response deadlines & Ouvidoria reanálise; RN 566/2022 prazos máximos; RN 490/2022 + CONSU 13 remoção; NIP; IGR; IDSS/PQO; Decreto 11.034/2022 SAC; Manual de Intercâmbio Nacional do Sistema Unimed) with "how Télix helps" for each, in cards or a table. Use {{IMG_REG_SUP}} image. CTA to solutions. This is an authority/SEO page targeting "atendimento saúde suplementar", "call center operadora de plano de saúde", "RN 623", "NIP ANS".` },
  { file: 'solucoes.html', slug: 'solucoes', parent: '', order: 20, brief: `"Soluções" hub (CollectionPage). Must include original 1.6 "Serviços — Nossa meta é sempre CONHECER MAIS! Com investimentos frequentes em treinamentos..." and 1.7 "Soluções Oferecidas" full list (SAC; Realização de Pesquisa — Satisfação de Beneficiários; Sistema de Atendimento — Registro de Protocolo, direcionamento para tratativas de SAC e RN 623; Centrais de Atendimento para: Regulação de Vaga e Transporte Médico; Agendamento conforme a RN 566; Agendamento para hospitais, clínicas e consultórios médicos; Apoio e Análise de Qualidade de Atendimento; Atendimento WEB – WhatsApp e Chatbots). Present 8 solution cards (tx-tilt) linking to: /solucoes/central-de-atendimento/, /solucoes/sac/, /solucoes/sistema-de-protocolo/, /solucoes/regulacao-e-remocao-hospitalar/, /solucoes/agendamento/, /solucoes/pesquisa-de-satisfacao/, /solucoes/atendimento-digital/, /solucoes/qualidade-e-monitoria/. Add a "which norm each solution supports" table (RN 623, RN 566, RN 490/CONSU 13, Decreto 11.034, LGPD), a "combine into an integrated operation" section, the implementation journey (steps), FAQ, CTA. Images {{IMG_SOL1}}..{{IMG_SOL4}} optional.` },
  { file: 'central-de-atendimento.html', slug: 'central-de-atendimento', parent: 'solucoes', order: 21, brief: `Solution page "Central de Atendimento — Call Center Ativo e Receptivo". Must include original 1.8 texts: "Durante a abordagem, a empresa tem o importante papel de conquistar e deixar boas impressões, independente do motivo do contato." and the full "Central de Atendimento - Call Center Ativo e Receptivo" paragraph (equipe qualificada em teleatendimento ativo e receptivo; capacitação constante; melhoria contínua; maximizar investimento e retorno; equipe paciente, cordial, boa comunicação, trabalho em equipe, concentração, sinergia com o computador). Expand: receptivo vs ativo use cases for operators (boas-vindas, atualização cadastral, lembretes, campanhas de prevenção, pesquisa, retorno de protocolos), indicators we measure (TMA, TME, nível de serviço, abandono, FCR — as what we monitor, not claimed values), ergonomics/quality of staff per NR-17 Anexo II (humanized operation = better service), LGPD. Images {{IMG_CENTRAL}}, {{IMG_SOL1}}. Schema Service.` },
  { file: 'sac.html', slug: 'sac', parent: 'solucoes', order: 22, brief: `Solution page "SAC para operadoras — Serviço de Atendimento ao Consumidor/Cliente" (original 1.7 item "SAC — Serviço de Atendimento ao Consumidor/ Cliente"). Explain how Télix operates an SAC aligned with Decreto 11.034/2022 (regras gerais do SAC) and RN 623/2024 for health plan operators (use the comparison table from regulatory.md A10 "Quadro comparativo RN 623 x Decreto 11.034"), protocol at the first contact, escalation to Ouvidoria, records/gravações retention, reclamações, elogios, sugestões, reports. Image {{IMG_SOL4}}. Schema Service. FAQ.` },
  { file: 'sistema-de-protocolo.html', slug: 'sistema-de-protocolo', parent: 'solucoes', order: 23, brief: `Solution page "Sistema de Atendimento e Protocolo (RN 623)". Original: "Sistema de Atendimento — Disponibilização para Registro de Protocolo, com direcionamento para tratativas de SAC e RN 623". Detail RN 623/2024 obligations from regulatory.md A2 (protocolo como primeira ação em qualquer canal, prazos de resposta, informação ao beneficiário, reanálise pela Ouvidoria, guarda de registros/gravações; penalties context RN 489 art. 99 / RN 659/2025; NIP/IGR). How the Télix protocol flow works (steps: registro → classificação → direcionamento à área responsável da operadora → acompanhamento de prazo → resposta → evidência/relatório). Rastreabilidade and monthly indicators. Image {{IMG_SOL2}}. Schema Service. Be careful: "apoiamos a operadora a cumprir".` },
  { file: 'regulacao-e-remocao-hospitalar.html', slug: 'regulacao-e-remocao-hospitalar', parent: 'solucoes', order: 24, brief: `Solution page "Regulação de Vagas e Remoção Hospitalar 24h" — the flagship. MUST include ALL of original section 1.10 improved: "Serviço de Atendimento Remoção Hospitalar" paragraph; "Atuamos com eficiência, rapidez e profissionalismo..."; "Equipe Especializada e Capacitada" (avaliação rápida da condição, urgência e gravidade, protocolos de triagem baseados em evidências); "Atendimento 24 horas via Central Telefônica e WhatsApp" (24/7, regulação de vaga e acionamento de transporte, resposta rápida); "Serviços inclusos" (Rastreabilidade do Processo — todo o atendimento é monitorado e registrado; Indicadores Mensais — relatórios detalhados; Regulação de vaga hospitalar; Acionamento de transporte; Autorização de atendimento vinculado ao serviço de remoção; Realização de cotação de transporte com empresas terceirizadas); "Para o Sistema Unimed: Padronização do processo conforme as regras do Manual de Intercâmbio"; "Melhor Custo-Benefício" paragraph. FIX the normative basis per regulatory.md A4/A5: Lei 9.656/1998 art. 12 II "e", RN 490/2022 (remoção em planos hospitalares após carência — list its cases), Resolução CONSU 13/1998 (urgência/emergência, art. 7º), CFM 1.672/2003 and 2.110/2014 (decisão clínica é do médico; providências administrativas/operacionais não são ato médico — where Télix acts). Use "apoio operacional à regulação de vagas e à remoção". Use the 3D "route" scene in the hero. Images {{IMG_SARH1}} ... {{IMG_SARH5}}, {{IMG_BG01}}. Process steps, FAQ, strong CTA (WhatsApp {WA_LINK}, phone {TEL_LINK}, /contato/#proposta). Schema Service (serviceType "Regulação de vagas e remoção hospitalar").` },
  { file: 'agendamento.html', slug: 'agendamento', parent: 'solucoes', order: 25, brief: `Solution page "Agendamento de Consultas, Exames e Procedimentos (RN 566)". Original items: "Agendamento de Atendimento conforme a RN 566" and "Agendamento para hospitais, clínicas e consultórios médicos". Include the RN 566/2022 maximum-deadline table (from regulatory.md A3, dias úteis: 7/14/10/7/3/10/21/21/10/10/10/imediato), the alternatives when there is no provider (arts. 4º–6º, transporte), protocol (art. 12), and the warning that RN 623's 10 dias úteis is a response deadline not realization. Two audiences: operators (garantia de atendimento, redução de NIP por descumprimento de prazo) and hospitals/clinics/consultórios (agenda, confirmação, lembretes, redução de faltas — no invented numbers). Schema Service. FAQ.` },
  { file: 'pesquisa-de-satisfacao.html', slug: 'pesquisa-de-satisfacao', parent: 'solucoes', order: 26, brief: `Solution page "Pesquisa de Satisfação de Beneficiários". Original item "Realização de Pesquisa — Satisfação de Beneficiários de Planos de Saúde". Explain methods (telefone ativo, WhatsApp, pós-atendimento), what is measured (satisfação, NPS/CSAT as methods, motivos de insatisfação), how results feed action plans and monthly reports; context of IDSS/PQO from regulatory.md A8 — phrase carefully: the IDSS satisfaction survey has specific ANS technical requirements (statistician, audit); say Télix can execute/operate survey fieldwork and support the operator "conforme o desenho metodológico definido pela operadora e pelas diretrizes aplicáveis da ANS" — do not claim Télix is the certified/responsible statistician. Image {{IMG_SOL3}}. Schema Service. FAQ.` },
  { file: 'atendimento-digital.html', slug: 'atendimento-digital', parent: 'solucoes', order: 27, brief: `Solution page "Atendimento Digital: WhatsApp e Chatbots". Original: "Atendimento WEB – WhatsApp e Chatbots"; and remoção section: "Atendimento 24 horas via Central Telefônica e WhatsApp". Explain omnichannel (voz + WhatsApp + web chat), chatbot for triage/FAQ with seamless human handoff, protocol in every channel (RN 623 applies to any channel), LGPD and security, transparency that the user is talking to a bot, human review of automated decisions (LGPD art. 20) — link to /conformidade/politica-de-inteligencia-artificial/. Image {{IMG_SARH3}} (arte WhatsApp central de atendimento). Schema Service. FAQ.` },
  { file: 'qualidade-e-monitoria.html', slug: 'qualidade-e-monitoria', parent: 'solucoes', order: 28, brief: `Solution page "Qualidade e Monitoria do Atendimento". Original item "Apoio e Análise de Qualidade de Atendimento". Monitoria de ligações e conversas, checklists de qualidade aderentes às normas, calibração, feedback e plano de desenvolvimento dos atendentes, análise de causa-raiz de reclamações, relatórios mensais e indicadores (list what is measured), gravações guardadas pelos prazos da RN 623 e Decreto 11.034, treinamento contínuo ("Nossa meta é sempre conhecer mais"). Could be offered as standalone to operators with own call center. Image {{IMG_SARH4}}. Schema Service. FAQ.` },
  { file: 'clientes.html', slug: 'clientes', parent: '', order: 30, brief: `"Clientes" (CollectionPage). Must show all 15 clients (config/site.json clients) using the token {{LOGO_GRID}} (it renders logo cards) and ALSO a richer list grouped by state with each client's name, city/UF and a 1–2 sentence public description from clients.json (respectful, factual; no beneficiary numbers unless clearly sourced; better omit numbers). Include the 3D map exactly like inicio.html (div.tx-mapwrap > div.tx-3d[data-tx-3d="brmap"][data-served='{{SERVED_JSON}}'] + legend) AND add <script type="application/json" id="tx-br-geo">{{BR_GEO}}</script> at the END of the page (required for the map). Use {{N_CLIENTES}}, {{N_ESTADOS}}, {{SERVED_LIST}} tokens for counts. Original texts: "Nossos Clientes", "Somos movidos pela satisfação dos nossos clientes, que atualmente podemos chamá-los de parceiros nessa história de sucesso e crescimento", "Para o Sistema Unimed: Padronização do processo conforme as regras do Manual de Intercâmbio", "atende vários estados do país". Add: what the Sistema Unimed/intercâmbio means for customer service; regions (Centro-Oeste, Norte, Nordeste). Do NOT claim "parceiro oficial Unimed". Add a small note that logos are trademarks of their owners. CTA to become a client.` },
  { file: 'conformidade.html', slug: 'conformidade', parent: '', order: 40, brief: `"Conformidade" hub (the compliance page requested by the client). MUST contain: section id="identidade" with Missão, Visão and the 8 Valores (same texts as the company: use cards or flip cards); section id="politica-integrada" with a well-written "Política Integrada de Gestão" statement (commitments: excelência e satisfação do cliente/beneficiário, cumprimento legal e regulatório (ANS, LGPD, anticorrupção, trabalhista), privacidade e proteção de dados, segurança da informação, ética e integridade/tolerância zero à corrupção e ao assédio, responsabilidade socioambiental (ESG), uso ético e responsável de IA, acessibilidade e inclusão, capacitação contínua, melhoria contínua) signed "A Diretoria" with version/vigência; a policy library (.tx-policy-list) linking to /conformidade/politica-de-privacidade/, /conformidade/politica-de-compliance/, /conformidade/politica-de-seguranca-da-informacao/, /conformidade/politica-esg/, /conformidade/politica-de-inteligencia-artificial/, /conformidade/politica-de-cookies/, /conformidade/glossario-lgpd/, /acessibilidade/; channels section (/canal-lgpd/, /canal-de-denuncia/, Ouvidoria {{OUVIDORIA_0800}} and {{OUVIDORIA_EMAIL}}, DPO). Preserve the old LGPD portal content (original_inventory.md section 3.1): intro "TÉLIX e LGPD / Segurança e proteção de dados — Afirmamos nosso compromisso..."; "Como tratamos seus dados" (Colaboradores = operadores de dados...; Fornecedores e Parceiros = operadores, responsabilidade solidária...); "Nossos Comitês" — Compliance, Proteção de Dados, Segurança e Qualidade — with their Atribuições (improved lists) and composition by ROLE only (Compliance Officer / DPO: Sanclé Landim Albuquerque; others as "Patrocinadores membros do comitê" and "Security Officer" WITHOUT names) using images {{IMG_COMITE1}}, {{IMG_COMITE2}}, {{IMG_COMITE3}}; "Treinamento e Capacitação" (no broken Trix Academy link; say trainings are periodic and mandatory); "Ouvidoria: críticas, elogios, denúncias e sugestões" with {{OUVIDORIA_0800}}. Include the YouTube video "TÉLIX - Introdução a LGPD" consent-gated using the .tx-map pattern with data-src="https://www.youtube-nocookie.com/embed/9DEchcquwbY" data-title="Vídeo: TÉLIX - Introdução à LGPD" data-tx-consent="functional" (gate text adapted to video; min-height via inline style aspect-ratio:16/9). Hero with 3D "shield". pageType WebPage.` },
  { file: 'politica-de-privacidade.html', slug: 'politica-de-privacidade', parent: 'conformidade', order: 11, brief: `"Política de Privacidade e Proteção de Dados (LGPD)" — full legal document using the .tx-doc layout (TOC aside + article.tx-prose with numbered h2 sections, tx-docmeta with Versão 2.0, vigência setembro de 2026, substitui versão de 28/09/2020). Rewrite and UPDATE the original policy (${R}/original_privacy_policy.txt — preserve every substantive clause: definitions, data collected (cadastro, navegação, IP, gravações de contato), purposes, sharing, security, retention, user rights, cookies, third parties/terceirizados, specific conditions for licensed systems "SAW, SAW Call e Aplicativos SAW Mobile" (keep as in original), lei aplicável e foro de Brasília/DF salvo direito do consumidor, contato do DPO) and ADD: controller identification (Telix Comunicações Ltda., CNPJ {{CNPJ}} matriz {{MATRIZ_ENDERECO}}; filial {{CNPJ_FILIAL}} Valparaíso), Télix's dual role (controladora for its own site/HR/suppliers; operadora when serving health plan operators — beneficiary data belongs to the operator/controller), table of purposes × legal bases (art. 7º and art. 11 for dados sensíveis de saúde), children/adolescents, international transfer (Google Fonts/Maps, CDN), retention table (formulários do site; gravações de atendimento per RN 623 — 90 dias e 2 anos / 5 anos quando há reclamação, per regulatory.md; logs de acesso 6 meses Marco Civil art. 15; banco de talentos 12 meses; relatos do canal de denúncia enquanto necessário para apuração e defesa), security measures, incidents (art. 48; ANPD communication), rights (art. 18) with /canal-lgpd/, ANPD = Agência Nacional de Proteção de Dados, updates. Remove generic template clauses from the old text that don't apply (payments/cards, biometrics, KYC) — list what you removed in your summary. Hero simple (no 3D needed) like politica-de-cookies.html.` },
  { file: 'politica-de-compliance.html', slug: 'politica-de-compliance', parent: 'conformidade', order: 12, brief: `"Política de Compliance e Integridade (Código de Conduta)" — .tx-doc legal document (versão 1.0, vigência setembro de 2026). Content: objetivo e abrangência (colaboradores, lideranças, fornecedores, parceiros); princípios (from the company values); anticorrupção (Lei 12.846/2013, Decreto 11.129/2022 — programa de integridade elements), relacionamento com agentes públicos incluindo a ANS e órgãos de fiscalização, brindes/presentes/hospitalidades, doações e patrocínios, conflito de interesses, registros contábeis e controles (from the Compliance committee attributions), prevenção a fraudes, due diligence de terceiros, assédio moral e sexual e discriminação (Lei 14.457/2022), respeito no atendimento ao beneficiário, confidencialidade e LGPD, uso de recursos e redes sociais, canal de denúncia e proteção ao denunciante/não retaliação (Lei 13.608/2018), apuração e medidas disciplinares, treinamentos periódicos, papéis (Alta Direção, Comitê de Compliance, Compliance Officer), revisão periódica. Reference ISO 37301/37001 only as "referências de boas práticas". Link to /canal-de-denuncia/. Hero simple.` },
  { file: 'politica-de-seguranca-da-informacao.html', slug: 'politica-de-seguranca-da-informacao', parent: 'conformidade', order: 13, brief: `"Política de Segurança da Informação" — .tx-doc (versão 1.0, vigência setembro de 2026). Content: objetivos (confidencialidade, integridade, disponibilidade, autenticidade), abrangência, papéis (Alta Direção, Comitê de Segurança e Qualidade, Security Officer, DPO, gestores, colaboradores, terceiros) — include the committee attributions from the old LGPD portal (original_inventory 3.1 card 3) improved; classificação da informação; controle de acesso (mínimo privilégio, MFA, revisão periódica); senhas; mesa e tela limpas (essencial em central de atendimento), uso de celulares/dispositivos na operação, gravações e registros de atendimento; backup e continuidade (a operação 24/7 depende disso); gestão de vulnerabilidades e atualizações; fornecedores; desenvolvimento/sistemas; monitoramento e logs (Marco Civil); gestão de incidentes (LGPD art. 48, comunicação à ANPD e titulares conforme Resolução CD/ANPD nº 15/2024); conscientização e treinamento; sanções; revisão. ISO/IEC 27001:2022 and 27701 as reference only. Hero simple or 3D shield.` },
  { file: 'politica-esg.html', slug: 'politica-esg', parent: 'conformidade', order: 14, brief: `"Política ESG — Ambiental, Social e Governança" — .tx-doc (versão 1.0, vigência setembro de 2026). Content: compromisso; Ambiental (operação digital e redução de papel, eficiência energética, descarte correto de eletrônicos/e-lixo, consumo consciente, deslocamento — unit near public transport); Social (colaboradores: ergonomia, pausas e condições do teleatendimento conforme NR-17 Anexo II; saúde mental e riscos psicossociais (NR-1); diversidade, equidade e inclusão; combate ao assédio (Lei 14.457/2022); capacitação; primeiro emprego/empregabilidade local em Valparaíso de Goiás — phrase as intention, no numbers; beneficiários: atendimento humanizado e acessível; comunidade); Governança (ética, compliance, LGPD, segurança, transparência, gestão de riscos, canais); alinhamento aos ODS da Agenda 2030 (3, 4, 5, 8, 10, 12, 16) as alignment, not certification; GRI as reference; metas e monitoramento (qualitative commitments, no invented metrics); revisão anual. Hero with 3D network light labels (Ambiental, Social, Governança).` },
  { file: 'politica-de-inteligencia-artificial.html', slug: 'politica-de-inteligencia-artificial', parent: 'conformidade', order: 15, brief: `"Política de Uso Ético e Responsável de Inteligência Artificial" — .tx-doc (versão 1.0, vigência setembro de 2026). Content: finalidade e escopo (chatbots, roteamento/triagem de demandas, transcrição e análise de qualidade, apoio à produtividade); princípios (centralidade humana, supervisão humana, transparência — o usuário sabe quando fala com um robô, não discriminação, privacidade desde a concepção, segurança, prestação de contas, precisão); usos proibidos (decisões clínicas, autorização/negativa de cobertura sem revisão humana, "vaga zero" — careful: just say decisões assistenciais/clínicas), direito de revisão de decisões automatizadas (LGPD art. 20), dados pessoais e dados sensíveis de saúde (minimização, anonimização quando possível, sem uso de dados de clientes para treinar modelos de terceiros sem autorização contratual), avaliação de riscos e impacto antes de adotar novas ferramentas, fornecedores de IA, registro/inventário de sistemas de IA, treinamento, governança (Comitê), monitoramento regulatório (PL 2338/2023 em tramitação — not law; ISO/IEC 42001:2023 as reference), canal para dúvidas (/canal-lgpd/, /contato/). Hero 3D network light labels (Ética, Transparência, Supervisão humana).` },
  { file: 'perguntas-frequentes.html', slug: 'perguntas-frequentes', parent: '', order: 50, brief: `"Perguntas Frequentes" (pageType FAQPage). 24–32 Q&As grouped by category with h2 headings and one .tx-faq[data-schema] per category: A Télix (fundação desde 2012, localização, estados/clientes, especialidade); Soluções (quais serviços, 24/7, WhatsApp, integração com sistemas da operadora, indicadores/relatórios, implantação); Normas ANS (RN 623 protocolo, RN 566 prazos, RN 490/remoção, NIP — as helpful explanations and how Télix supports); Contratação (como solicitar proposta, para quem, operadoras fora do Sistema Unimed, hospitais/clínicas); Privacidade e segurança (LGPD, DPO, dados de saúde, Canal LGPD, cookies); Canais (denúncia anônima, ouvidoria, protocolo); Carreiras (como se candidatar, anexo por e-mail, taxa nunca cobrada). Answers accurate and consistent with the other pages; link to relevant pages inside answers. Add a search/filter input is NOT needed. Hero simple with 3D network light labels (Dúvidas, Respostas, Suporte).` },
]

const SEL = (args.pages && args.pages.length) ? PAGES.filter(p => args.pages.includes(p.slug)) : PAGES
log('páginas: ' + SEL.map(p => p.slug).join(', '))
phase('Write')
const results = await pipeline(
  SEL,
  p => agent(`${COMMON}

YOUR PAGE: file ${REPO}/src/pages/${p.file}
META: "slug": "${p.slug}", "parent": "${p.parent}", "menu_order": ${p.order}. Breadcrumb must reflect the hierarchy (Início → ${p.parent ? p.parent === 'solucoes' ? 'Soluções (/solucoes/) → ' : 'Conformidade (/conformidade/) → ' : ''}page). URL of this page: ${p.parent ? '/' + p.parent + '/' + p.slug + '/' : '/' + p.slug + '/'}
BRIEF: ${p.brief}

Write the complete page now (substantial, polished, persuasive, accurate), then validate with the validator and fix all errors.`, { label: `write:${p.slug}`, phase: 'Write' }),
  (writeSummary, p) => agent(`${COMMON}

You are the ADVERSARIAL REVIEWER for ${REPO}/src/pages/${p.file} (slug ${p.slug}). A writer produced it; its summary: """${writeSummary}"""
The page brief was: ${p.brief}

Do a rigorous review and FIX the file directly (Edit tool):
1. FACTS: check every factual claim (numbers, dates, norms and article numbers, deadlines, company facts, client facts) against the research files. Remove or rephrase anything unsupported or overstated. Apply regulatory.md PART C rules.
2. COMPLETENESS: open ${R}/original_inventory.md and confirm every original-site item named in the brief appears (improved but faithful). Add anything missing.
3. PERSUASION & CLARITY: benefit-led headings, scannable structure, strong but honest CTAs, good pt-BR (grammar, accents, crase, consistent terminology "Télix"). Remove repetition and filler.
4. TECH: run \`cd ${REPO} && python3 tools/validate.py src/pages/${p.file}\` → 0 errors and no SEO-length warnings. Check component markup matches AUTHORING.md exactly (e.g., .tx-flip structure, .tx-ring items with --i, .tx-map gate, tabs ARIA, form rules), links root-relative and valid, one h1, heading order, alt texts, unique ids, META JSON valid, schema sensible.
5. VISUAL: run \`cd ${REPO} && python3 tools/build.py >/dev/null && python3 tools/preview.py >/dev/null && node tools/shots.js file://${REPO}/dist/preview/${p.file} /tmp/review-${p.slug} 1440 900\` and LOOK at 3–5 of the resulting PNGs (/tmp/review-${p.slug}-00.png ...) with the Read tool; fix layout problems caused by the page markup (e.g., empty sections, misused classes, overlong headings). Do not edit global CSS/JS.
Final answer: concise list of the fixes you made and any residual risk/open question for the client (<= 200 words).`, { label: `review:${p.slug}`, phase: 'Review' }).then(r => ({ page: p.slug, review: r })),
)
return results.filter(Boolean)
