# Dados institucionais e estrutura de navegação (megamenu, drawer, rodapé)
SITE = {
 "name": "Trix Tecnologia Inteligente",
 "description": "Software sob medida, conectividade em saúde suplementar, consultoria e produtos com IA. Desde 2009 em Brasília, atendendo empresas de todo o Brasil.",
 "phone": "(61) 3403-5353", "phone_e164": "+556134035353", "phone_sp": "(11) 3014-3220", "phone_sp_e164": "+551130143220",
 "phone_prontow": "(61) 3246-1800", "ouvidoria": "0800 941 1190", "ouvidoria_e164": "+5508009411190",
 "email": "falecom@trixti.com.br", "email_dpo": "dpo@trixti.com.br", "email_ouvidoria": "ouvidoria@trixti.com.br", "email_seguranca": "seguranca@trixti.com.br",
 "address_line1": "Edifício Capital Financial Center — SIG Quadra 4, Lote 75, Bloco A, Sala 15", "address_line2": "Zona Industrial (Guará) · Brasília – DF · CEP 70610-440",
 "address_sp": "Alameda Santos, 1165 — Cerqueira César · São Paulo – SP · CEP 01419-002",
 "geo": {"lat": -15.787418, "lng": -47.913077},
 "maps_url": "https://www.google.com/maps/search/?api=1&query=SIG+Quadra+4+Lote+75+Bloco+A+Sala+15+Bras%C3%ADlia+DF+70610-440",
 "maps_embed": "https://www.google.com/maps?q=Edif%C3%ADcio+Capital+Financial+Center+SIG+Quadra+4+Lote+75+Bras%C3%ADlia+DF&z=16&output=embed",
 "maps_embed_sp": "https://www.google.com/maps?q=Alameda+Santos+1165+Cerqueira+C%C3%A9sar+S%C3%A3o+Paulo+SP&z=16&output=embed",
 "waze_url": "https://waze.com/ul?ll=-15.787418,-47.913077&navigate=yes",
 "social": {"linkedin": "https://www.linkedin.com/company/trix-tecnologia-inteligente", "instagram": "https://www.instagram.com/trix_tecnologia/", "facebook": "https://www.facebook.com/trixti/",
            "whatsapp": "https://wa.me/5561992324516?text=Ol%C3%A1!%20Vim%20pelo%20site%20da%20Trix%20e%20gostaria%20de%20falar%20com%20um%20consultor.",
            "whatsapp_prontow": "https://wa.me/556132461800?text=Ol%C3%A1!%20Quero%20uma%20demonstra%C3%A7%C3%A3o%20do%20Prontow."},
 "favicon": "{{media:favicon.ico}}", "ga4": "",
 "cnpj": "11.010.095/0001-40", "founded": "10/07/2009",
}
NAV = [
 {"label": "Home", "url": "/"},
 {"label": "A Trix", "title": "Conheça a Trix", "feature": {"title": "Desde 2009 transformando tecnologia em resultado", "text": "Fábrica de software, conectividade em saúde e IA aplicada, com governança, LGPD e compliance de verdade.", "url": "/empresa/", "cta": "Nossa história"},
  "children": [
   {"label": "Sobre a Trix", "desc": "História, propósito e diferenciais", "url": "/empresa/", "icon": "building"},
   {"label": "Missão, visão e valores", "desc": "O que nos move todos os dias", "url": "/empresa/#missao", "icon": "target"},
   {"label": "Governança e comitês", "desc": "Compliance, proteção de dados e segurança", "url": "/conformidade/", "icon": "shield"},
   {"label": "Clientes", "desc": "Operadoras, Unimeds, RHs e prestadores", "url": "/clientes/", "icon": "users"},
   {"label": "Oracle PartnerNetwork", "desc": "Membro OPN com soluções Oracle", "url": "/servicos/oracle-partner/", "icon": "award"},
   {"label": "Eventos e Trix Academy", "desc": "Webinários e capacitação", "url": "/empresa/eventos/", "icon": "graduation"},
  ]},
 {"label": "Serviços", "title": "Serviços sob medida para o seu negócio", "feature": {"title": "Fale com um consultor", "text": "Diagnóstico gratuito e sem compromisso para encontrar a solução ideal para sua operação.", "url": "/contato/", "cta": "Agendar conversa"},
  "children": [
   {"label": "Fábrica de software", "desc": "Metodologia PROTRIX, do requisito ao teste", "url": "/servicos/fabrica-de-software/", "icon": "code"},
   {"label": "Conectividade em saúde", "desc": "TISS, elegibilidade, faturamento e suporte", "url": "/servicos/conectividade-em-saude/", "icon": "network"},
   {"label": "Consultoria", "desc": "Outsourcing, segurança, APF, processos", "url": "/servicos/consultoria/", "icon": "briefcase"},
   {"label": "Escritório de processos", "desc": "BPM, governança e metodologia MTRIX", "url": "/servicos/escritorio-de-processos/", "icon": "flow"},
   {"label": "Soluções e automação", "desc": "Demandas, projetos, qualidade e monitoramento", "url": "/servicos/solucoes-e-automacao/", "icon": "gear"},
   {"label": "Agenda médica", "desc": "Central de atendimento para sua agenda", "url": "/servicos/agenda-medica/", "icon": "calendar"},
   {"label": "Oracle Partner", "desc": "Cloud, banco de dados e integração Oracle", "url": "/servicos/oracle-partner/", "icon": "cloud"},
   {"label": "Todos os serviços", "desc": "Visão geral do portfólio", "url": "/servicos/", "icon": "grid"},
  ]},
 {"label": "Produtos", "title": "Produtos que facilitam a vida de milhares de pessoas", "feature": {"title": "Prontow: agendamento por WhatsApp com IA", "text": "Gestão completa para clínicas, consultórios e laboratórios — na nuvem, com prontuário, TISS e IA.", "url": "/produtos/prontow/", "cta": "Conhecer o Prontow"},
  "children": [
   {"label": "Prontow", "desc": "Clínicas, consultórios e laboratórios com IA", "url": "/produtos/prontow/", "icon": "stethoscope"},
   {"label": "SAW", "desc": "Sistema de Atendimento Web para operadoras", "url": "/produtos/saw/", "icon": "monitor"},
   {"label": "Portal Operadora", "desc": "Atendimento integrado para cooperativas", "url": "/produtos/portal-operadora/", "icon": "globe"},
   {"label": "Aspect Face", "desc": "API de reconhecimento facial antifraude", "url": "/produtos/aspect-face/", "icon": "face"},
   {"label": "Xield", "desc": "Controle de acesso e automação com biometria", "url": "/produtos/xield/", "icon": "lock"},
   {"label": "GEDAI", "desc": "GED/ECM e bureau de digitalização", "url": "/produtos/gedai/", "icon": "file"},
   {"label": "Integrador", "desc": "Integração de sistemas em tempo real", "url": "/produtos/integrador/", "icon": "plug"},
   {"label": "Intranet Trix", "desc": "Comunicação interna premiada", "url": "/produtos/intranet/", "icon": "intranet"},
  ]},
 {"label": "Clientes", "url": "/clientes/"},
 {"label": "Conformidade", "title": "Central de Conformidade", "feature": {"title": "Fale com o DPO ou com a Ouvidoria", "text": "Canais seguros e confidenciais para titulares de dados, denúncias, dúvidas e sugestões.", "url": "/canal-lgpd/", "cta": "Acessar canais"},
  "children": [
   {"label": "Central de Conformidade", "desc": "Missão, valores e política integrada", "url": "/conformidade/", "icon": "shield"},
   {"label": "Portal de Proteção de Dados", "desc": "Como tratamos dados, comitês e DPO", "url": "/conformidade/lgpd/", "icon": "lock"},
   {"label": "Política de Privacidade", "desc": "Texto integral e condições específicas", "url": "/conformidade/politica-de-privacidade/", "icon": "eye"},
   {"label": "Compliance e Código de Conduta", "desc": "Programa de integridade e anticorrupção", "url": "/conformidade/compliance/", "icon": "scale"},
   {"label": "Segurança da Informação", "desc": "Política e controles de segurança", "url": "/conformidade/seguranca-da-informacao/", "icon": "cpu"},
   {"label": "ESG", "desc": "Ambiental, social e governança", "url": "/conformidade/esg/", "icon": "leaf"},
   {"label": "Inteligência Artificial", "desc": "Uso ético e responsável de IA", "url": "/conformidade/inteligencia-artificial/", "icon": "brain"},
   {"label": "Cookies e glossário", "desc": "Política de cookies e termos LGPD", "url": "/conformidade/cookies/", "icon": "cookie"},
   {"label": "Canal LGPD (titulares)", "desc": "Exerça seus direitos de titular", "url": "/canal-lgpd/", "icon": "users"},
   {"label": "Canal de Compliance", "desc": "Ouvidoria, denúncias e sugestões", "url": "/canal-de-compliance/", "icon": "megaphone"},
  ]},
 {"label": "Contato", "url": "/contato/", "cta": True},
]
