from .helpers import *
import os, re
ORIG = os.path.join(os.path.dirname(os.path.abspath(__file__)), "original")
def orig(name):
    t = open(os.path.join(ORIG, name + ".html"), encoding="utf-8").read()
    t = t.replace('<table>', '<table class="trix-table">')
    # texto herdado: espaços inquebráveis colavam palavras e deixavam linhas curtas no celular
    t = re.sub(r'[ \t]{2,}', ' ', t.replace('\xa0', ' '))
    # <br> soltos antes/depois de blocos geravam vãos grandes
    t = re.sub(r'\s*<br\s*/?>\s*(?=<(?:h[23]|ul|/ul|ol|/ol|li|p|/p)\b)', '\n', t)
    t = re.sub(r'(</(?:h[23]|p|ul|ol)>)\s*<br\s*/?>', r'\1', t)
    # texto solto no início de uma lista vira parágrafo (sem o recuo da lista)
    t = re.sub(r'<ul>\s*([^<]+?)\s*<li>', r'<p>\1</p>\n<ul>\n<li>', t)
    t = t.replace('<a>\nCookies', '<a href="/conformidade/cookies/">\nCookies').replace('<a>\nVoltar políticas de privacidade', '<a href="/conformidade/politica-de-privacidade/">\nVoltar políticas de privacidade')
    return t
PROSE = lambda inner: '<div class="trix-prose">%s</div>' % inner
DRAFT_NOTE = '<p class="trix-note"><strong>Versão 1.0 (minuta, setembro de 2026).</strong> Documento elaborado na construção deste site para consolidar práticas já publicadas pela Trix (Portal de Proteção de Dados, Código de Conduta e Política de Privacidade). Está sujeito à aprovação formal da Diretoria Executiva e dos comitês e a revisão jurídica; os itens redigidos como diretrizes indicam o padrão a ser mantido e evidenciado pela empresa.</p>'
def pol(slug, title, desc, kicker, h1, lead, body, short=None, order=10, image="images/02.jpg", faq_items=None):
    p = {"slug": slug, "parent": "conformidade", "order": order, "title": title, "description": desc, "hero": "dark", "kicker": kicker, "h1": h1, "lead": lead, "body": body, "image": image,
         "actions": [("Canal LGPD", "/canal-lgpd/", "trix-btn--primary"), ("Canal de Compliance", "/canal-de-compliance/", "trix-btn--ghost")]}
    if short: p["short"] = short
    if faq_items: p["faq"] = [{"q": q, "a": a} for q, a in faq_items]
    return p
POLICY_LINKS = [
 {"icon": "lock", "title": "Política de Privacidade e Proteção de Dados (LGPD)", "text": "Como coletamos, usamos, armazenamos e compartilhamos dados pessoais; direitos dos titulares; cookies; contato do DPO. Versão de 28/09/2020.", "url": "/conformidade/politica-de-privacidade/", "cta": "Ler a política integral"},
 {"icon": "scale", "title": "Programa de Compliance e Código de Conduta", "text": "Atuação de colaboradores e diretores, combate à corrupção, proibição de benefícios, contratações, doações, combate à prática criminosa e canal de denúncias.", "url": "/conformidade/compliance/", "cta": "Conhecer o programa"},
 {"icon": "cpu", "title": "Política de Segurança da Informação", "text": "Princípios, controles técnicos e administrativos, gestão de acessos, incidentes, continuidade e responsabilidades — sob o Comitê de Segurança e Qualidade.", "url": "/conformidade/seguranca-da-informacao/", "cta": "Ler a política"},
 {"icon": "leaf", "title": "Política ESG", "text": "Compromissos ambientais, sociais e de governança: meio ambiente, saúde e segurança, diversidade, comunidade e transparência.", "url": "/conformidade/esg/", "cta": "Ler a política"},
 {"icon": "brain", "title": "Política de Inteligência Artificial responsável", "text": "Princípios para desenvolvimento e uso de IA nos produtos Trix: supervisão humana, transparência, privacidade, segurança, não discriminação e governança.", "url": "/conformidade/inteligencia-artificial/", "cta": "Ler a política"},
 {"icon": "cookie", "title": "Política de Cookies e Glossário LGPD", "text": "Cookies e armazenamento local utilizados no portal, categorias, como gerenciar preferências; e glossário de termos da LGPD e dos sistemas Trix.", "url": "/conformidade/cookies/", "cta": "Cookies e glossário"},
]
HUB = {
 "slug": "conformidade", "order": 6, "short": "Conformidade",
 "title": "Central de Conformidade: LGPD, compliance, ESG e IA | Trix TI",
 "description": "Missão, valores, política integrada e políticas de privacidade, compliance, segurança, ESG e IA da Trix TI, com canais de denúncia e DPO.",
 "image": "images/02.jpg", "hero": "dark", "type": "about",
 "kicker": "Central de Conformidade", "h1": "Integridade, privacidade e segurança <strong>por princípio</strong>",
 "lead": "Afirmamos nosso compromisso com a qualidade e a segurança da informação. Como fornecedores de serviços e soluções de conectividade para operadoras de planos de saúde, estamos totalmente comprometidos com a proteção dos dados dos nossos clientes, parceiros e colaboradores — e já estamos adequados à LGPD, a Lei Geral de Proteção de Dados.",
 "actions": [("Ver políticas", "#politicas"), ("Canais de denúncia e LGPD", "#canais", "trix-btn--ghost")],
 "meta": ["DPO nomeado", "3 comitês permanentes", "Código de Conduta publicado", "Programa de adequação à LGPD desde 2020"],
 "body": "".join([
  sec(head("Propósito", "Missão, <strong>visão</strong> e valores", "Nossa conformidade nasce do que acreditamos. Estes são os compromissos que orientam cada decisão, produto e relacionamento da Trix.", True)
   + cards([{"icon": "rocket", "title": "Missão", "text": "Criar soluções inovadoras que agregam valor aos negócios dos nossos clientes, promovendo a escalabilidade, resiliência e resolutividade esperadas."}, {"icon": "eye", "title": "Visão", "text": "Ser reconhecida pela satisfação dos nossos clientes e pela qualidade dos produtos e serviços oferecidos, estabelecendo alianças que formam um relacionamento contínuo e próspero em todos os sentidos."}, {"icon": "heart", "title": "Valores", "text": "<strong>Ética</strong>, <strong>compromisso</strong> e <strong>competência</strong>, sustentados pelos princípios de conduta: honestidade, responsabilidade, respeito, organização e valorização."}], 3)),
  sec(head("Política integrada", "Política Integrada de <strong>Gestão, Qualidade, Segurança, Privacidade, Integridade e Sustentabilidade</strong>", "A Trix Tecnologia Inteligente, por meio de sua alta direção, declara apoio visível e inequívoco aos seus programas de conformidade e assume os seguintes compromissos:")
   + PROSE(checks([
     "<strong>Qualidade e satisfação:</strong> entregar produtos e serviços que atendam aos requisitos dos clientes, à legislação e às normas aplicáveis, medindo a satisfação e promovendo a melhoria contínua dos processos por meio do Escritório de Processos (MTRIX) e da metodologia PROTRIX.",
     "<strong>Proteção de dados pessoais:</strong> tratar dados pessoais — inclusive dados sensíveis de saúde — apenas para finalidades legítimas, específicas e informadas, com base legal adequada, pelo tempo necessário, com registro em logs de tratamento e respeito integral aos direitos dos titulares previstos na LGPD (Lei nº 13.709/2018).",
     "<strong>Segurança da informação:</strong> assegurar a confidencialidade, integridade, disponibilidade e autenticidade das informações sob nossa responsabilidade, com controles técnicos, administrativos e físicos proporcionais aos riscos, gestão de incidentes e continuidade de negócios.",
     "<strong>Integridade e anticorrupção:</strong> atuar com respeito às leis, em especial a Lei Anticorrupção (12.846/2013) e a Lei Antitruste (12.529/2011), com tolerância zero a fraudes, suborno, vantagens indevidas e conflitos de interesse, e com canal de denúncias acessível e protegido contra retaliação.",
     "<strong>Pessoas, saúde e segurança:</strong> proporcionar um ambiente de trabalho asseado, organizado e seguro, com respeito, diversidade, desenvolvimento e acesso dos colaboradores aos gestores e ao Compliance Officer.",
     "<strong>Meio ambiente e sociedade (ESG):</strong> conservar recursos naturais, reduzir impactos ambientais ao longo da cadeia de produção e priorizar doações e patrocínios em educação, cultura, esporte, tecnologia e projetos sociais, sempre com aprovação do compliance.",
     "<strong>Inteligência artificial responsável:</strong> desenvolver e usar IA com supervisão humana, transparência, explicabilidade, privacidade desde a concepção e prevenção de vieses — a decisão final é sempre do profissional.",
     "<strong>Governança e melhoria contínua:</strong> manter comitês permanentes de Compliance, Proteção de Dados e Segurança e Qualidade, analisar riscos periodicamente, promover treinamentos obrigatórios (Trix Academy), garantir controles contábeis fiéis e aplicar medidas disciplinares com pronta interrupção de irregularidades e tempestiva remediação de danos.",
   ]) + '<p class="trix-note"><strong>Versão 1.0 (minuta, setembro de 2026) — aprovação prevista:</strong> Diretoria Executiva e Comitês de Compliance, Proteção de Dados e Segurança e Qualidade. Esta política integrada consolida as políticas específicas listadas abaixo, que prevalecem em seus temas e devem ser lidas na íntegra.</p>'), "trix-section--sand"),
  sec(head("Políticas integrais", "Acesse as <strong>políticas completas</strong>", "", True) + cards(POLICY_LINKS, 3), "", "politicas"),
  sec(head("Governança", "Nossos <strong>comitês</strong>", "Três comitês permanentes, patrocinados pela alta direção, sustentam o programa de conformidade. Conheça a composição, as atribuições e os canais de acionamento de cada um.")
   + '<div class="trix-grid trix-grid--3">'
   + '<article class="trix-card trix-reveal"><img src="{{media:lgpd/img/comite-01.png}}" alt="Comitê de Compliance" style="width:72px" loading="lazy"><h3>Compliance</h3><p><strong>Compliance Officer:</strong> Sanclé Landim Albuquerque<br><strong>Patrocinadores:</strong> Marcos Soares de Sousa, Nádia Regina Siqueira Alves, Herbert Oliveira</p><details><summary style="cursor:pointer;font-weight:700">Atribuições</summary><ul style="font-size:.9rem;padding-left:1.1em"><li>Apoiar a alta direção e quaisquer outros conselhos, que demonstram apoio visível e inequívoco ao programa;</li><li>Declaração de aplicação dos códigos de conduta, padrões, procedimentos, regras e penalidades da Diretoria à equipe de operações;</li><li>Apoiar a ocorrência e obrigatoriedade de treinamentos periódicos;</li><li>Analisar periodicamente os riscos e realizar as adaptações necessárias;</li><li>Garantir, com a contabilidade, que os controles contábeis reflitam de forma correta e completa as demonstrações financeiras, prontamente disponíveis;</li><li>Definir procedimentos padrões para prevenir fraudes e atos ilícitos em qualquer aspecto institucional;</li><li>Garantir existência, disponibilidade e análise de resultados dos canais de denúncia;</li><li>Garantir medidas disciplinares, pronta interrupção de irregularidades e tempestiva remediação de danos.</li></ul></details><p><strong>Canais:</strong> (61) 3403-5353 · <a href="/canal-de-compliance/">formulário web</a> · ouvidoria@trixti.com.br</p></article>'
   + '<article class="trix-card trix-reveal"><img src="{{media:lgpd/img/comite-02.png}}" alt="Comitê de Proteção de Dados" style="width:72px" loading="lazy"><h3>Proteção de Dados</h3><p><strong>Encarregado (DPO):</strong> Sanclé Landim Albuquerque<br><strong>Patrocinadores:</strong> Marcos Soares de Sousa, Daniel Rodrigo da Silva, Herbert Oliveira</p><details><summary style="cursor:pointer;font-weight:700">Atribuições</summary><ul style="font-size:.9rem;padding-left:1.1em"><li>Apoiar a alta direção e conselhos no programa de proteção de dados;</li><li>Aplicação dos códigos de conduta, padrões, procedimentos, regras e penalidades;</li><li>Treinamentos periódicos obrigatórios;</li><li>Análise periódica de riscos e adaptações necessárias;</li><li>Controles contábeis corretos e disponíveis;</li><li>Procedimentos padrões para prevenir fraudes e atos ilícitos em relação à proteção de dados;</li><li>Existência, disponibilidade e análise dos canais de proteção de dados;</li><li>Medidas disciplinares, interrupção de irregularidades e remediação de danos;</li><li>Elaboração e atualização frequente do Relatório de Avaliação de Impacto da Privacidade (PIA), do Relatório de Avaliação de Impacto de Proteção de Dados (DPIA) e do Relatório de Impacto à Proteção de Dados Pessoais (RIPD).</li></ul></details><p><strong>Canais:</strong> (61) 3403-5353 · <a href="/canal-lgpd/">formulário web</a> · dpo@trixti.com.br</p></article>'
   + '<article class="trix-card trix-reveal"><img src="{{media:lgpd/img/comite-03.png}}" alt="Comitê de Segurança e Qualidade" style="width:72px" loading="lazy"><h3>Segurança e Qualidade</h3><p><strong>Security Officer:</strong> Sanclé Landim Albuquerque<br><strong>Patrocinadores:</strong> Marcos Soares de Sousa, Daniel Rodrigo da Silva, Nádia Regina</p><details><summary style="cursor:pointer;font-weight:700">Atribuições</summary><ul style="font-size:.9rem;padding-left:1.1em"><li>Apoiar a alta direção no programa de Segurança da Informação institucional e Qualidade;</li><li>Aplicação dos manuais, padrões, procedimentos, regras e penalidades da Diretoria à operação;</li><li>Treinamentos periódicos obrigatórios;</li><li>Análise periódica de riscos e adaptações documentais ou técnicas;</li><li>Garantir, com os prestadores-chave, que controles e registros reflitam todos os aspectos de segurança requeridos, para adequação a processos internos e cumprimento legal ou regulamentar;</li><li>Procedimentos padrões para prevenir fraudes e atos ilícitos em segurança da informação e qualidade;</li><li>Existência, disponibilidade e análise dos canais de segurança da informação;</li><li>Medidas disciplinares, interrupção de irregularidades e remediação de danos.</li></ul></details><p><strong>Canais:</strong> (61) 3403-5353 · <a href="/canal-de-compliance/?tipo=Seguran%C3%A7a%20da%20informa%C3%A7%C3%A3o">formulário web</a> · seguranca@trixti.com.br</p></article></div>', "trix-section--sand", "comites"),
  sec(head("Canais", "Fale com quem <strong>cuida da conformidade</strong>", "", True) + '<div class="trix-grid trix-grid--3"><div class="trix-card trix-card--yellow trix-reveal"><div class="trix-card__icon">{{icon:lock}}</div><h3>Canal LGPD</h3><p>Titulares de dados: acesso, correção, eliminação, portabilidade, revogação e incidentes. Atendido pelo DPO.</p><a class="trix-card__link" href="/canal-lgpd/">Exercer direitos</a></div><div class="trix-card trix-card--dark trix-reveal"><div class="trix-card__icon">{{icon:megaphone}}</div><h3>Canal de Compliance e Ouvidoria</h3><p>Denúncias (inclusive anônimas), dúvidas, sugestões e elogios. 0800 941 1190.</p><a class="trix-card__link" href="/canal-de-compliance/">Fazer um relato</a></div><div class="trix-card trix-reveal"><div class="trix-card__icon">{{icon:graduation}}</div><h3>Trix Academy</h3><p>Parceiros, fornecedores e clientes devem estar preparados para a LGPD. Acesse a plataforma de treinamentos.</p><a class="trix-card__link" href="http://academy.trixti.com.br/" target="_blank" rel="noopener">Acessar</a></div></div>', "", "canais"),
 ]),
}
LGPD = pol("lgpd",
 "Portal de Proteção de Dados (LGPD) | Trix TI",
 "Como a Trix trata dados de usuários, colaboradores e fornecedores, comitês de proteção de dados, DPO, treinamento e canais para titulares.",
 "Portal de Proteção de Dados", "Trix e LGPD: <strong>segurança e proteção de dados</strong>",
 "Afirmamos nosso compromisso com a qualidade e a segurança da informação. Como fornecedores de serviços e soluções de conectividade para operadoras de planos de saúde, estamos totalmente comprometidos com a proteção dos dados dos nossos clientes, parceiros e colaboradores. Já estamos adequados à LGPD — Lei Geral de Proteção de Dados.",
 "".join([
  sec(head("Como tratamos seus dados", "Responsabilidades de <strong>cada público</strong>")
   + cards([
     {"icon": "users", "title": "Usuários", "text": "Como usuário dos sistemas, serviços e soluções Trix Tecnologia, você opera com dados de titulares, inclusive os seus. Saiba que eles estão devidamente protegidos e que toda operação realizada é registrada nos logs de tratamento de dados. Suas responsabilidades estão declaradas nos termos de uso e políticas de privacidade e proteção de dados. Dados pessoais de titulares, inclusive dados sensíveis, são utilizados apenas para promoção do(s) serviço(s) relacionado(s) ao contrato a que estão vinculados.", "url": "/conformidade/politica-de-privacidade/", "cta": "Mais detalhes"},
     {"icon": "briefcase", "title": "Colaboradores", "text": "Como colaborador, você desenvolve tarefas para as quais foi contratado, assumindo as responsabilidades de OPERADOR de dados. Zelar e proteger os dados de outros titulares é sua obrigação, assim como usá-los apenas para tarefas relacionadas à sua função. Faça a sua parte começando pelo programa de treinamentos de Integração e LGPD, onde conhecerá o Código de Conduta Ética e as Políticas de Privacidade, Segurança e Proteção de Dados.", "url": "/conformidade/politica-de-privacidade/", "cta": "Mais detalhes"},
     {"icon": "handshake", "title": "Fornecedores e parceiros", "text": "Como fornecedor e/ou parceiro, você assume a responsabilidade de OPERADOR de dados. Para dar continuidade aos serviços contratados pela Trix Tecnologia, é obrigatório aceitar nossos termos e condições. Contratos vigentes receberam instruções para adequação contratual, aceite dos novos termos e participação no programa de capacitação. Para novos contratos, as atividades só são liberadas após o mapeamento do inventário de dados e aceite do Código de Conduta Ética e das Políticas de Privacidade, Segurança e Proteção de Dados.", "url": "/conformidade/politica-de-privacidade/", "cta": "Mais detalhes"},
   ], 3)),
  sec(head("Bases legais e princípios", "Como a LGPD é aplicada <strong>nos produtos Trix</strong>", "Nossos sistemas (SAW, Portal Operadora, Prontow, Aspect Face, Xield e demais) tratam dados pessoais — inclusive dados sensíveis de saúde e biométricos — em nome das operadoras, clínicas e empresas contratantes (controladoras). Aplicamos:")
   + PROSE(checks(["<strong>Finalidade, adequação e necessidade:</strong> apenas os dados indispensáveis ao serviço contratado.", "<strong>Bases legais — dados pessoais comuns (art. 7º):</strong> execução de contrato, cumprimento de obrigação legal ou regulatória (ANS, TISS), legítimo interesse e consentimento, quando cabível.", "<strong>Bases legais — dados sensíveis de saúde e biométricos (art. 11):</strong> cumprimento de obrigação legal ou regulatória, tutela da saúde em procedimento realizado por profissionais e serviços de saúde, garantia da prevenção à fraude e à segurança do titular (biometria) e consentimento específico e destacado, quando exigido — sempre sob as instruções da controladora.", "<strong>Transparência:</strong> políticas públicas, termos de uso apresentados no primeiro acesso e canais de atendimento ao titular.", "<strong>Segurança:</strong> criptografia em trânsito (SSL/TLS), controle de acesso por perfil, trilhas de auditoria, backups e esquemas redundantes.", "<strong>Prevenção e responsabilização:</strong> relatórios de impacto (PIA/DPIA/RIPD) elaborados e atualizados pelo Comitê de Proteção de Dados; contratos com operadores e fornecedores com cláusulas de proteção de dados.", "<strong>Transferência internacional:</strong> quando ocorrer, com as salvaguardas previstas na LGPD e nas Cláusulas Contratuais Padrão."])), "trix-section--sand"),
  sec(head("Comitês", "Nossos <strong>comitês</strong>") + '<div class="trix-grid trix-grid--3">'
   + '<div class="trix-card trix-reveal"><img src="{{media:lgpd/img/comite-01.png}}" alt="Ícone do Comitê de Compliance" style="width:64px" loading="lazy"><h3>Compliance</h3><p>Compliance Officer: Sanclé Landim Albuquerque. Patrocinadores: Marcos Soares de Sousa, Nádia Regina Siqueira Alves, Herbert Oliveira.</p><p><strong>Canais:</strong> (61) 3403-5353 · formulário web · ouvidoria@trixti.com.br</p><a class="trix-card__link" href="/conformidade/#comites">Atribuições completas</a></div>'
   + '<div class="trix-card trix-reveal"><img src="{{media:lgpd/img/comite-02.png}}" alt="Ícone do Comitê de Proteção de Dados" style="width:64px" loading="lazy"><h3>Proteção de Dados</h3><p>Data Protection Officer (DPO): Sanclé Landim Albuquerque. Patrocinadores: Marcos Soares de Sousa, Daniel Rodrigo da Silva, Herbert Oliveira.</p><p><strong>Canais:</strong> (61) 3403-5353 · formulário web · dpo@trixti.com.br</p><a class="trix-card__link" href="/canal-lgpd/">Falar com o DPO</a></div>'
   + '<div class="trix-card trix-reveal"><img src="{{media:lgpd/img/comite-03.png}}" alt="Ícone do Comitê de Segurança e Qualidade" style="width:64px" loading="lazy"><h3>Segurança e Qualidade</h3><p>Security Officer: Sanclé Landim Albuquerque. Patrocinadores: Marcos Soares de Sousa, Daniel Rodrigo da Silva, Nádia Regina.</p><p><strong>Canais:</strong> (61) 3403-5353 · formulário web · seguranca@trixti.com.br</p><a class="trix-card__link" href="/conformidade/seguranca-da-informacao/">Política de segurança</a></div></div>'),
  sec('<div class="trix-split"><div class="trix-reveal"><img src="{{media:lgpd/img/treinamento.png}}" alt="Trix Academy" style="max-width:120px" loading="lazy"><h2>Treinamento e <strong>capacitação</strong></h2><p>Parceiros, fornecedores e clientes devem estar preparados para a LGPD. Acesse nossa plataforma de treinamentos Trix Academy e participe dos programas.</p><a class="trix-btn trix-btn--primary" href="http://academy.trixti.com.br/" target="_blank" rel="noopener">Acessar a Trix Academy</a></div><div class="trix-reveal"><h2>Ouvidoria</h2><p>Críticas, elogios, denúncias e sugestões: entre em contato.</p><p style="font-size:1.6rem;font-weight:300"><a href="tel:+5508009411190">0800 941 1190</a></p><div class="trix-actions"><a class="trix-btn trix-btn--dark" href="/canal-lgpd/?tipo=Solicita%C3%A7%C3%A3o%20de%20documentos">Solicitação de informação ou documentos</a><a class="trix-btn trix-btn--ghost" href="/canal-de-compliance/">Ouvidoria</a><a class="trix-btn trix-btn--ghost" href="/canal-lgpd/">Proteção de dados</a></div><p class="trix-muted" style="margin-top:14px">falecom@trixti.com.br ou ouvidoria@trixti.com.br</p></div></div>', "trix-section--sand"),
 ]), short="Portal de Proteção de Dados", order=1,
 faq_items=[("A Trix está adequada à LGPD?", "A Trix mantém um programa contínuo de adequação à LGPD: Política de Privacidade publicada em 2020, Encarregado (DPO) nomeado, comitês permanentes responsáveis por promover os relatórios de impacto e programa de treinamento na Trix Academy."), ("Quem é o DPO da Trix?", "Sanclé Landim Albuquerque — dpo@trixti.com.br.")])
POLITICA = pol("politica-de-privacidade",
 "Política de Privacidade | Trix Tecnologia Inteligente",
 "Texto integral da Política de Privacidade da Trix TI (28/09/2020): coleta, uso, cookies, armazenamento, direitos dos titulares e contato do DPO.",
 "Política de Privacidade", "Política de <strong>Privacidade</strong>",
 "Quando o USUÁRIO aceita esta Política de Privacidade, confere sua livre e expressa concordância com os termos aqui estipulados. Este documento estabelece as regras para o tratamento de dados coletados dos USUÁRIOS, além do registro de suas atividades, de acordo com as leis aplicáveis. Texto integral, versão de 28 de setembro de 2020.",
 "".join([
  sec('<div class="trix-toc"><strong>Sumário</strong><ol><li><a href="#definicoes">Definições</a></li><li><a href="#coleta">Coleta de dados</a></li><li><a href="#uso">Uso de dados</a></li><li><a href="#armazenamento">Armazenamento de dados</a></li><li><a href="#gerais">Disposições gerais</a></li><li><a href="#lei">Lei aplicável e jurisdição</a></li><li><a href="#especificas">Condições específicas</a></li><li><a href="/conformidade/cookies/">Cookies</a></li></ol></div>'
      + PROSE(orig("politica").replace('<h2>Definições</h2>', '<h2 id="definicoes">Definições</h2>').replace('<h2>\nColeta de dados\n</h2>', '<h2 id="coleta">Coleta de dados</h2>').replace('<h2>\nUso de dados\n</h2>', '<h2 id="uso">Uso de dados</h2>').replace('<h2>\nArmazenamento de dados\n</h2>', '<h2 id="armazenamento">Armazenamento de dados</h2>').replace('<h2>Disposições Gerais</h2>', '<h2 id="gerais">Disposições Gerais</h2>').replace('<h2>Lei aplicável e jurisdição</h2>', '<h2 id="lei">Lei aplicável e jurisdição</h2>').replace('<h2>Condições específicas</h2>', '<h2 id="especificas">Condições específicas</h2>')
        + '<p class="trix-note"><strong>Encarregado de Proteção de Dados:</strong> Sanclé Landim Albuquerque · <strong>E-mail:</strong> <a href="mailto:dpo@trixti.com.br">dpo@trixti.com.br</a> · <strong>Versão desta Política:</strong> 28 de setembro de 2020. Para exercer seus direitos, utilize o <a href="/canal-lgpd/">Canal LGPD</a>.</p>'
        + '<h2 id="adendo">Adendo informativo do site (setembro de 2026)</h2><p>Este adendo complementa, sem alterar, a Política de 2020 quanto ao uso deste site e está sujeito a revisão jurídica:</p><ul><li><strong>Formulários do site</strong> (Contato, Canal LGPD e Canal de Compliance): os dados informados são usados apenas para responder à sua solicitação, com base na execução de diligências pré-contratuais, no cumprimento de obrigação legal (LGPD, art. 18) ou no legítimo interesse em apurar irregularidades; ficam armazenados no WordPress do site e são acessíveis à equipe responsável.</li><li><strong>Cookies</strong>: o site utiliza o painel de consentimento descrito na <a href="/conformidade/cookies/">Política de Cookies</a>; cookies não essenciais só são ativados com o seu opt-in, que pode ser revogado a qualquer momento.</li><li><strong>Direitos do titular</strong> (LGPD, art. 18): confirmação, acesso, correção, anonimização, bloqueio ou eliminação, portabilidade, informação sobre compartilhamento, revogação do consentimento e oposição — exercidos pelo <a href="/canal-lgpd/">Canal LGPD</a>, com resposta nos prazos do art. 19.</li><li><strong>Autoridade Nacional de Proteção de Dados (ANPD)</strong>: além de contatar a Trix, você pode peticionar à ANPD (gov.br/anpd).</li><li><strong>Transferência internacional</strong>: quando ocorrer, observará a Resolução CD/ANPD nº 19/2024 e as cláusulas-padrão aplicáveis.</li></ul>')),
 ]), short="Política de Privacidade", order=2)
COOKIES = pol("cookies",
 "Política de Cookies | Trix TI",
 "Categorias de cookies do site da Trix TI (necessários, funcionais, analíticos e marketing), armazenamento local e como gerenciar suas preferências.",
 "Política de Cookies", "Cookies e <strong>armazenamento local</strong>",
 "Cookies são pequenos arquivos enviados ao seu dispositivo para identificá-lo e coletar informações que nos ajudam a aprimorar os serviços. Você controla suas preferências a qualquer momento pelo painel de consentimento deste site (ícone de cookie no canto inferior esquerdo).",
 "".join([
  sec(head("Neste site", "Categorias utilizadas <strong>neste portal</strong>")
   + table(["Categoria", "Finalidade", "Exemplos", "Consentimento"], [["Estritamente necessários", "Funcionamento do site, segurança e registro das suas preferências de consentimento e acessibilidade.", "trix_cookie_consent, trix_a11y (armazenamento local), cookies de sessão do WordPress", "Sempre ativos"], ["Funcionais", "Recursos adicionais como mapa interativo do Google Maps, vídeos incorporados e tradução em Libras (VLibras).", "Cookies do Google Maps/YouTube quando carregados", "Opcional"], ["Analíticos", "Estatísticas anônimas de navegação para melhorar o site (Google Analytics 4 com anonimização de IP e Consent Mode v2).", "_ga, _ga_*", "Opcional"], ["Marketing", "Medição de campanhas e conteúdo relevante em outras plataformas.", "Cookies de redes sociais quando ativados", "Opcional"]])
   + '<p style="margin-top:16px"><button type="button" class="trix-btn trix-btn--primary" data-cookie="open">Gerenciar minhas preferências</button></p>'),
  sec(head("Registro histórico", "Cookies e armazenamento local <strong>do widget de chat</strong>", "Registro integral dos cookies e dados de armazenamento local utilizados pelo widget de bate-papo (JivoChat) no portal de proteção de dados, conforme documentado originalmente.") + PROSE(orig("cookies")), "trix-section--sand"),
  sec(head("Glossário", "Termos <strong>LGPD</strong>", "Consulte o glossário completo de termos da LGPD e dos sistemas Trix.", True) + '<div class="trix-actions" style="justify-content:center"><a class="trix-btn trix-btn--dark" href="/conformidade/glossario-lgpd/">Abrir o glossário</a><a class="trix-btn trix-btn--ghost" href="/conformidade/politica-de-privacidade/">Voltar à Política de Privacidade</a></div>'),
 ]), short="Cookies", order=6)
GLOSS = pol("glossario-lgpd",
 "Glossário LGPD e dos sistemas Trix | Trix TI",
 "Termos da LGPD e dos sistemas Trix: agentes de tratamento, anonimização, consentimento, controlador, operador, encarregado, dado sensível, SAW e telemedicina.",
 "Glossário", "Nosso <strong>glossário</strong>",
 "Definições utilizadas na Política de Privacidade, nos termos de uso e nos sistemas da Trix Tecnologia Inteligente, com base na Lei nº 13.709/2018 (LGPD) e nas normas da ANS.",
 sec(PROSE(orig("glossario"))), short="Glossário LGPD", order=7)
CODIGO_TEXT = """
<h2 id="atuacao">Atuação dos colaboradores e diretores</h2>
<p>A empresa atua em todo território nacional. Os nossos contratantes, fornecedores, diretores, gerentes e cada colaborador desta empresa devem estar cientes da conduta ilibada praticada pela empresa, tanto nas relações sociais, quanto nas comerciais. A empresa sempre irá atuar com respeito às leis e em conformidade com o programa de compliance*.</p>
<p>Desta forma, os envolvidos nas atividades executadas pela empresa devem evitar toda e qualquer violação legal, estando cientes que as atividades ilegais serão devidamente repudiadas, através de medidas disciplinares ou, em se tratando de terceiros/fornecedores, de rescisões contratuais com estabelecimento de multas.</p>
<p class="trix-note">* Compliance, em termos didáticos, significa estar absolutamente em linha com normas, controles internos e externos, além de todas as políticas e diretrizes estabelecidas para o negócio. É a atividade de assegurar que a empresa está cumprindo à risca todas as imposições dos órgãos de regulamentação, dentro de todos os padrões exigidos no seu segmento. E isso vale para as esferas trabalhista, fiscal, contábil, financeira, ambiental, jurídica, previdenciária, ética, etc.</p>
<p>Esta forma de atuar comporá uma cultura na empresa, a qual será respeitada por todos os envolvidos, correspondendo ao modelo padrão de conduta caso haja novos colaboradores. Todos os gestores deverão dar o exemplo para os demais componentes da empresa, através de sua conduta pessoal, desempenho, objetivos e liderança. O gestor, em todos os níveis, deverá ser acessível para discutir problemas pessoais e profissionais dos demais colaboradores. Ajudar os colaboradores de forma clara e precisa, sempre no intento de fomentar a cultura de transparência e conduta estritamente de acordo com a lei.</p>
<p>É importante frisar que o dever de orientação e supervisão dos gestores não afasta a responsabilidade pessoal do colaborador de agir conforme a lei, notadamente a Lei Antitruste (Lei nº 12.529, de 2011) e a Lei Anticorrupção (Lei nº 12.846, de 2013).</p>
<p>Cabe à Diretoria, com apoio da gerência, garantir o cumprimento integral da lei, supervisionando os colaboradores, justamente para evitar que condutas possivelmente evitáveis sejam consumadas. Estas responsabilidades são subdivididas com todos os Diretores, de áreas específicas, e diversos gerentes, conforme organograma da Empresa.</p>
<p>Os colaboradores, por sua vez, devem respeitar as orientações, acompanhar as palestras de atualização quanto às diretrizes da empresa e seguir o código de conduta. Além disso, devem tirar dúvidas e reportar qualquer acontecimento indesejado aos gestores, para fomentar a cultura da empresa e cumprir o seu dever de transparência.</p>
<p>Os princípios de conduta são aqueles capazes de fomentar e pôr em prática a cultura do compliance, sendo eles: <strong>HONESTIDADE; RESPONSABILIDADE; RESPEITO; ORGANIZAÇÃO e VALORIZAÇÃO</strong>.</p>
<p>Diante da aplicação destes princípios no interior da empresa, naturalmente as relações com os clientes se valem da mesma conduta. O relacionamento com os clientes deve ser honesto, sem gerar expectativas falsas. A confiabilidade, fidelidade e confidencialidade serão adotadas nesta relação, sempre para atender as necessidades dos clientes. Não serão toleradas condutas ilícitas, as quais serão reprimidas por nossos colaboradores.</p>
<h2 id="corrupcao">Combate à corrupção</h2>
<p>O combate à corrupção deve ser exercido por todos, os quais terão mecanismos de denunciar de forma anônima qualquer ato anormal, preferencialmente entrando em contato com o portal de denúncias da empresa ou e-mail <a href="mailto:ouvidoria@trixti.com.br">ouvidoria@trixti.com.br</a>, de forma ágil e transparente. Qualquer conduta indesejada será devidamente analisada e acarretará sanções aos envolvidos, caso a denúncia seja confirmada.</p>
<p>A principal preocupação é evitar que qualquer ato ilegal possa envolver as relações da empresa. Para as contratações o único item relevante deve ser o serviço prestado, o qual é de qualidade e com preço atraente e competitivo no mercado, além do diferencial do nosso atendimento e presteza.</p>
<p>Desta forma, é vedado a qualquer colaborador o oferecimento de vantagens para obter contratos ou fornecer produtos/serviços. Não será possível ofertar dinheiro, presentes ou tráfico de influência, com a intenção de obter vantagens.</p>
<p>Todas as ações dos colaboradores devem estar de acordo com a lei, não podendo ao menos aparentar uma ilegalidade ou indícios de má-fé. A simples aparência pode gerar danos à empresa e, por esta razão, também devem ser evitados, mesmo que legais.</p>
<p>Ressalta-se que os colaboradores deverão ter conduta ilibada, sem oferecer qualquer vantagem indevida ou imoral, em todas as transações efetivadas, com órgão público/privado, em qualquer ramo de atuação da empresa.</p>
<p>Assim, todos os envolvidos em contratações, negócios ou transações com esta empresa deverão respeitar princípios básicos. Os que merecem citação iniciam-se com o primordial <strong>PRINCÍPIO DA BOA-FÉ</strong>, ou seja, agir sempre de acordo com a lei e com condutas morais ilibadas.</p>
<p>O <strong>PRINCÍPIO DE TRANSPARÊNCIA</strong>, o qual consiste em informar aos terceiros da conduta ilibada da empresa e das proibições contidas neste código de conduta, além do dever de informar qualquer prática indesejada do terceiro aos seus gestores e canal de denúncia.</p>
<p>O <strong>PRINCÍPIO DA AVALIAÇÃO</strong>, o qual consiste na necessidade do colaborador avaliar a qualificação e reputação do futuro parceiro da empresa. Deverá sempre se preocupar com a imagem da empresa, certificando-se que a nova parceria não trará prejuízos futuros.</p>
<h2 id="beneficios">Proibição de aceitar benefícios</h2>
<p>Os colaboradores não podem oferecer e aceitar benefícios. A intenção de terceiros em dar presentes, tráfico de influência e troca de favores deve ser imediatamente recusada.</p>
<p>Além da recusa, o colaborador deve informar ao seu gestor a tentativa do terceiro em agir de forma imoral e em desacordo com a prática da empresa. Caso a conduta seja considerada atentatória ao programa, a equipe de Compliance será cientificada e poderá recusar-se a dar continuidade às negociações.</p>
<h2 id="contratacoes">Contratações públicas e privadas</h2>
<p>A participação em licitações públicas demandará uma atuação também de acordo com os princípios de negociações já elencados. A empresa deverá agir com boa-fé, transparência, avaliar o cliente contratante e vincular-se ao programa de compliance.</p>
<p>Além disso, os colaboradores envolvidos deverão estar atentos às leis e normas vinculativas do procedimento licitatório, como a Lei 8.666/93 ou qualquer outra que a suceda, para sempre agir de forma correta e com amparo legal.</p><p class="trix-note"><strong>Nota da publicação web:</strong> a Lei nº 8.666/1993 foi revogada em 30/12/2023; aplica-se atualmente a Lei nº 14.133/2021 (Nova Lei de Licitações e Contratos).</p>
<p>A mesma atuação será exigida nos contratos privados, e a empresa não admitirá hipóteses vedadas por este código de conduta. A avaliação da empresa privada levará em consideração se esta detém programa de compliance; caso não tenha, avaliar-se-á se sua conduta em negociações anteriores não diverge das determinadas neste Código.</p>
<h2 id="doacoes">Doações e patrocínios</h2>
<p>A empresa, para não gerar qualquer desconfiança ou mácula na sua imagem, evitará doações, mesmo que legais, para empresas com ou sem fins lucrativos. Doações e patrocínios, se necessários, serão destinados prioritariamente ao ramo da educação, cultura, esporte, tecnologia e projetos sociais. A preferência será dada aos projetos que possam agregar à imagem da empresa, contribuindo para o seu fim social e proliferação da sua imagem sustentável.</p>
<p>Todo e qualquer investimento desta natureza deverá ser submetido ao setor de compliance (COMPLIANCE OFFICER), o qual avaliará a vinculação da atividade ao programa. Esta medida trará transparência ao investimento.</p>
<p>Nenhuma doação pode ser entendida como troca de favor. Não são permitidas doações para obter vantagens imediatas ou futuras. Por esta razão, doações devem ser justificadas formalmente. Do mesmo modo, contratos de patrocínio deverão ser formalizados e serão admitidos após aprovação dos gestores e do setor de compliance. O patrocínio deverá ser dado em troca unicamente da exposição da marca TRIX.</p>
<h2 id="criminosa">Combate à prática criminosa</h2>
<p>A empresa não compactua com práticas criminosas. Como preconizado pelos princípios de conduta, age sempre com honestidade e respeito, justamente para se afastar de qualquer conduta ilegal.</p>
<p>Os colaboradores devem cumprir integralmente as leis aplicáveis e os mecanismos de combate à corrupção. Para tanto, os colaboradores devem manter registrados todos os ativos da empresa, arquivos contábeis, pagamentos, transações e contratos, sempre com o dever de transparência.</p>
<p>Do mesmo modo será proibido maquiar qualquer relação da empresa, ante o dever de transparência. Neste sentido, práticas como lavagem de dinheiro, simulações ou fontes ilegais estão vedadas e não podem ter qualquer relação, mesmo que indireta, com a empresa.</p>
<h2 id="saude">Saúde, segurança e meio ambiente</h2>
<p>A TRIX envida todos os esforços para conservar os recursos naturais, através da promoção de atividades capazes de preservar o meio ambiente. Do começo de sua cadeia de produção até o resultado final do produto, todos os colaboradores deverão contribuir com a cultura de consciência ambiental inserida na empresa.</p>
<p>Todos os colaboradores da empresa exercem as atividades em um local asseado, organizado e seguro. Estas medidas são obrigações da empresa, com o intento de atingir a satisfação de seus colaboradores e garantir a saúde e segurança no local de trabalho.</p>
<p>A preservação deste ambiente de trabalho depende do esforço de todos os colaboradores, os quais terão amplo acesso aos gestores para reclamações ou poderão utilizar-se do Compliance Officer, com a intenção de indicar novas medidas práticas que possam ser adotadas para melhorar o ambiente de trabalho.</p>
<h2 id="denuncias">Canal de denúncias</h2>
<p>Todos os colaboradores terão amplo acesso ao Compliance Officer, responsável por esta atividade, que estará sempre disponível. A sua função será de esclarecer dúvidas, receber sugestões, implementar novas práticas capazes de melhorar o programa e receber denúncias (canal <a href="mailto:ouvidoria@trixti.com.br">ouvidoria@trixti.com.br</a>).</p>
<p>Este guia serve para demonstrar que o(a) colaborador(a) não está sozinho(a) e poderá sempre, em uma situação desconfortável, buscar auxílio do seu Compliance Officer. Você receberá, além desta cartilha, comunicado escrito detalhando nome e telefones do Compliance Officer, como também o endereço do site da empresa, onde há um local para denúncias e dúvidas, que não estão aqui inscritos em razão de possíveis alterações de telefone e endereço ao longo do tempo.</p>
<p class="trix-note">Canais atuais: <a href="/canal-de-compliance/">Canal de Compliance (formulário web, com opção de anonimato)</a> · Ouvidoria <a href="tel:+5508009411190">0800 941 1190</a> · (61) 3403-5353 · ouvidoria@trixti.com.br. Compliance Officer: Sanclé Landim Albuquerque.</p>
"""
CODIGO = pol("codigo-de-conduta",
 "Código de Conduta da Empresa | Trix TI",
 "Código de Conduta da Trix TI: atuação de colaboradores, combate à corrupção, benefícios, contratações, doações, meio ambiente e denúncias.",
 "Código de Conduta da Empresa", "Código de <strong>Conduta</strong>",
 "Transcrição do documento “Código de Conduta da Empresa” (PDF publicado no Portal de Proteção de Dados), que orienta contratantes, fornecedores, diretores, gerentes e colaboradores sobre a conduta ilibada praticada pela Trix. Pequenas correções ortográficas foram feitas na transcrição; notas da publicação web aparecem destacadas.",
 sec('<div class="trix-toc"><strong>Índice</strong><ol><li><a href="#atuacao">Atuação dos colaboradores e diretores</a></li><li><a href="#corrupcao">Combate à corrupção</a></li><li><a href="#beneficios">Proibição de aceitar benefícios</a></li><li><a href="#contratacoes">Contratações públicas e privadas</a></li><li><a href="#doacoes">Doações e patrocínios</a></li><li><a href="#criminosa">Combate à prática criminosa</a></li><li><a href="#saude">Saúde, segurança e meio ambiente</a></li><li><a href="#denuncias">Canal de denúncias</a></li></ol></div>' + PROSE(CODIGO_TEXT)), short="Código de Conduta", order=4)
COMPLI = pol("compliance",
 "Programa de Compliance e integridade | Trix TI",
 "Pilares do programa de integridade da Trix TI: alta direção, riscos, Código de Conduta, treinamento, denúncias e terceiros (Lei 12.846/2013).",
 "Programa de Compliance", "Integridade que <strong>se pratica</strong>",
 "Compliance é estar absolutamente em linha com normas, controles internos e externos e com todas as políticas e diretrizes estabelecidas para o negócio — nas esferas trabalhista, fiscal, contábil, financeira, ambiental, jurídica, previdenciária e ética. Nosso programa é patrocinado pela alta direção e conduzido pelo Compliance Officer.",
 "".join([
  sec(head("Pilares", "Os pilares do <strong>Programa de Integridade</strong> da Trix", "Estruturado conforme os parâmetros da Lei Anticorrupção (Lei nº 12.846/2013) e do Decreto nº 11.129/2022:")
   + cards([{"icon": "award", "title": "1. Comprometimento da alta direção", "text": "A Diretoria declara apoio visível e inequívoco ao programa e é responsável por garantir o cumprimento integral da lei, com supervisão dos colaboradores."}, {"icon": "search", "title": "2. Avaliação de riscos", "text": "Análise periódica dos riscos de integridade, proteção de dados e segurança, com adaptações julgadas necessárias pelos comitês."}, {"icon": "book", "title": "3. Código de Conduta e políticas", "text": "Código de Conduta da Empresa, Política de Privacidade, Segurança da Informação, ESG e IA aplicáveis a colaboradores, diretores, fornecedores e parceiros."}, {"icon": "graduation", "title": "4. Treinamento e comunicação", "text": "Treinamentos periódicos obrigatórios (Trix Academy), palestras de atualização e cartilha do Código de Conduta para cada colaborador."}, {"icon": "megaphone", "title": "5. Canal de denúncias", "text": "Canal web com opção de anonimato, ouvidoria 0800 941 1190 e e-mail ouvidoria@trixti.com.br, com garantia de não retaliação e apuração pelo Comitê de Compliance."}, {"icon": "handshake", "title": "6. Due diligence de terceiros", "text": "Princípio da avaliação: qualificação e reputação de parceiros, existência de programa de compliance e conduta em negociações anteriores; cláusulas contratuais com multas e rescisão."}, {"icon": "chart", "title": "7. Controles contábeis e financeiros", "text": "Registros de ativos, arquivos contábeis, pagamentos, transações e contratos corretos, completos e prontamente disponíveis; vedação à lavagem de dinheiro e simulações."}, {"icon": "shield", "title": "8. Monitoramento e medidas disciplinares", "text": "Procedimentos padrões para prevenir fraudes e atos ilícitos, pronta interrupção de irregularidades, medidas disciplinares e tempestiva remediação de danos."}], 4)),
  sec(head("Regras essenciais", "O que <strong>não toleramos</strong>", "", True) + PROSE(checks(["Oferecer ou aceitar dinheiro, presentes, tráfico de influência ou troca de favores para obter contratos ou vantagens — em contratações públicas ou privadas.", "Qualquer ato que sequer aparente ilegalidade ou má-fé, ainda que legal.", "Doações e patrocínios sem justificativa formal e aprovação do Compliance Officer; patrocínio só em troca da exposição da marca Trix.", "Lavagem de dinheiro, simulações, fontes ilegais e registros contábeis maquiados.", "Retaliação a quem relata de boa-fé.", "Expectativas falsas nas relações com clientes: confiabilidade, fidelidade e confidencialidade são obrigatórias."]) + '<p class="trix-note">Leia o <a href="/conformidade/codigo-de-conduta/">Código de Conduta da Empresa</a> na íntegra. Dúvidas e relatos: <a href="/canal-de-compliance/">Canal de Compliance</a>.</p>'), "trix-section--sand"),
  sec(cta("Precisa relatar algo?", "Denúncias, dúvidas, sugestões e elogios são recebidos com confidencialidade pelo Compliance Officer. Você pode se identificar ou relatar anonimamente.", ("Acessar o Canal de Compliance", "/canal-de-compliance/"), ("Código de Conduta", "/conformidade/codigo-de-conduta/"))),
 ]), short="Compliance", order=3)
SEGURANCA = pol("seguranca-da-informacao",
 "Política de Segurança da Informação | Trix TI",
 "Princípios, acesso, criptografia, backup, desenvolvimento seguro e incidentes na Trix TI. Reporte incidentes a seguranca@trixti.com.br.",
 "Política de Segurança da Informação", "Segurança da <strong>Informação</strong>",
 "A informação é o bem mais precioso de qualquer empresa. A privacidade e a integridade das informações mantidas pelas organizações estão no topo da importância para a continuidade do negócio. Esta política estabelece as diretrizes que protegem as informações da Trix, de seus clientes, parceiros e colaboradores.",
 sec('<div class="trix-toc"><strong>Sumário</strong><ol><li><a href="#s1">Objetivo e escopo</a></li><li><a href="#s2">Princípios</a></li><li><a href="#s3">Diretrizes gerais</a></li><li><a href="#s4">Controle de acesso e identidades</a></li><li><a href="#s5">Proteção de dados e criptografia</a></li><li><a href="#s6">Desenvolvimento seguro e operações</a></li><li><a href="#s7">Gestão de incidentes</a></li><li><a href="#s8">Continuidade de negócios</a></li><li><a href="#s9">Fornecedores e terceiros</a></li><li><a href="#s10">Responsabilidades e sanções</a></li><li><a href="#s11">Governança e revisão</a></li></ol></div>'
   + PROSE(DRAFT_NOTE + """
<h2 id="s1">1. Objetivo e escopo</h2><p>Estabelecer princípios, diretrizes e responsabilidades para a proteção das informações e dos ativos de tecnologia da Trix Tecnologia Inteligente Ltda, aplicáveis a todos os colaboradores, diretores, estagiários, prestadores de serviço, fornecedores e parceiros que acessem ambientes, sistemas ou informações da Trix ou de seus clientes — incluindo os produtos SAW, Portal Operadora, Prontow, GEDAI, Integrador, Intranet, Aspect Face e Xield e os serviços de conectividade em saúde suplementar.</p>
<h2 id="s2">2. Princípios</h2><ul><li><strong>Confidencialidade:</strong> a informação é acessível apenas a quem tem autorização e necessidade de conhecê-la.</li><li><strong>Integridade:</strong> a informação é exata, completa e protegida contra alterações indevidas.</li><li><strong>Disponibilidade:</strong> a informação e os sistemas estão acessíveis quando necessários ao negócio e aos clientes.</li><li><strong>Autenticidade e não repúdio:</strong> origem e autoria das informações e transações são verificáveis (autenticação, trilhas de auditoria e assinatura digital ICP-Brasil quando aplicável).</li><li><strong>Legalidade:</strong> conformidade com a LGPD, normas da ANS (padrão TISS), Marco Civil da Internet e demais legislações e contratos.</li></ul>
<h2 id="s3">3. Diretrizes gerais</h2><p>As diretrizes desta seção e das seguintes descrevem o padrão de segurança que a Trix adota e evidencia em seus produtos e serviços; onde um controle ainda estiver em implantação, o Comitê de Segurança e Qualidade acompanha o plano de ação.</p><ul><li>As informações são classificadas em pública, interna, confidencial e restrita (incluindo dados pessoais sensíveis de saúde e biométricos), com controles proporcionais ao risco.</li><li>Todo acesso a sistemas é individual, autenticado e registrado; credenciais são pessoais e intransferíveis, e seu compartilhamento constitui violação desta política.</li><li>Estações de trabalho, dispositivos móveis e ambientes de nuvem seguem padrões de configuração segura, atualização de software, antimalware e bloqueio automático.</li><li>O uso de recursos de TI da Trix é destinado às atividades profissionais e pode ser monitorado nos limites da lei.</li><li>Informações confidenciais não devem ser transmitidas por canais não homologados nem armazenadas em serviços não autorizados.</li></ul>
<h2 id="s4">4. Controle de acesso e identidades</h2><ul><li>Concessão de acessos pelo princípio do menor privilégio e por perfil de função (médico, atendente, gestão, auditor, administrador etc.), com aprovação formal do gestor.</li><li>Revisão periódica de acessos e revogação imediata em desligamentos ou mudanças de função.</li><li>Senhas fortes, autenticação multifator para acessos administrativos e remotos, e bloqueio após tentativas inválidas.</li><li>Ambientes segregados (desenvolvimento, homologação e produção), com acesso a produção restrito e auditado.</li></ul>
<h2 id="s5">5. Proteção de dados e criptografia</h2><ul><li>Criptografia em trânsito (TLS/SSL) em todos os serviços web, APIs e integrações, e em repouso para dados sensíveis e backups.</li><li>Dados pessoais são tratados conforme a <a href="/conformidade/politica-de-privacidade/">Política de Privacidade</a>, com registro em logs de tratamento, minimização e anonimização quando possível.</li><li>Backups periódicos, testados e armazenados com redundância; esquemas redundantes para serviços críticos das operadoras.</li><li>Descarte seguro de mídias e documentos; mesa limpa e tela limpa.</li></ul>
<h2 id="s6">6. Desenvolvimento seguro e operações</h2><ul><li>Requisitos de segurança e privacidade desde a concepção (privacy by design) na metodologia PROTRIX; revisão de código, testes de segurança e gestão de vulnerabilidades.</li><li>Controle de versões, gestão de mudanças e trilhas de auditoria de quem fez cada alteração nos sistemas e nos dados.</li><li>Monitoramento contínuo de serviços, capacidade e eventos de segurança, com alertas aos responsáveis.</li><li>Uso de componentes e bibliotecas atualizados; homologação de fornecedores de nuvem (incluindo Oracle Cloud Infrastructure) e de serviços de terceiros.</li></ul>
<h2 id="s7">7. Gestão de incidentes</h2><ul><li>Todo colaborador ou terceiro deve reportar imediatamente incidentes ou suspeitas (vazamento, acesso indevido, malware, perda de dispositivo) ao canal <a href="mailto:seguranca@trixti.com.br">seguranca@trixti.com.br</a> ou pelo <a href="/canal-de-compliance/">formulário web</a>.</li><li>O Comitê de Segurança e Qualidade classifica, contém, erradica e registra o incidente, com lições aprendidas.</li><li>Incidentes com dados pessoais são avaliados com o Encarregado (DPO) e, quando exigido, comunicados aos controladores, titulares e à ANPD nos prazos legais.</li></ul>
<h2 id="s8">8. Continuidade de negócios</h2><p>Planos de continuidade e recuperação de desastres são mantidos para os serviços críticos, com objetivos de tempo e ponto de recuperação definidos, redundância de infraestrutura, testes periódicos e comunicação com os clientes.</p>
<h2 id="s9">9. Fornecedores e terceiros</h2><p>Fornecedores e parceiros assumem a responsabilidade de operadores de dados e devem aceitar os termos e condições da Trix, participar do programa de capacitação (Trix Academy), mapear o inventário de dados e cumprir esta política e o Código de Conduta. Contratos preveem cláusulas de confidencialidade, segurança, auditoria e sanções.</p>
<h2 id="s10">10. Responsabilidades e sanções</h2><ul><li><strong>Alta direção:</strong> patrocinar o programa e prover recursos.</li><li><strong>Comitê de Segurança e Qualidade / Security Officer:</strong> manter a política, analisar riscos, definir procedimentos, tratar incidentes e garantir treinamentos.</li><li><strong>Gestores:</strong> aplicar a política em suas áreas e aprovar acessos.</li><li><strong>Colaboradores e terceiros:</strong> cumprir a política, proteger credenciais e informações e reportar incidentes.</li></ul><p>O descumprimento sujeita o infrator a medidas disciplinares, rescisão contratual, multas e responsabilização civil e criminal, conforme o caso.</p>
<h2 id="s11">11. Governança e revisão</h2><p>Esta política deve ser aprovada pela Diretoria Executiva, mantida pelo Comitê de Segurança e Qualidade (Security Officer: Sanclé Landim Albuquerque; patrocinadores: Marcos Soares de Sousa, Daniel Rodrigo da Silva e Nádia Regina) e revisada anualmente ou sempre que mudanças relevantes ocorrerem. Documentos complementares: Política de Privacidade, Código de Conduta, Política de IA e normas internas de acesso, backup e incidentes.</p>
<p class="trix-note"><strong>Canal:</strong> seguranca@trixti.com.br · (61) 3403-5353 · <a href="/canal-de-compliance/">formulário web</a>.</p>""")), short="Segurança da Informação", order=5)
ESG = pol("esg",
 "Política ESG | Trix TI",
 "Compromissos ambientais, sociais e de governança da Trix TI: recursos naturais, digitalização, segurança, capacitação e transparência.",
 "Política ESG", "Ambiental, social e <strong>governança</strong>",
 "A Trix envida todos os esforços para conservar os recursos naturais, garantir um ambiente de trabalho seguro e saudável e atuar com integridade e transparência. Esta política consolida nossos compromissos ESG e como eles se conectam ao propósito de criar tecnologia que melhora a vida das pessoas.",
 "".join([
  sec(cards([
   {"icon": "leaf", "title": "Ambiental", "text": "<strong>Conservação de recursos naturais</strong> do começo da cadeia de produção ao produto final · <strong>Digitalização e desmaterialização</strong>: nossos produtos (GEDAI, Prontow, SAW) reduzem papel, deslocamentos e arquivos físicos nos clientes · <strong>Infraestrutura eficiente</strong>: nuvem e data centers com melhor eficiência energética, descarte responsável de equipamentos eletrônicos · <strong>Consciência ambiental</strong> difundida entre colaboradores."},
   {"icon": "users", "title": "Social", "text": "<strong>Saúde e segurança</strong>: local de trabalho asseado, organizado e seguro, com acesso amplo aos gestores e ao Compliance Officer · <strong>Respeito e diversidade</strong>: tolerância zero a assédio e discriminação · <strong>Capacitação</strong>: Trix Academy e treinamentos contínuos · <strong>Impacto na saúde</strong>: tecnologia que amplia o acesso e a qualidade do atendimento a beneficiários e pacientes · <strong>Comunidade</strong>: doações e patrocínios priorizando educação, cultura, esporte, tecnologia e projetos sociais."},
   {"icon": "scale", "title": "Governança", "text": "<strong>Comitês permanentes</strong> de Compliance, Proteção de Dados e Segurança e Qualidade · <strong>Código de Conduta</strong> e programa anticorrupção · <strong>LGPD</strong> com DPO nomeado e relatórios de impacto · <strong>Transparência</strong>: políticas públicas, dados institucionais abertos e canais de denúncia protegidos contra retaliação · <strong>Controles contábeis</strong> fiéis e disponíveis."},
  ], 3)),
  sec(head("Compromissos", "O que já está <strong>estabelecido</strong> e o que vem a seguir", "", True) + PROSE(table(["Eixo", "Compromisso (fonte: Código de Conduta e políticas publicadas)", "Próximo passo"], [["Ambiental", "Conservar os recursos naturais e promover a consciência ambiental do início da cadeia de produção ao produto final", "Definir indicadores (consumo, resíduos eletrônicos) e metas anuais"], ["Ambiental", "Reduzir papel e deslocamentos com soluções digitais (GED/ECM, prontuário eletrônico, atendimento remoto)", "Medir o volume digitalizado e os atendimentos remotos nos clientes"], ["Social", "Local de trabalho asseado, organizado e seguro; acesso amplo aos gestores e ao Compliance Officer", "Formalizar canais e pesquisa de clima"], ["Social", "Treinamento de integração, Código de Conduta e LGPD para colaboradores e parceiros (Trix Academy)", "Acompanhar conclusões e reciclagens"], ["Social", "Doações e patrocínios priorizando educação, cultura, esporte, tecnologia e projetos sociais, com aprovação do compliance", "Publicar critérios e registros"], ["Governança", "Comitês permanentes, Código de Conduta, canal de denúncias com não retaliação e controles contábeis fiéis", "Revisão anual das políticas com data e versão"]]) + DRAFT_NOTE + '<p class="trix-note">Sugestões e relatos: <a href="/canal-de-compliance/">Canal de Compliance</a>.</p>'), "trix-section--sand"),
 ]), short="ESG", order=8)
IA = pol("inteligencia-artificial",
 "Política de IA responsável | Trix TI",
 "Princípios de IA da Trix TI: supervisão humana, transparência, privacidade, segurança e equidade no Prontow, Aspect Face e Xield.",
 "Política de IA responsável", "Inteligência artificial <strong>com o humano no controle</strong>",
 "Usamos inteligência artificial para tornar o atendimento mais rápido, seguro e humano: agendamento conversacional, apoio ao diagnóstico, antifraude facial e automação de ambientes. Esta política define como desenvolvemos e operamos IA com ética, transparência e conformidade com a LGPD.",
 "".join([
  sec(head("Princípios", "Nossos <strong>princípios</strong> para IA")
   + cards([{"icon": "users", "title": "Supervisão humana", "text": "A IA apoia, não decide. No Prontow, a sugestão diagnóstica é uma ferramenta de apoio e a decisão é sempre do médico; no Aspect Face, analistas revisam os alertas de fraude e corrigem falsos positivos."}, {"icon": "eye", "title": "Transparência e explicabilidade", "text": "Usuários sabem quando interagem com um assistente de IA (ex.: WhatsApp) e quais dados foram considerados em uma sugestão. Documentamos finalidade, limitações e desempenho dos modelos."}, {"icon": "lock", "title": "Privacidade desde a concepção", "text": "Minimização de dados, bases legais adequadas, anonimização quando possível e retenção limitada. Dados de clientes não são utilizados para treinar modelos, salvo com base legal específica, previsão contratual com a controladora e informação aos titulares — dados sensíveis somente anonimizados."}, {"icon": "shield", "title": "Segurança e robustez", "text": "Testes contra manipulação (prova de vida/liveness, detecção de comportamentos anômalos), controle de acesso, monitoramento e planos de contingência com fallback humano."}, {"icon": "scale", "title": "Equidade e não discriminação", "text": "Diretriz: avaliar e monitorar vieses (idade, gênero, etnia) no reconhecimento facial e nos modelos clínicos, com desempenho acompanhado por segmento. Dados de crianças e adolescentes: tratamento apenas em seu melhor interesse e com base legal específica (LGPD, art. 14)."}, {"icon": "award", "title": "Responsabilidade e governança", "text": "Diretriz: cada solução com IA deve ter responsável nomeado, avaliação de impacto (inclusive à proteção de dados), registro de decisões e canal para contestação e revisão humana."}], 3)),
  sec(head("Aplicações", "Onde a IA está nos <strong>produtos Trix</strong>", "", True) + PROSE(table(["Produto", "Uso de IA", "Salvaguardas"], [["Prontow", "Assistente de agendamento por WhatsApp; sugestão de diagnóstico diferencial; preenchimento assistido do prontuário; estratificação de risco populacional", "Identificação do assistente; decisão sempre do profissional; trilha de auditoria; LGPD e sigilo médico"], ["Aspect Face", "Reconhecimento facial 1:1/1:N/N:N; prova de vida; classificação de fraudes", "Revisão humana dos alertas; consentimento e bases legais do art. 11; alternativa de autenticação sem biometria; regras específicas para menores"], ["Xield", "Reconhecimento facial para controle de acesso e automação", "Regras por perfil/horário; auditoria completa de eventos; cadastro por link seguro"], ["SAW / Portal Operadora", "Auditoria inteligente e autorização automática por regras parametrizadas (sem modelos de IA)", "Parametrização pela operadora; auditor humano nas decisões que exigem interação"]])), "trix-section--sand"),
  sec(head("Direitos e governança", "O que você pode <strong>esperar de nós</strong>") + PROSE(DRAFT_NOTE + checks(["Ser informado quando uma decisão for apoiada por IA e solicitar revisão humana.", "Exercer todos os direitos da LGPD pelo <a href='/canal-lgpd/'>Canal LGPD</a>, inclusive sobre dados biométricos.", "Contestar resultados (ex.: falha de reconhecimento facial) com atendimento humano e alternativa de autenticação.", "Governança pelo Comitê de Proteção de Dados e pelo Comitê de Segurança e Qualidade, com avaliação de riscos antes de cada lançamento e monitoramento contínuo em produção.", "Conformidade com a LGPD, com as normas da ANS e do CFM (telemedicina) e com as boas práticas internacionais de IA confiável; acompanhamento do marco legal brasileiro de IA."]) + '<p class="trix-note">Dúvidas ou relatos sobre uso de IA: <a href="mailto:dpo@trixti.com.br">dpo@trixti.com.br</a> · <a href="/canal-de-compliance/">Canal de Compliance</a>.</p>')),
 ]), short="Inteligência Artificial", order=9)
PAGES = [HUB, LGPD, POLITICA, COMPLI, CODIGO, SEGURANCA, COOKIES, GLOSS, ESG, IA]
