from .helpers import *
from nav import SITE as S
def captcha_block():
    return ('<div class="trix-captcha" role="group" aria-label="Verificação anti-spam"><label for="{id}">Verificação anti-spam <span class="req">*</span></label><p class="trix-captcha__q" id="{id}_q" aria-live="polite">Quanto é ?</p>'
            '<input type="number" inputmode="numeric" id="{id}" name="trix_captcha" required autocomplete="off" placeholder="Resposta" aria-describedby="{id}_q"><button type="button">Gerar outra pergunta</button></div>')
HP = '<div class="trix-hp" aria-hidden="true"><label for="website_url_{f}">Não preencha este campo</label><input type="text" id="website_url_{f}" name="website_url" tabindex="-1" autocomplete="off"></div>'
def privacy_notice(base):
    return '<p class="hint" style="font-size:.85rem">Os dados informados serão tratados pela Trix exclusivamente para receber, apurar e responder a esta manifestação, com base %s, pelo tempo necessário ao seu atendimento e à guarda legal. Consulte a <a href="/conformidade/politica-de-privacidade/" target="_blank">Política de Privacidade</a>.</p>' % base
def consent(f):
    return '<label class="trix-consent" for="consent_%s"><input type="checkbox" id="consent_%s" name="consent" required><span>Li e concordo com a <a href="/conformidade/politica-de-privacidade/" target="_blank">Política de Privacidade</a> e autorizo o tratamento dos dados informados para atendimento desta solicitação. <span class="req">*</span></span></label>' % (f, f)
def field(f, name, label, typ="text", req=True, ph="", extra=""):
    return '<div><label for="%s_%s">%s%s</label><input type="%s" id="%s_%s" name="%s" %s placeholder="%s" %s></div>' % (f, name, label, ' <span class="req">*</span>' if req else "", typ, f, name, name, "required" if req else "", ph, extra)
def select(f, name, label, options, req=True):
    return '<div><label for="%s_%s">%s%s</label><select id="%s_%s" name="%s" %s><option value="">Selecione…</option>%s</select></div>' % (f, name, label, ' <span class="req">*</span>' if req else "", f, name, name, "required" if req else "", "".join('<option value="%s">%s</option>' % (o, o) for o in options))
def textarea(f, name, label, ph="", req=True, rows=6):
    return '<div><label for="%s_%s">%s%s</label><textarea id="%s_%s" name="%s" rows="%d" %s placeholder="%s"></textarea></div>' % (f, name, label, ' <span class="req">*</span>' if req else "", f, name, name, rows, "required" if req else "", ph)
ASSUNTOS = ["Dúvida", "Sugestão", "Problema", "Financeiro", "Fábrica de Software", "Agenda Médica", "Treinamento e Capacitação", "Soluções e Automação", "Consultoria", "Escritório de Processos", "Conectividade em Saúde", "Suporte ao Prestador", "Prontow", "SAW", "Portal Operadora", "Aspect Face", "Xield", "GEDAI", "Integrador", "Intranet", "Oracle Partner", "Parcerias", "Imprensa", "Trabalhe conosco", "Outro"]
CONTATO_FORM = ('<form class="trix-form" data-form="contato" data-mail="%s" novalidate><h3>Envie sua mensagem</h3><p class="trix-muted">Campos com <span class="req">*</span> são obrigatórios. Retornamos o mais breve possível, em dias úteis.</p>' % S["email"]
  + '<div class="trix-form__row trix-form__row--2">' + field("c", "nome", "Nome", ph="Seu nome completo", extra='autocomplete="name"') + field("c", "email", "E-mail", "email", ph="voce@empresa.com.br", extra='autocomplete="email"') + '</div>'
  + '<div class="trix-form__row trix-form__row--2">' + field("c", "telefone", "(DDD) Telefone / WhatsApp", "tel", req=False, ph="(61) 99999-9999", extra='autocomplete="tel"') + field("c", "empresa", "Empresa / Operadora", req=False, ph="Nome da organização", extra='autocomplete="organization"') + '</div>'
  + '<div class="trix-form__row trix-form__row--2">' + select("c", "assunto", "Assunto", ASSUNTOS) + select("c", "perfil", "Você é", ["Operadora de saúde / cooperativa", "Prestador (clínica, consultório, laboratório, hospital)", "Empresa / órgão público", "Parceiro ou fornecedor", "Beneficiário / paciente", "Outro"], req=False) + '</div>'
  + textarea("c", "mensagem", "Mensagem", "Conte-nos sobre o seu desafio, produto de interesse ou dúvida.") + HP.format(f="c") + captcha_block().format(id="c_captcha") + consent("c")
  + '<div class="trix-form__msg" role="status" aria-live="polite"></div><div><button type="submit" class="trix-btn trix-btn--primary">Enviar mensagem</button></div></form>')
CONTATO = {
 "slug": "contato", "order": 7, "comments": True, "type": "contact", "short": "Contato",
 "title": "Contato: fale com a Trix TI em Brasília e São Paulo",
 "description": "Formulário, WhatsApp, e-mail e telefones da Trix TI: (61) 3403-5353 em Brasília e (11) 3014-3220 em São Paulo. Endereços, mapa e como chegar.",
 "image": "images/02.jpg", "hero": "dark",
 "kicker": "Contato", "h1": "Atendimento ágil também é uma <strong>marca da Trix</strong>",
 "lead": "Nós estamos prontos para atendê-lo. Escolha o canal de sua preferência: formulário, WhatsApp, e-mail ou telefone. Para solicitações de titulares de dados (LGPD) e denúncias, utilize os canais confidenciais específicos.",
 "actions": [("WhatsApp", S["social"]["whatsapp"]), ("Enviar mensagem", "#formulario", "trix-btn--ghost")],
 "meta": ["Retorno em dias úteis", "Suporte seg. a sex. 07h30–19h30", "Brasília e São Paulo"],
 "faq": [{"q": "Qual o horário de atendimento da Trix?", "a": "Comercial: segunda a sexta-feira, em horário comercial. Suporte aos prestadores: segunda a sexta, das 07h30 às 19h30, com serviço de call-back gratuito."}, {"q": "Como pedir uma demonstração do Prontow?", "a": "Pelo WhatsApp (61) 3246-1800 ou pelo formulário de contato selecionando o assunto Prontow."}, {"q": "Onde fica a Trix?", "a": "Matriz no Edifício Capital Financial Center, SIG Quadra 4, Lote 75, Bloco A, Sala 15, Brasília/DF, CEP 70610-440, e escritório na Alameda Santos, 1165, Cerqueira César, São Paulo/SP."}],
 "body": "".join([
  sec('<div class="trix-split" id="formulario"><div class="trix-reveal">' + CONTATO_FORM + '</div><div class="trix-reveal trix-contact-info">'
      + '<div class="trix-address"><strong>{{icon:map}} Brasília — Matriz</strong><span>Edifício Capital Financial Center<br>SIG Quadra 4, Lote 75, Bloco A, Sala 15<br>Zona Industrial (Guará) · Brasília – DF<br>CEP 70610-440</span><a href="tel:%s">Telefone: %s</a><a href="%s" target="_blank" rel="noopener">Abrir no Google Maps →</a></div>' % (S["phone_e164"], S["phone"], S["maps_url"])
      + '<div class="trix-address"><strong>{{icon:map}} São Paulo</strong><span>Alameda Santos, 1165<br>Cerqueira César · São Paulo – SP<br>CEP 01419-002</span><a href="tel:%s">Telefone: %s</a></div>' % (S["phone_sp_e164"], S["phone_sp"])
      + '<div class="trix-address"><strong>{{icon:mail}} Canais diretos</strong><a href="mailto:%s">%s</a><a href="%s" target="_blank" rel="noopener">WhatsApp comercial</a><a href="%s" target="_blank" rel="noopener">WhatsApp Prontow: %s</a><a href="tel:%s">Ouvidoria: %s</a><a href="mailto:%s">DPO: %s</a></div>' % (S["email"], S["email"], S["social"]["whatsapp"], S["social"]["whatsapp_prontow"], S["phone_prontow"], S["ouvidoria_e164"], S["ouvidoria"], S["email_dpo"], S["email_dpo"])
      + '</div></div>'),
  sec(head("Como chegar", "Venha nos <strong>visitar</strong>", "Estamos no Setor de Indústrias Gráficas (SIG), a poucos minutos do Eixo Monumental e do Parque da Cidade, com estacionamento no edifício. O mapa é carregado após sua autorização de cookies funcionais ou ao clicar no botão.", True)
   + '<div class="trix-grid trix-grid--2"><div class="trix-map trix-reveal" data-map="%s" data-title="Mapa: Trix em Brasília"><div class="trix-map__ph">{{icon:map}}<strong>Brasília — Edifício Capital Financial Center</strong><button type="button" class="trix-btn trix-btn--primary trix-btn--sm" data-map-load>Carregar mapa</button><small>Ao carregar, o Google Maps pode definir cookies.</small></div></div>' % S["maps_embed"]
   + '<div class="trix-map trix-reveal" data-map="%s" data-title="Mapa: Trix em São Paulo"><div class="trix-map__ph">{{icon:map}}<strong>São Paulo — Alameda Santos, 1165</strong><button type="button" class="trix-btn trix-btn--primary trix-btn--sm" data-map-load>Carregar mapa</button><small>Ao carregar, o Google Maps pode definir cookies.</small></div></div></div>' % S["maps_embed_sp"]
   + '<div class="trix-actions" style="justify-content:center"><a class="trix-btn trix-btn--dark" href="%s" target="_blank" rel="noopener">Rota no Google Maps</a><a class="trix-btn trix-btn--ghost" href="%s" target="_blank" rel="noopener">Rota no Waze</a></div>' % (S["maps_url"], S["waze_url"])
   + '<div style="height:32px"></div>' + cards([{"icon": "clock", "title": "Horários", "text": "Comercial: segunda a sexta, horário comercial. Suporte aos prestadores: segunda a sexta, das 07h30 às 19h30."}, {"icon": "phone", "title": "Call-back gratuito", "text": "Prestadores podem solicitar ligação de retorno sem custo: informe seu telefone e aguarde a ligação automática do ambiente Trix."}, {"icon": "graduation", "title": "Trix Academy", "text": "Treinamentos e capacitação online para clientes, parceiros e fornecedores em academy.trixti.com.br."}], 3), "trix-section--sand", "como-chegar"),
  sec(head("Canais específicos", "Precisa de um <strong>canal confidencial</strong>?", "", True) + '<div class="trix-grid trix-grid--2"><div class="trix-card trix-card--yellow trix-reveal"><div class="trix-card__icon">{{icon:lock}}</div><h3>Canal LGPD — titulares de dados</h3><p>Acesso, correção, eliminação, portabilidade, revogação de consentimento e informações sobre compartilhamento. Atendido pelo Encarregado (DPO).</p><a class="trix-card__link" href="/canal-lgpd/">Exercer meus direitos</a></div><div class="trix-card trix-card--dark trix-reveal"><div class="trix-card__icon">{{icon:megaphone}}</div><h3>Canal de Compliance e Ouvidoria</h3><p>Denúncias (com opção de anonimato), críticas, elogios e sugestões. Também pelo 0800 941 1190 e ouvidoria@trixti.com.br.</p><a class="trix-card__link" href="/canal-de-compliance/">Fazer um relato</a></div></div>'),
 ]),
}
LGPD_FORM = ('<form class="trix-form" data-form="lgpd" data-mail="%s" novalidate><h3>Solicitação do titular de dados</h3><p class="trix-muted">Campos com <span class="req">*</span> são obrigatórios. Para sua segurança, poderemos solicitar comprovação de identidade antes de atender à solicitação.</p>' % S["email_dpo"]
  + '<div class="trix-form__row trix-form__row--2">' + select("l", "tipo", "Tipo de solicitação", ["Confirmação da existência de tratamento", "Acesso aos meus dados", "Correção de dados incompletos, inexatos ou desatualizados", "Anonimização, bloqueio ou eliminação de dados", "Portabilidade dos dados", "Informação sobre compartilhamento com terceiros", "Revogação do consentimento", "Oposição ao tratamento / não receber marketing", "Relato de incidente de segurança com dados pessoais", "Dúvida sobre a Política de Privacidade", "Solicitação de documentos", "Outro"]) + select("l", "relacao", "Sua relação com a Trix", ["Beneficiário / paciente", "Usuário de sistema Trix (SAW, Prontow, Portal etc.)", "Colaborador ou ex-colaborador", "Cliente ou representante de cliente", "Fornecedor ou parceiro", "Visitante do site", "Outro"]) + '</div>'
  + '<div class="trix-form__row trix-form__row--2">' + field("l", "nome", "Nome completo", ph="Como consta em seus documentos", extra='autocomplete="name"') + field("l", "email", "E-mail para resposta", "email", ph="voce@exemplo.com", extra='autocomplete="email"') + '</div>'
  + '<div class="trix-form__row trix-form__row--2">' + field("l", "telefone", "Telefone", "tel", req=False, ph="(DDD) número", extra='autocomplete="tel"') + field("l", "cpf", "CPF (opcional, para localizar seus dados)", req=False, ph="000.000.000-00", extra='inputmode="numeric"') + '</div>'
  + field("l", "sistema", "Sistema, operadora ou serviço relacionado", req=False, ph="Ex.: SAW da operadora X, Prontow da clínica Y")
  + textarea("l", "descricao", "Descreva sua solicitação", "Informe o que deseja e, se possível, quais dados estão envolvidos.") + HP.format(f="l") + captcha_block().format(id="l_captcha") + privacy_notice("no cumprimento de obrigação legal (LGPD, art. 7º, II, e art. 18)")
  + '<div class="trix-form__msg" role="status" aria-live="polite"></div><div><button type="submit" class="trix-btn trix-btn--primary">Enviar ao DPO</button></div></form>')
CANAL_LGPD = {
 "slug": "canal-lgpd", "order": 8, "comments": True, "type": "contact", "short": "Canal LGPD",
 "title": "Canal LGPD: direitos do titular de dados | Trix TI",
 "description": "Solicite acesso, correção, eliminação ou portabilidade de dados, revogue consentimento ou relate incidentes. Atendido pelo DPO da Trix TI.",
 "image": "images/02.jpg", "hero": "dark",
 "kicker": "Canal LGPD", "h1": "Seus dados, <strong>seus direitos</strong>",
 "lead": "A Lei Geral de Proteção de Dados (Lei nº 13.709/2018) garante a você, titular, o direito de saber como seus dados são tratados e de decidir sobre eles. Este canal é atendido pelo nosso Encarregado de Proteção de Dados (DPO): confirmação e acesso são respondidos de forma imediata e simplificada ou, se você preferir, por declaração completa em até 15 dias (art. 19). Quando a Trix atua como operadora, encaminhamos sua solicitação à empresa controladora (operadora de saúde, clínica ou contratante).",
 "actions": [("Fazer solicitação", "#formulario"), ("Portal de Proteção de Dados", "/conformidade/lgpd/", "trix-btn--ghost")],
 "meta": ["Resposta simplificada imediata ou completa em até 15 dias", "Atendido pelo DPO", "Gratuito e confidencial"],
 "faq": [{"q": "Quais direitos posso exercer pelo Canal LGPD?", "a": "Confirmação de tratamento, acesso, correção, anonimização/bloqueio/eliminação, portabilidade, informação sobre compartilhamento, revogação do consentimento e oposição, conforme o art. 18 da LGPD."}, {"q": "Qual o prazo de resposta?", "a": "Confirmação de tratamento e acesso: de forma imediata, em formato simplificado, ou por declaração completa em até 15 dias (LGPD, art. 19). Demais pedidos: em prazo razoável, informado no protocolo. Podemos solicitar comprovação de identidade."}, {"q": "Quem é o Encarregado (DPO) da Trix?", "a": "Sanclé Landim Albuquerque, contato dpo@trixti.com.br."}],
 "body": "".join([
  sec(head("Direitos do titular", "O que você pode <strong>solicitar</strong>", "Conforme o art. 18 da LGPD, você pode exercer os seguintes direitos, gratuitamente, mediante requisição:")
   + cards([{"icon": "search", "title": "Confirmação e acesso", "text": "Saber se tratamos seus dados e obter uma cópia deles."}, {"icon": "check", "title": "Correção", "text": "Corrigir dados incompletos, inexatos ou desatualizados."}, {"icon": "lock", "title": "Anonimização, bloqueio ou eliminação", "text": "De dados desnecessários, excessivos ou tratados em desconformidade com a lei."}, {"icon": "plug", "title": "Portabilidade", "text": "Receber seus dados em formato estruturado para outro fornecedor de serviço."}, {"icon": "users", "title": "Informação sobre compartilhamento", "text": "Saber com quais entidades públicas e privadas compartilhamos seus dados."}, {"icon": "reset", "title": "Revogação do consentimento", "text": "Revogar o consentimento a qualquer momento e ser informado sobre as consequências da negativa."}], 3)),
  sec('<div class="trix-split" id="formulario"><div class="trix-reveal">' + LGPD_FORM + '</div><div class="trix-reveal trix-contact-info">'
      + '<div class="trix-address"><strong>{{icon:lock}} Encarregado de Proteção de Dados (DPO)</strong><span>Sanclé Landim Albuquerque</span><a href="mailto:%s">%s</a><a href="tel:%s">%s</a></div>' % (S["email_dpo"], S["email_dpo"], S["phone_e164"], S["phone"])
      + '<div class="trix-address"><strong>{{icon:shield}} Como tratamos sua solicitação</strong><span>1. Registro com número de protocolo<br>2. Validação de identidade (quando necessário)<br>3. Análise pelo Encarregado e pelo Comitê de Proteção de Dados (ou encaminhamento à controladora)<br>4. Resposta pelo e-mail informado: imediata e simplificada ou completa em até 15 dias</span></div>'
      + '<div class="trix-address"><strong>{{icon:alert}} Incidente de segurança?</strong><span>Se você suspeita de vazamento ou uso indevido de dados pessoais, relate imediatamente por este canal ou pelo e-mail seguranca@trixti.com.br.</span></div>'
      + '<div class="trix-address"><strong>{{icon:scale}} Autoridade Nacional (ANPD)</strong><span>Caso considere que a Trix violou a LGPD, você também pode apresentar reclamação à Autoridade Nacional de Proteção de Dados.</span><a href="https://www.gov.br/anpd/" target="_blank" rel="noopener">gov.br/anpd →</a></div></div></div>', "trix-section--sand"),
  sec(head("Perguntas frequentes", "Dúvidas <strong>comuns</strong>", "", True) + faq([("Preciso comprovar minha identidade?", "Para proteger seus dados contra acesso indevido, podemos solicitar documento ou outra forma de comprovação antes de atender pedidos de acesso, portabilidade ou eliminação."), ("Sou beneficiário de uma operadora que usa o SAW. A Trix é a controladora?", "Na maioria dos casos, a operadora é a controladora e a Trix atua como operadora de dados. Encaminharemos sua solicitação à controladora e acompanharemos a resposta, conforme previsto contratualmente."), ("Meus dados serão usados para outra finalidade?", "Não. Os dados desta solicitação são utilizados exclusivamente para atendê-la e para cumprimento de obrigações legais.")])),
 ]),
}
COMPLIANCE_FORM = ('<form class="trix-form" data-form="compliance" data-mail="%s" novalidate><h3>Registrar manifestação</h3><p class="trix-muted">Campos com <span class="req">*</span> são obrigatórios. Você pode optar por não se identificar. Nenhuma retaliação será tolerada contra quem relata de boa-fé.</p>' % S["email_ouvidoria"]
  + '<div class="trix-form__row trix-form__row--2">' + select("k", "tipo", "Tipo de manifestação", ["Denúncia", "Dúvida sobre o Código de Conduta", "Sugestão", "Reclamação", "Elogio", "Solicitação de informação", "Conflito de interesses", "Outro"]) + select("k", "tema", "Tema", ["Corrupção, suborno ou vantagem indevida", "Fraude ou irregularidade financeira", "Assédio, discriminação ou conduta inadequada", "Conflito de interesses", "Segurança da informação", "Proteção de dados / privacidade", "Saúde, segurança e meio ambiente", "Fornecedores e contratações", "Qualidade do atendimento", "Outro"], req=False) + '</div>'
  + '<fieldset><legend>Identificação</legend><div class="trix-radio"><label><input type="radio" name="identificacao" value="identificada" checked> Quero me identificar</label><label><input type="radio" name="identificacao" value="anonima"> Prefiro relato anônimo</label></div></fieldset>'
  + '<div class="trix-form__row trix-form__row--2">' + field("k", "nome", "Nome (opcional)", req=False, ph="Seu nome (se quiser)") + field("k", "email", "E-mail para retorno (opcional)", "email", req=False, ph="Para acompanhar a apuração") + '</div>'
  + select("k", "relacao", "Sua relação com a Trix", ["Colaborador", "Ex-colaborador", "Cliente", "Fornecedor ou parceiro", "Beneficiário / paciente", "Candidato", "Outro"], req=False)
  + textarea("k", "descricao", "Descreva o fato", "O que aconteceu, quando, onde, quem está envolvido e como tomou conhecimento. Quanto mais detalhes, melhor a apuração.", rows=8)
  + field("k", "evidencias", "Evidências (links para documentos, se houver)", req=False, ph="Links de arquivos, fotos ou vídeos")
  + HP.format(f="k") + captcha_block().format(id="k_captcha") + privacy_notice("no legítimo interesse da empresa em apurar irregularidades e no cumprimento de obrigações legais (Lei nº 12.846/2013)")
  + '<div class="trix-form__msg" role="status" aria-live="polite"></div><div><button type="submit" class="trix-btn trix-btn--primary">Enviar relato</button></div></form>')
CANAL_COMP = {
 "slug": "canal-de-compliance", "order": 9, "comments": True, "type": "contact", "short": "Canal de Compliance",
 "title": "Canal de Compliance e Ouvidoria | Trix TI",
 "description": "Denúncias (com opção de anonimato), dúvidas, sugestões e elogios sobre conduta, corrupção, fraude e assédio. Ouvidoria 0800 941 1190.",
 "image": "images/02.jpg", "hero": "dark",
 "kicker": "Canal de Compliance e Ouvidoria", "h1": "Fale com segurança. <strong>Nós ouvimos.</strong>",
 "lead": "Críticas, elogios, denúncias e sugestões fortalecem nossa cultura de integridade. Este canal é gerido pelo Compliance Officer com total confidencialidade, garantia de não retaliação e possibilidade de anonimato, conforme nosso Código de Conduta e as Leis Anticorrupção (12.846/2013) e Antitruste (12.529/2011).",
 "actions": [("Fazer um relato", "#formulario"), ("Ligar 0800 941 1190", "tel:+5508009411190", "trix-btn--ghost")],
 "meta": ["Opção de relato anônimo", "Não retaliação", "Apuração pelo Comitê de Compliance"],
 "faq": [{"q": "Posso denunciar sem me identificar?", "a": "Sim. Selecione “Prefiro relato anônimo”: nome, e-mail e telefone não são enviados. Dados técnicos de conexão podem ser registrados pela plataforma. Você receberá um protocolo para acompanhamento."}, {"q": "O que acontece após a denúncia?", "a": "O relato é registrado, classificado e apurado pelo Comitê de Compliance, com medidas disciplinares, interrupção de irregularidades e remediação de danos quando confirmado."}, {"q": "Quais outros canais existem?", "a": "Telefone (61) 3403-5353, Ouvidoria 0800 941 1190 e e-mail ouvidoria@trixti.com.br."}],
 "body": "".join([
  sec(head("Compromisso", "O que você pode <strong>relatar</strong>", "O combate à corrupção deve ser exercido por todos, com mecanismos para denunciar, de forma anônima, qualquer ato anormal. Qualquer conduta indesejada será devidamente analisada e acarretará sanções aos envolvidos, caso a denúncia seja confirmada.")
   + cards([{"icon": "scale", "title": "Corrupção e vantagens indevidas", "text": "Oferta ou aceitação de dinheiro, presentes, tráfico de influência ou troca de favores em contratações públicas ou privadas."}, {"icon": "chart", "title": "Fraude e irregularidades", "text": "Lavagem de dinheiro, simulações, registros contábeis maquiados ou fontes ilegais."}, {"icon": "users", "title": "Conduta e relações de trabalho", "text": "Assédio, discriminação, desrespeito aos princípios de honestidade, responsabilidade, respeito, organização e valorização."}, {"icon": "lock", "title": "Dados e segurança", "text": "Uso indevido de informações, violações de privacidade ou de segurança da informação."}, {"icon": "leaf", "title": "Saúde, segurança e meio ambiente", "text": "Condições inadequadas de trabalho ou práticas que agridam o meio ambiente."}, {"icon": "megaphone", "title": "Elogios e sugestões", "text": "Reconheça boas práticas e proponha melhorias para o programa de compliance e para o ambiente de trabalho."}], 3)),
  sec('<div class="trix-split" id="formulario"><div class="trix-reveal">' + COMPLIANCE_FORM + '</div><div class="trix-reveal trix-contact-info">'
      + '<div class="trix-address"><strong>{{icon:phone}} Ouvidoria</strong><a href="tel:%s">%s</a><a href="tel:%s">%s</a><a href="mailto:%s">%s</a></div>' % (S["ouvidoria_e164"], S["ouvidoria"], S["phone_e164"], S["phone"], S["email_ouvidoria"], S["email_ouvidoria"])
      + '<div class="trix-address"><strong>{{icon:scale}} Compliance Officer</strong><span>Sanclé Landim Albuquerque<br>Comitê de Compliance: Marcos Soares de Sousa, Nádia Regina Siqueira Alves e Herbert Oliveira (patrocinadores)</span></div>'
      + '<div class="trix-address"><strong>{{icon:shield}} Garantias</strong><ul class="trix-check"><li>Confidencialidade: acesso restrito ao Compliance Officer e ao comitê</li><li>Opção de não se identificar (dados técnicos de conexão, como o endereço IP, podem ser registrados pela plataforma)</li><li>Não retaliação a relatos de boa-fé</li><li>Apuração imparcial e resposta com protocolo</li></ul></div>'
      + '<div class="trix-address"><strong>{{icon:book}} Referências</strong><a href="/conformidade/codigo-de-conduta/">Código de Conduta da Empresa</a><a href="/conformidade/compliance/">Programa de Compliance</a></div></div></div>', "trix-section--sand"),
  sec(head("Perguntas frequentes", "Dúvidas <strong>comuns</strong>", "", True) + faq([("Posso denunciar sem me identificar?", "Sim. Selecione “Prefiro relato anônimo”: nome, e-mail e telefone não são enviados. Você receberá um protocolo para acompanhar."), ("O que acontece após a denúncia?", "O relato é registrado, classificado e apurado pelo Comitê de Compliance, com medidas disciplinares, pronta interrupção de irregularidades e tempestiva remediação de danos quando confirmado."), ("Fornecedores também devem seguir o Código?", "Sim. Contratantes, fornecedores, diretores, gerentes e colaboradores devem estar cientes da conduta ilibada praticada pela empresa; terceiros podem sofrer rescisão contratual com multas.")])),
 ]),
}
PAGES = [CONTATO, CANAL_LGPD, CANAL_COMP]
