from .helpers import *
def prod(slug, title, desc, kicker, h1, lead, body, name, category="BusinessApplication", meta=None, image=None, faq_items=None, order=10, actions=None, three=None, hero_img=None):
    p = {"slug": slug, "parent": "produtos", "order": order, "title": title, "description": desc, "type": "product", "productName": name, "category": category, "hero": "dark", "short": name.split(" - ")[0],
         "kicker": kicker, "h1": h1, "lead": lead, "actions": actions or [("Solicitar demonstração", "/contato/?assunto=" + name), ("Todos os produtos", "/produtos/", "trix-btn--ghost")], "body": body}
    if meta: p["meta"] = meta
    if image: p["image"] = image
    if three: p["three"] = three
    if hero_img: p["hero_img"] = hero_img[0]; p["hero_img_alt"] = hero_img[1]
    if faq_items: p["faq"] = [{"q": q, "a": a} for q, a in faq_items]
    return p
ARQ = lambda tec, arq, com, db=None: arch(([("Tecnologia", tec), ("Arquitetura", arq)] + ([("Banco de dados", db)] if db else []) + [("Comercialização", com)]))
HUB = {
 "slug": "produtos", "order": 3, "short": "Produtos",
 "title": "Produtos | Prontow, SAW, Portal Operadora, Aspect Face, Xield, GEDAI, Integrador e Intranet",
 "description": "Produtos da Trix TI: Prontow (clínicas com IA), SAW e Portal Operadora (operadoras de saúde), Aspect Face (reconhecimento facial antifraude), Xield (controle de acesso e automação), GEDAI (GED/ECM), Integrador e Intranet premiada.",
 "image": "images/monitor.png", "hero": "dark", "three": "cubes",
 "kicker": "Produtos", "h1": "Produtos que <strong>entregam resultados</strong>",
 "lead": "Nós transformamos a nossa paixão por tecnologia em produtos que agregam valor e entregam resultados. Nossos produtos facilitam a vida de milhares de pessoas Brasil afora — em operadoras de saúde, clínicas, hospitais, laboratórios, empresas e condomínios.",
 "actions": [("Solicitar demonstração", "/contato/")],
 "body": "".join([
  sec(cards([
     {"icon": "stethoscope", "title": "Prontow", "badge": "IA + WhatsApp", "text": "Sistema de gestão para clínicas, consultórios e laboratórios: agenda, prontuário eletrônico, financeiro, TISS, telemedicina, painel de senhas, app do paciente e IA.", "url": "/produtos/prontow/"},
     {"icon": "monitor", "title": "SAW — Sistema de Atendimento Web", "text": "Integra todos os envolvidos no atendimento a beneficiários: auditoria médica, intercâmbio PTU, elegibilidade, TISS e faturamento eletrônico.", "url": "/produtos/saw/"},
     {"icon": "globe", "title": "Portal Operadora", "text": "Solução criada para atender às necessidades das cooperativas e operadoras, com interface única para atendentes, prestadores, contratantes e beneficiários.", "url": "/produtos/portal-operadora/"},
     {"icon": "face", "title": "Aspect Face", "badge": "Antifraude", "text": "API de reconhecimento facial com prova de vida, identificação 1:1/1:N/N:N, gerenciador web, dashboards e a única com serviço antifraude por IA.", "url": "/produtos/aspect-face/"},
     {"icon": "lock", "title": "Xield", "badge": "Novo", "text": "Segurança e automação inteligente com reconhecimento facial: controle de acesso, mapa de presença, automação de ambientes e IoT.", "url": "/produtos/xield/"},
     {"icon": "file", "title": "GEDAI", "text": "Gerenciador Eletrônico de Documentos e Arquivo Inteligente: GED/ECM, workflow, OCR/ICR, indexação, versionamento e bureau de digitalização.", "url": "/produtos/gedai/"},
     {"icon": "plug", "title": "Integrador", "text": "Integração de sistemas e bases de dados heterogêneas com comunicação em tempo real, em qualquer tecnologia e independente do provedor.", "url": "/produtos/integrador/"},
     {"icon": "intranet", "title": "Intranet Trix", "badge": "Premiada", "text": "Ferramenta web de administração, comunicação e relacionamento interno, bicampeã do Prêmio Unimed de Comunicação.", "url": "/produtos/intranet/"},
   ], 4)),
  sec(head("Comercialização", "Modelos <strong>flexíveis</strong>", "Nossos produtos podem ser contratados por direito de acesso (licenciamento/SaaS) ou por aquisição da solução, com implantação, treinamento e suporte incluídos.", True)
   + cards([{"icon": "cloud", "title": "Direito de acesso (SaaS)", "text": "Assinatura na nuvem, sem instalação, com atualizações contínuas e suporte."}, {"icon": "database", "title": "Aquisição da solução", "text": "Licença perpétua com implantação on-premises ou em nuvem própria, integração e customizações sob medida."}, {"icon": "gear", "title": "Customizações", "text": "Adaptações às regras de negócio da sua operadora, clínica ou empresa, com a fábrica de software Trix."}], 3), "trix-section--sand"),
  contact_band(),
 ]),
}
PRONTOW = prod("prontow",
 "Prontow — Software com IA para Clínicas, Consultórios e Laboratórios | Trix",
 "Software de gestão para clínicas, consultórios e laboratórios: prontuário eletrônico, agenda, agendamento por WhatsApp com IA, telemedicina, financeiro, TISS/ANS, painel de senhas, app do paciente e sugestão diagnóstica por IA. Solicite uma demonstração.",
 "Prontow · Novo: WhatsApp com IA", "Gestão completa para clínicas, <strong>com inteligência artificial</strong>",
 "O PRONTOW é o sistema de gestão para clínicas, consultórios e laboratórios da Trix TI. Em um só lugar e na nuvem, ele reúne agenda, prontuário eletrônico, financeiro, faturamento TISS, atendimento por WhatsApp com IA e apoio ao diagnóstico por inteligência artificial — conduzindo o paciente do agendamento à cobrança, em fluxos conectados.",
 "".join([
  sec(feature("Agenda", "<p>A agenda do estabelecimento: a recepção marca consultas, retornos e exames e acompanha o status de cada marcação em tempo real.</p>" + checks(["Calendário por dia, semana ou mês, por profissional", "Consultas, retornos e exames com status em tempo real", "Filtros por agenda, tipo e forma de cobrança (particular/convênio)", "Busca rápida de paciente e marcação em segundos"]), "{{media:images/prontow/agenda.png}}", "Agenda do Prontow", kicker="Módulo")
   + '<div style="height:48px"></div>'
   + feature("Agendamento por WhatsApp com IA", "<p>Um assistente inteligente atende o paciente no próprio WhatsApp da clínica e resolve o agendamento de ponta a ponta — marca, remarca e cancela consultas e exames, 24 horas por dia, em conversa natural, sem ocupar a recepção.</p>" + checks(["Marcação, remarcação e cancelamento a qualquer hora, em linguagem natural", "Identifica o paciente e cadastra quem é novo automaticamente", "Exames pelo WhatsApp: entende o pedido (ex.: “quero um ultrassom da barriga”) e informa o preparo", "Envia link para o paciente adicionar a consulta ao calendário do celular", "Recebe fotos e PDFs (pedido, exames, carteirinha) como anexo do agendamento", "Multiclínica, com controle por agenda — você decide onde o agente atende", "Confirmação de agenda por WhatsApp com um toque, inclusive no ato da marcação: menos faltas e menos trabalho na recepção"]), "{{media:images/prontow/prontow_logo.png}}", "Prontow", rev=True, kicker="Novo · WhatsApp", plain=True)),
  sec(feature("Atendimento e prontuário eletrônico", "<p>Acompanha o paciente da chegada à finalização, com filas em tempo real e o prontuário eletrônico no centro do fluxo.</p>" + checks(["Filas em tempo real: aguardando, em atendimento e aguardando autorização", "Prontuário com seções e campos configuráveis por especialidade", "Prescrições, atestados, laudos, documentos, anexos e encaminhamentos", "Autorizações de convênio e pagamentos no mesmo atendimento"]), "{{media:images/prontow/filas.png}}", "Filas de atendimento em tempo real", kicker="Módulo")
   + '<div style="height:48px"></div>'
   + '<div class="trix-split trix-reveal"><div><span class="trix-tag">{{icon:brain}} Inteligência artificial</span><h3>Sugestão diagnóstica por IA</h3><p>Apoio à decisão clínica direto no prontuário: a inteligência artificial analisa o histórico clínico, as prescrições e os pedidos de exames anteriores do paciente e sugere um diagnóstico diferencial ao profissional — além de ajudar a preencher campos do prontuário com a opção “Sugerir com IA”.</p>' + checks(["Sugestão de diagnóstico diferencial a partir do contexto do atendimento", "Preenchimento assistido de campos do prontuário", "Considera histórico, prescrições, pedidos e anexos do paciente", "A decisão é sempre do médico — a IA é uma ferramenta de apoio"]) + '</div><div>'
   + cards([{"icon": "layers", "title": "Mais recursos clínicos", "text": "<strong>Painel de senhas</strong> em TV, por guichê e em tempo real, com vídeos institucionais · <strong>Exames, laudos e resultados</strong> com ciclo de status e resultado online · <strong>Prescrição digital</strong> com integração Memed · <strong>Assinatura digital</strong> ICP-Brasil (A1/A3, BirdID/Valid) com validação por QR Code/token · <strong>Atestados e encaminhamentos</strong> a partir de modelos · <strong>Templates</strong> reaproveitáveis de atestados, documentos, laudos e prescrições."}], 1, tilt=False) + '</div></div>', "trix-section--sand"),
  sec(feature("Financeiro", "<p>Controle completo do dinheiro do estabelecimento, do lançamento ao fluxo de caixa.</p>" + checks(["Contas a receber e a pagar, com baixa e parcelamento", "Transferências entre contas, categorias e centros de custo", "Fluxo de caixa com saldo e projeções", "Emissão de notas fiscais (NFS-e / NF-e)"]), "{{media:images/prontow/fluxo-caixa.png}}", "Fluxo de caixa no Prontow", kicker="Módulo")
   + '<div style="height:48px"></div>'
   + feature("TISS e faturamento (padrão ANS)", "<p>Troca de informações com os convênios no padrão da ANS, da guia ao faturamento em lotes.</p>" + checks(["Guias de Consulta e SP/SADT no padrão TISS", "Acompanhamento de autorizações e status das guias", "Verificação de elegibilidade dos pacientes em lote junto aos convênios", "Faturamento em lotes para envio aos convênios", "Versões de XML conforme o padrão da ANS"]), "{{media:images/prontow/tiss-painel.png}}", "Painel TISS do Prontow", rev=True, kicker="Módulo")),
  sec(head("Gestão e administração", "Controle total, <strong>100% na nuvem</strong>", "", True)
   + cards([
     {"icon": "building", "title": "Multiunidade e multiprofissional", "text": "Várias clínicas e equipes na mesma conta, com cadastros de pacientes, profissionais, convênios, procedimentos, locais e guichês."},
     {"icon": "users", "title": "Controle de acesso por perfil", "text": "Médico, atendente e gestão com acessos distintos, e trilha de auditoria de quem fez cada alteração — segurança e conformidade com a LGPD."},
     {"icon": "chart", "title": "Relatórios e estoque", "text": "Produtividade, atendimentos, convênios, pagamentos, repasses e mais; controle de itens e fornecedores. Acesse de qualquer lugar, sem instalação."},
   ], 3)
   + '<div style="height:40px"></div>'
   + '<div class="trix-split trix-reveal"><div><span class="trix-tag">{{icon:activity}} Novo · Operadoras de saúde</span><h3>Gestão de saúde populacional e visão de cuidado</h3><p>Um painel para operadoras e gestores de saúde acompanharem toda a população de beneficiários — transformando os dados da rede em ação sobre quem mais precisa de cuidado, sempre com respeito à LGPD.</p>' + checks(["Estratificação de risco dos beneficiários em níveis, do saudável ao alto risco", "Busca ativa: listas de quem precisa de acompanhamento para a equipe agir", "Análise epidemiológica: distribuição por idade e sexo, condições crônicas, principais grupos de doenças e multimorbidade", "Linhas de cuidado para condições como hipertensão e diabetes", "Gestão de risco por empresa/contrato nos planos empresariais", "Indicadores populacionais como apoio à atenção primária e às decisões de saúde"]) + '</div><div>'
   + cards([{"icon": "smartphone", "title": "App do paciente", "text": "O Prontow vai além da clínica: o paciente acompanha tudo pelo celular, integrado ao mesmo sistema da recepção e do consultório. Agendar consultas e retornos, acompanhar atendimentos e histórico, ver clínicas, profissionais e procedimentos, documentos e comprovantes em PDF, lembretes por notificação, cadastro e login seguros. <em>Aplicativo para iOS e Android — disponível em breve nas lojas.</em>"}], 1, tilt=False)
   + '<div class="trix-store" style="margin-top:14px"><img src="{{media:images/prontow/appstore.png}}" alt="Disponível na App Store" loading="lazy"><img src="{{media:images/prontow/gplay.png}}" alt="Disponível no Google Play" loading="lazy"></div></div></div>', "trix-section--sand"),
  sec(cta("Solicite uma demonstração", "Fale com a Trix TI e veja o PRONTOW em uma demonstração sem compromisso — por WhatsApp (61) 3246-1800 ou pelo formulário de contato.", ("WhatsApp (61) 3246-1800", "https://wa.me/556132461800?text=Ol%C3%A1!%20Quero%20uma%20demonstra%C3%A7%C3%A3o%20do%20prontow."), ("Formulário de contato", "/contato/?assunto=Prontow"))),
  sec(faq([("O Prontow precisa de instalação?", "Não. É 100% na nuvem: acesse de qualquer lugar, por navegador, sem instalação."), ("O Prontow atende laboratórios?", "Sim. Pedidos médicos, laudos com ciclo de status e resultados online para o paciente consultar pela web, além de faturamento TISS."), ("A IA substitui o médico?", "Não. A sugestão diagnóstica e o preenchimento assistido são ferramentas de apoio; a decisão é sempre do profissional de saúde."), ("Como funciona a assinatura digital?", "Documentos assinados com certificado ICP-Brasil (A1/A3, BirdID/Valid) e validação por QR Code/token.")]), "trix-section--sand"),
  contact_band(),
 ]), "Prontow", "MedicalApplication", meta=["Agenda, prontuário e financeiro", "WhatsApp com IA 24h", "TISS/ANS e telemedicina", "100% na nuvem"], image="images/prontow/agenda.png", order=1,
 actions=[("Solicitar demonstração", "https://wa.me/556132461800?text=Ol%C3%A1!%20Quero%20uma%20demonstra%C3%A7%C3%A3o%20do%20prontow."), ("Ver módulos", "#conteudo", "trix-btn--ghost")],
 faq_items=[("O Prontow precisa de instalação?", "Não. É 100% na nuvem, acessível por navegador."), ("O Prontow atende laboratórios?", "Sim, com pedidos, laudos, resultados online e TISS."), ("A IA substitui o médico?", "Não. É uma ferramenta de apoio; a decisão é sempre do profissional.")],
 hero_img=("{{media:images/prontow/prontow_logo.png}}", "Prontow"))
SAW_BODY = lambda name: "".join([
  sec(head("Auditoria", "Avançados recursos de <strong>auditoria médica</strong>", "O %s também é uma poderosa ferramenta de auditoria médica: pela internet, auditores e atendentes têm, de maneira coesa, as informações necessárias para a tomada de decisão em processos de atendimento que exigem interação humana." % name)
   + '<div class="trix-split"><div class="trix-reveal"><p>Com integração personalizada, alto desempenho e precisão, as informações são formatadas e apresentadas de acordo com as necessidades do usuário, com a garantia de fidelidade promovida pela integração em tempo real com a base de dados da operadora. Auditores podem trabalhar de casa, do hospital ou do consultório sem sofrer com a falta de informações.</p><p>Histórico de utilizações, restrições contratuais, cadastro do beneficiário, informações financeiras, visualização de laudos, históricos de conversas e de solicitações são algumas das informações disponíveis em tempo de auditoria. A <strong>auditoria inteligente</strong> uniformiza o conhecimento dos auditores da operadora e antecipa a auditoria ao solicitante, reduzindo o tempo de atendimento. Todo o processo ocorre em meio digital, integrando os envolvidos.</p></div><div class="trix-reveal">' + cards([{"icon": "star", "title": "Novidades da última versão", "text": "Auditoria de contas hospitalares (auditoria técnica) · Autorização e absenteísmo por SMS · Auditoria inteligente · Guia modelo."}], 1, tilt=False) + '</div></div>'),
  sec(head("Intercâmbio", "Intercâmbio <strong>online e offline</strong>", "O %s é certificado na versão 3.5 do PTU (Protocolo de Transações da Operadora): está apto a realizar transações de intercâmbio em nível nacional com todas as operadoras já certificadas." % name)
   + checks(["Operadoras que utilizam o %s requisitam ou respondem solicitações de intercâmbio para todo o Brasil sem contratar links de comunicação ou infraestrutura adicional — tudo é resolvido no sistema, sem onerar a estrutura da operadora" % name, "Para operadoras não certificadas, é possível configurar todas as regras de intercâmbio para autorização automática mediante solicitação do cooperado/prestador", "Mesmo para beneficiários de operadoras não aptas ao padrão PTU, autorizações automáticas conforme as regras de intercâmbio ou a particularidade de cada operadora", "O ranking de intercâmbio, que classifica as operadoras pelos serviços prestados em intercâmbio, avalia 9 itens diretamente influenciados pelo uso do %s" % name]), "trix-section--sand"),
  sec(head("Integração e segurança", "Integração de alto nível <strong>com a base da operadora</strong>")
   + '<div class="trix-grid trix-grid--2">' + cards([
     {"icon": "plug", "title": "Integração personalizada", "text": "Os mais altos padrões de integração de sistemas para que, de maneira independente da tecnologia e/ou banco de dados da operadora, a integração seja facilmente implementada. Com o Integrador próprio, a comunicação com a base de dados é um fator diferencial. A integração pode ocorrer pela internet e a operadora acompanha as ações e monitora os logs das transações."},
     {"icon": "shield", "title": "Elegibilidade e segurança", "text": "As informações são capturadas em tempo real na base da operadora: um atendimento só é possível se o beneficiário for localizado. Após a digitação do código, as verificações são realizadas e, em poucos segundos, as informações são apresentadas ao usuário. Segurança com esquemas redundantes, SSL, controle de transações, autenticação, backups e proteções administrativas, técnicas e físicas."},
   ], 2)[len('<div class="trix-grid trix-grid--2">'):]),
  sec(head("TISS", "Implementação de toda a solução <strong>para o TISS</strong>")
   + cards([
     {"icon": "network", "title": "Padrão de comunicação", "text": "Como o sistema funciona pela internet, o padrão de troca de mensagens da ANS não é utilizado neste contexto: as informações TISS são apresentadas e armazenadas no formato determinado. Também disponibilizamos WebService para prestadores com sistema apto a transações XML no padrão TISS."},
     {"icon": "file", "title": "Padrão de conteúdo e estrutura", "text": "Todas as entradas de dados são similares ao padrão visual e físico definido pelo TISS, facilitando a adaptação dos usuários habituados às guias em papel. Os dados são validados na entrada conforme os domínios e regras do padrão e da operadora."},
     {"icon": "lock", "title": "Padrão de segurança", "text": "Esquemas redundantes, SSL (Secure Sockets Layer), controle de transações, autenticação de usuários, backups e proteções administrativas, técnicas e físicas."},
     {"icon": "chart", "title": "Faturamento eletrônico", "text": "O módulo de faturamento eletrônico atende às necessidades de prestadores/cooperados — inclusive os que não possuem sistema apto a gerar a cobrança no padrão definido pela ANS."},
   ], 4), "trix-section--sand"),
  sec(head("Arquitetura", "Ficha <strong>técnica</strong>") + ARQ("Java", "MVC", "Direito de acesso · Aquisição da solução")),
  contact_band(),
 ])
SAW = prod("saw",
 "SAW — Sistema de Atendimento Web para operadoras de saúde | Auditoria, intercâmbio PTU e TISS",
 "O SAW integra todos os envolvidos no atendimento a beneficiários de planos de saúde: auditoria médica inteligente, intercâmbio certificado PTU 3.5, elegibilidade em tempo real, padrão TISS, faturamento eletrônico e integração com a base da operadora. Para cooperativas de todos os portes.",
 "SAW · Sistema de Atendimento Web", "Todos os envolvidos no atendimento, <strong>em uma única interface</strong>",
 "O SAW é uma ferramenta que integra todos os envolvidos no processo de atendimento a beneficiários de plano de saúde da operadora. De maneira eficiente, com uma única interface comum a todos e por meio da mobilidade da internet, possibilita a escalabilidade do atendimento com qualidade, garantindo a satisfação de atendentes, analistas de contas, cooperados/prestadores, empresas contratantes e, principalmente, beneficiários. Criado para atender às necessidades das operadoras de forma exclusiva, abstraindo conceitos, regras e processos, o SAW atende a realidade de cooperativas de todos os portes.",
 SAW_BODY("SAW"), "SAW - Sistema de Atendimento Web", "HealthApplication", meta=["Certificado PTU 3.5", "Auditoria inteligente", "TISS e faturamento eletrônico", "+35 operadoras"], image="images/30.png", order=2,
 faq_items=[("O SAW exige infraestrutura na operadora?", "Não para o intercâmbio: tudo é resolvido no SAW, sem links dedicados. A integração com a base da operadora ocorre pela internet com o Integrador Trix."), ("O SAW atende ao padrão TISS?", "Sim. Interfaces no padrão TISS, validação de dados, WebService para transações XML e faturamento eletrônico.")],
 hero_img=("{{media:images/30.png}}", "SAW - Sistema de Atendimento Web"))
PORTAL = prod("portal-operadora",
 "Portal Operadora | Atendimento integrado para cooperativas e operadoras de saúde",
 "O Portal Operadora da Trix TI integra atendentes, analistas de contas, cooperados/prestadores, empresas contratantes e beneficiários em uma única interface web, com auditoria médica, intercâmbio PTU, TISS, elegibilidade e faturamento eletrônico. Solução criada para as necessidades das cooperativas.",
 "Portal Operadora", "A solução criada para atender às <strong>necessidades das cooperativas</strong>",
 "O Portal Operadora é uma ferramenta que integra todos os envolvidos no processo de atendimento a beneficiários de plano de saúde. De maneira eficiente, com uma única interface comum a todos e por meio da mobilidade da internet, possibilita a escalabilidade do atendimento com qualidade — para cooperativas de todos os portes.",
 SAW_BODY("Portal Operadora"), "Portal Operadora", "HealthApplication", meta=["Interface única para todos os perfis", "Auditoria e intercâmbio", "TISS e faturamento eletrônico"], image="images/img_port_opera.png", order=3, hero_img=("{{media:images/img_port_opera.png}}", "Portal Operadora"))
ASPECT = prod("aspect-face",
 "Aspect Face — API de reconhecimento facial com antifraude e prova de vida | Trix",
 "Aspect Face: API de reconhecimento facial da Trix TI com serviço antifraude por IA, identificação 1:1, 1:N e N:N, garantia de prova de vida (liveness), integração fácil via Swagger, gerenciador web, dashboards, baixo custo e sem limite de idade.",
 "Aspect Face · Biometria facial", "A única API de reconhecimento facial <strong>com serviço antifraude</strong>",
 "O Aspect Face é uma API de reconhecimento facial baseada no princípio de que cada pessoa tem um padrão característico facial que, com análise profunda de imagem, permite identificar o indivíduo. Integre em minutos e ofereça uma jornada personalizada, segura e sem fraudes aos seus clientes.",
 "".join([
  sec(cards([
     {"icon": "shield", "title": "Única com IA e serviço antifraude", "text": "Identifica fraudes durante a captura/cadastro da face. A IA detecta “maus comportamentos” e os classifica como potenciais fraudes; nossos analistas corrigem falsos positivos, formando uma base de fraudes técnicas 99% confirmadas e ensinando a IA a trabalhar cada vez melhor."},
     {"icon": "users", "title": "Identificador 1:1, 1:N e N:N", "text": "Identifique seu cliente pela face a partir de milhares já cadastradas e forneça uma jornada personalizada e exclusiva de tratamento e relacionamento."},
     {"icon": "eye", "title": "Garantia de prova de vida (liveness)", "text": "Garante que a face capturada seja sempre de uma pessoa real (viva), presente no local de captura. Recurso essencial contra fraudes em cadastros e autenticações."},
     {"icon": "code", "title": "Fácil integração (Swagger)", "text": "API desenvolvida seguindo padrões internacionais de desenvolvimento, interoperabilidade e escalabilidade. Documentação Swagger para integrar rapidamente com a sua aplicação."},
     {"icon": "monitor", "title": "Gerenciador web de acessos e fraudes", "text": "Acesso para gerenciamento das capturas realizadas, relatórios e dashboards, além da visualização das fraudes relatadas pela IA."},
     {"icon": "chart", "title": "Dashboards de visualização", "text": "Relatórios que detalham o consumo por aplicação, segmentado em TAGs dinâmicas por funcionalidade. Painéis analytics com dados consolidados para decisões e gestão proativa do uso/aderência."},
   ], 3) + '<p class="trix-center" style="margin-top:28px">' + pills(["Baixo custo", "Sem limite de idade", "Padrões internacionais", "Escalável"]) + '</p>'),
  sec(feature("Antifraude com inteligência artificial", "<p>O recurso antifraude possibilita a identificação de fraudes durante o processo de captura/cadastro da face, com base de fraudes técnicas confirmadas e aprendizado contínuo.</p>", "{{media:images/img_antifraude.jpg}}", "Antifraude com IA", kicker="Diferencial")
   + '<div style="height:40px"></div>' + feature("Prova de vida e identificação", "<p>Liveness garante pessoa real e presente; identificação 1:1, 1:N e N:N entrega experiência personalizada em milhares de faces cadastradas.</p>", "{{media:images/img_prova_vida.jpg}}", "Prova de vida (liveness)", rev=True, kicker="Segurança")
   + '<div style="height:40px"></div>' + feature("Identificador 1:1, 1:N e N:N", "<p>Forneça uma nova experiência para seu cliente: identifique-o pela face a partir de milhares já cadastradas e ofereça uma jornada personalizada e exclusiva de tratamento e relacionamento.</p>", "{{media:images/img_identificador.jpg}}", "Identificação facial 1:1, 1:N e N:N", kicker="Identificação")
   + '<div style="height:40px"></div>' + feature("Fácil integração via Swagger", "<p>A API Aspect Face foi desenvolvida seguindo padrões internacionais de desenvolvimento, interoperabilidade e escalabilidade. Acesse <a href=\"https://aspectface.com/\" target=\"_blank\" rel=\"noopener\">www.aspectface.com</a> e veja como é fácil integrar com a sua aplicação.</p><p><img src=\"{{media:images/logo_swagger.png}}\" alt=\"Swagger\" style=\"max-height:48px\" loading=\"lazy\"></p>", "{{media:images/img_swagger.jpg}}", "Documentação Swagger", rev=True, kicker="Integração")
   + '<div style="height:40px"></div>' + feature("Gerenciador web e dashboards", "<p>Capturas, relatórios, fraudes relatadas pela IA e painéis analytics por TAGs dinâmicas em um só lugar. Relatórios detalham o consumo da biometria facial por aplicação, para decisões e gestão proativa do uso/aderência da solução.</p>", "{{media:images/img_gerenciador_web.jpg}}", "Gerenciador web", kicker="Gestão")
   + '<div style="height:40px"></div>' + feature("Dashboards de visualização", "<p>Painéis analytics com dados consolidados, segmentados em TAGs dinâmicas atribuídas em cada funcionalidade, para facilitar decisões e a gestão do uso da solução.</p>", "{{media:images/img_dashboard.jpg}}", "Dashboards de visualização", rev=True, kicker="Analytics"), "trix-section--sand"),
  sec(cta("Experimente o Aspect Face", "Acesse www.aspectface.com, conheça a documentação Swagger e veja como é fácil integrar com a sua aplicação.", ("Acessar aspectface.com", "https://aspectface.com/"), ("Falar com um consultor", "/contato/?assunto=Aspect%20Face"))),
  contact_band(),
 ]), "Aspect Face", "SecurityApplication", meta=["Antifraude por IA", "Prova de vida (liveness)", "1:1, 1:N e N:N", "Integração via Swagger"], image="images/img_face.jpg", order=4,
 actions=[("Experimentar em aspectface.com", "https://aspectface.com/"), ("Solicitar proposta", "/contato/?assunto=Aspect%20Face", "trix-btn--ghost")],
 faq_items=[("O que é prova de vida (liveness)?", "É a garantia de que a face capturada pertence a uma pessoa real e presente no momento da captura, evitando fraudes com fotos ou vídeos."), ("Como integrar o Aspect Face?", "Pela API REST documentada em Swagger, seguindo padrões internacionais de interoperabilidade e escalabilidade.")],
 hero_img=("{{media:images/logo_aspect_face.png}}", "Aspect Face"))
XIELD = prod("xield",
 "Xield — Segurança e automação inteligente com reconhecimento facial | Trix",
 "Xield: controle de acesso com biometria facial, mapa de presença em tempo real, automação inteligente de ambientes e integração com RTSP, Matter, Zigbee, MQTT e Home Assistant. 100% web, em nuvem ou on-premises, para hospitais, clínicas, empresas, escolas e condomínios.",
 "Xield · Novo", "Segurança e automação inteligente <strong>com reconhecimento facial</strong>",
 "Transforme o controle de acessos e a automação do seu espaço com o Xield. Seja na nuvem ou localmente (on-premises), o Xield oferece uma solução completa e inteligente para segurança, automação e gestão de ambientes — tudo via navegador, sem instalação de software adicional.",
 "".join([
  sec(feature("Plataforma 100% web, flexível e escalável", checks(["Operação via browser, com interface intuitiva", "Implantação em nuvem (SaaS) ou em infraestrutura local (on-premises)", "Gestão centralizada de múltiplas unidades ou ambientes"]), "{{media:images/xieldimg/xield_01.png}}", "Xield: plataforma web", kicker="🧠 Plataforma")
   + '<div style="height:40px"></div>' + feature("Controle de acesso inteligente com biometria facial", checks(["Identificação precisa por reconhecimento facial em tempo real", "Permite ou nega acesso a ambientes com base em perfil, horários e permissões", "Abertura automática de portas e portões sem toque — apenas com o rosto"]), "{{media:images/xieldimg/xield_02.png}}", "Xield: controle de acesso", rev=True, kicker="🔐 Acesso")
   + '<div style="height:40px"></div>' + feature("Mapa de presença e monitoramento em tempo real", checks(["Visualize quem está presente, onde está e desde quando", "Ideal para empresas, hospitais, escolas, clínicas e condomínios", "Visualização dinâmica por mapa, lista ou cronograma"]), "{{media:images/xieldimg/xield_03.png}}", "Xield: mapa de presença", kicker="🗺 Presença")),
  sec(feature("Automação inteligente de ambientes", checks(["Acendimento automático de luzes, climatização e dispositivos ao reconhecer o usuário", "Rotinas por perfil: colaborador, visitante, prestador de serviço", "Integração com sensores de presença, fechaduras eletrônicas e atuadores"]), "{{media:images/xieldimg/xield_04.png}}", "Xield: automação", kicker="💡 Automação")
   + '<div style="height:40px"></div>' + feature("Integração com equipamentos e protocolos de mercado", checks(["Compatível com RTSP (câmeras), Matter (IoT) e Zigbee (automação)", "Comunicação nativa com Home Assistant para automações personalizadas", "Integra com câmeras, fechaduras, sensores, campainhas e dispositivos smart", "Suporte ao protocolo MQTT para publicação de eventos em tempo real"]), "{{media:images/xieldimg/xield_05.png}}", "Xield: integrações", rev=True, kicker="🔗 Integração")
   + '<div style="height:40px"></div>' + feature("Outros recursos exclusivos", checks(["Controle de acesso por cômodo com regras configuráveis", "Cadastro facial remoto via link seguro para visitantes ou colaboradores", "Registro de eventos com auditoria completa e alertas em tempo real", "Dashboards personalizados com relatórios de presença, horários e acessos"]), "{{media:images/xieldimg/xield_06.png}}", "Xield: recursos", kicker="🧩 Recursos"), "trix-section--sand"),
  sec(head("Casos de uso", "Onde o Xield <strong>faz a diferença</strong>", "", True)
   + cards([{"icon": "stethoscope", "title": "Hospitais e clínicas", "text": "Restrição de acesso a áreas críticas com automação."}, {"icon": "home", "title": "Residências e condomínios", "text": "Entrada sem chave, controle de portões e luzes."}, {"icon": "building", "title": "Empresas", "text": "Gestão de acessos por perfil, horário e setor."}, {"icon": "graduation", "title": "Educação", "text": "Mapa de presença e comunicação com responsáveis."}], 4)
   + '<div style="height:40px"></div>' + feature("Por que escolher o Xield?", checks(["Implantação rápida e flexível", "Arquitetura escalável e segura", "Compatível com RTSP, Zigbee, Matter e MQTT", "Customizações sob medida para o seu ambiente"]), "{{media:images/xieldimg/xield_08.png}}", "Por que escolher o Xield", rev=True, kicker="🚀 Diferenciais")),
  contact_band(),
 ]), "Xield", "SecurityApplication", meta=["Biometria facial em tempo real", "Nuvem ou on-premises", "RTSP · Matter · Zigbee · MQTT"], image="images/xieldimg/xield_02.png", order=5,
 faq_items=[("O Xield funciona sem internet?", "Sim, na modalidade on-premises, com operação local e via navegador."), ("Quais dispositivos são compatíveis?", "Câmeras RTSP, dispositivos Matter e Zigbee, fechaduras, sensores, campainhas e integrações via MQTT e Home Assistant.")])
GEDAI = prod("gedai",
 "GEDAI — Gerenciador Eletrônico de Documentos e Arquivo Inteligente (GED/ECM) | Trix",
 "GEDAI: solução de GED/ECM da Trix TI com workflow, OCR/ICR, indexação de conteúdo, versionamento, controle do ciclo de vida de documentos físicos e digitais, controle de correspondências e bureau de digitalização. Java, MVC, por direito de acesso ou aquisição.",
 "GEDAI · GED/ECM", "Gerenciamento Eletrônico de Documentos e <strong>Arquivo Inteligente</strong>",
 "O GEDAI reúne metodologias, processos e tecnologias para a implantação do Gerenciamento Eletrônico de Documentos (GED) e da Gestão de Conteúdo Empresarial (ECM) no ambiente de uma organização. Elaborado para empresas de todos os tipos e portes, contempla o controle (manutenção, tramitação e localização) dos documentos produzidos e consumidos pelos processos internos, o ciclo de vida dos documentos físicos e o controle das correspondências entrantes e saintes.",
 "".join([
  sec('<div class="trix-split"><div class="trix-reveal"><span class="trix-kicker">Composição</span><h2>Bureau de digitalização + <strong>sistema GEDAI</strong></h2><p>No Bureau (birô), os documentos são digitalizados seguindo uma linha de produção, garantindo qualidade, produtividade e segurança da informação, disponibilizada em tempo hábil para processos mais eficientes e desburocratização do acesso à informação. O sistema GEDAI reúne tecnologias correlacionadas para garantir a aplicabilidade dos processos necessários à correta implantação do GED.</p><p>O GEDAI abstrai o ambiente organizacional conforme a hierarquia da empresa: permissões de acesso e escrita são definidas antes da implantação, de modo que qualquer documento inserido já possua definição exata de quem precisa acessá-lo. A tramitação física é registrada para manter o histórico da movimentação interna, e todo o ciclo de vida (criação, revisão, reprodução, distribuição, arquivamento, recuperação) é controlado.</p></div><div class="trix-reveal">'
      + cards([{"icon": "layers", "title": "Tecnologias e conceitos", "text": "<strong>Document Management</strong> (captura, controle e recuperação) · <strong>Document Imaging</strong> (imagens digitalizadas em qualquer formato) · <strong>Web Content Management</strong> · <strong>Workflow</strong> · <strong>OCR/ICR</strong> · <strong>Form Processing</strong> · <strong>Indexação de conteúdos</strong> · <strong>Serialização</strong> · <strong>Versionamento</strong>."}], 1, tilt=False) + '</div></div>'),
  sec(head("Características", "Principais características da <strong>solução GEDAI</strong>", "", True)
   + checks(["Distribuição do acesso por perfis de usuário", "Integração com sistemas ERP, RH, GPS ou qualquer outro", "Importação e indexação de lotes de documentos digitalizados", "Definição, validação e formatação dinâmica dos atributos dos tipos de documentos", "Hierarquização do acesso à informação", "Indexação de imagens e textos de documentos", "Mecanismo de pesquisa inteligente (estilo Google): qualquer palavra contida no documento/imagem, PDF, MS-Office, texto, HTML etc., localizada em poucos segundos", "Bureau de digitalização com infraestrutura de hardware, software e capacitação inclusa", "Controle do ciclo de vida do documento", "Controle de correspondências", "Organização física de depósitos: caixas com numeração única, endereçamento por depósito, estante e prateleira — localização do original em poucos minutos"]), "trix-section--sand"),
  sec(head("Benefícios", "O que sua empresa <strong>ganha</strong>")
   + cards([{"icon": "trending", "title": "Produtividade", "text": "Ganho de produtividade e redução do tempo de recuperação do documento."}, {"icon": "shield", "title": "Segurança e acesso", "text": "Segurança, unificação e desburocratização do acesso à informação, com versionamento."}, {"icon": "brain", "title": "Conhecimento", "text": "Base de conhecimento para auxílio à tomada de decisões, com informações mais coesas e de maior qualidade."}, {"icon": "cloud", "title": "Mobilidade e espaço", "text": "Mobilidade e escalabilidade via internet; redução do espaço físico com microfilmagem e descarte de documentos."}], 4)
   + '<p style="margin-top:24px">A solução GEDAI foi desenvolvida para uso por qualquer organização. Com recursos próprios e mão de obra especializada, fornece todos os quesitos para a aplicabilidade de uma solução de GED/ECM inovadora e com baixo investimento. Utilizando a internet é possível manter e acessar todas as informações da sua organização com segurança, velocidade e de forma personalizada — toda a infraestrutura necessária está inclusa na solução.</p>'
   + '<div style="height:24px"></div>' + ARQ("Java", "MVC", "Direito de acesso · Aquisição da solução")),
  contact_band(),
 ]), "GEDAI", "BusinessApplication", meta=["GED/ECM completo", "OCR/ICR e pesquisa inteligente", "Bureau de digitalização"], image="images/09.png", order=6, hero_img=("{{media:images/32.png}}", "GEDAI"))
INTEG = prod("integrador",
 "Integrador — Integração de sistemas e bases de dados heterogêneas em tempo real | Trix",
 "O Integrador Trix permite a integração de sistemas e bases de dados heterogêneas com comunicação em tempo real das operações, adaptando-se ao seu negócio e atuando em qualquer tecnologia, independente do provedor. Java, PostgreSQL, MVC/Struts.",
 "Integrador", "Sistemas e bases heterogêneas conversando <strong>em tempo real</strong>",
 "O Integrador permite a integração de sistemas e bases de dados heterogêneas, realizando a comunicação em tempo real das operações executadas. Utilizando tecnologia específica e adaptando-se às necessidades do seu negócio, o Integrador atua em qualquer tecnologia, independentemente do provedor da solução.",
 "".join([
  sec(cards([{"icon": "plug", "title": "Qualquer tecnologia", "text": "Conecta ERPs, sistemas de gestão de operadoras, bases legadas e novos serviços digitais, independente de fornecedor ou banco de dados."}, {"icon": "clock", "title": "Tempo real", "text": "Operações refletidas imediatamente entre os sistemas, com logs de transações para acompanhamento e auditoria pela operadora."}, {"icon": "shield", "title": "Segurança e rastreabilidade", "text": "Comunicação de alto nível com a base de dados do cliente, monitoramento de consultas e alterações realizadas, e conformidade com a LGPD."}, {"icon": "monitor", "title": "Base do SAW e do Portal Operadora", "text": "É o Integrador que garante a integração personalizada dos sistemas Trix com a base de dados das operadoras, pela internet."}], 4)
   + '<div style="height:32px"></div>' + ARQ("Java", "MVC, Struts", "Direito de acesso · Aquisição da solução", "PostgreSQL")),
  contact_band(),
 ]), "Integrador Trix", "BusinessApplication", meta=["Integração em tempo real", "Independente de tecnologia", "Logs e auditoria"], image="images/10.png", order=7, hero_img=("{{media:images/33.png}}", "Integrador"))
INTRA = prod("intranet",
 "Intranet Trix — Comunicação interna premiada (Prêmio Unimed de Comunicação) | Trix",
 "A Intranet Trix é uma ferramenta web de administração, comunicação e relacionamento interno, com conteúdo colaborativo, mídia organizacional, chat, gestão de pessoas, notícias, informativos e documentos. Bicampeã do Prêmio Unimed de Comunicação (troféu Alberto Urquiza Wanderley).",
 "Intranet Trix · Premiada", "Mais que um site, <strong>uma ferramenta de comunicação</strong>",
 "A Intranet Trix é uma solução para empresas que buscam uma ferramenta web que auxilie na administração, comunicação e relacionamento interno entre as diversas áreas e membros da organização. Aplica conceitos de conteúdo colaborativo, mídia organizacional e gestão tecnológica e virtual de recursos, com tecnologia aberta que permite robustez e adaptação contínua sem ônus de softwares terceiros.",
 "".join([
  sec('<div class="trix-split"><div class="trix-reveal"><span class="trix-kicker">Um sistema premiado</span><h2>Bicampeã do <strong>Prêmio Unimed de Comunicação</strong></h2><p>Pelo segundo ano consecutivo, a Intranet Trix foi premiada com o troféu “Alberto Urquiza Wanderley”, concedido aos vencedores do 6º Prêmio Unimed de Comunicação. Na edição de 2010, venceu na categoria para cooperativas com número de beneficiários entre 40 e 100 mil; na edição de 2009, foi a vencedora da categoria até 30 mil beneficiários. Os vencedores foram revelados durante a 40ª Convenção Nacional Unimed, realizada em Goiânia (GO), de 21 a 24 de setembro.</p></div><div class="trix-reveal">'
      + cards([{"icon": "users", "title": "Perfis e áreas", "text": "Diferentes perfis de usuários com interface específica para RH, jornalismo, compras, almoxarifado, controladoria, financeiro, cadastro e diretorias, com ferramentas que apoiam as atividades e processos de cada setor."}, {"icon": "chat", "title": "Chat corporativo", "text": "Promove colaboração e comunicação interna, reduz gastos com telefone e o tempo de resposta e resolutividade de problemas operacionais e estratégicos."}], 1, tilt=False) + '</div></div>'),
  sec(head("Recursos", "Funcionalidades <strong>por setor</strong>", "", True)
   + cards([{"icon": "users", "title": "Setor de RH", "text": "Gestão de pessoas · Comunicação interna · Aniversariantes do mês · Agenda organizacional · Gestão de questionários."}, {"icon": "megaphone", "title": "Setor de Comunicação", "text": "Gestão de notícias · Gestão de informativos e boletins · Pesquisa de opinião · Gestão de arquivos e documentos."}, {"icon": "chart", "title": "Financeiro e Contabilidade", "text": "Gestão de notícias e informativos do setor, pesquisas de opinião e gestão de arquivos e documentos financeiros."}], 3)
   + '<div style="height:32px"></div>' + checks(["Canal de comunicação com beneficiários", "Canal de comunicação com prestadores", "Adequação às exigências da lei", "Integração a qualquer base de dados e/ou sistema legado: acessa, recupera, utiliza e disponibiliza informações de outras fontes"])
   + ARQ("Java", "MVC", "Direito de acesso · Aquisição da solução"), "trix-section--sand"),
  contact_band(),
 ]), "Intranet Trix", "BusinessApplication", meta=["Prêmio Unimed de Comunicação 2009 e 2010", "Chat e conteúdo colaborativo", "Integração com sistemas legados"], image="images/11.png", order=8, hero_img=("{{media:images/37.png}}", "Intranet Trix"))
PAGES = [HUB, PRONTOW, SAW, PORTAL, ASPECT, XIELD, GEDAI, INTEG, INTRA]
