/* Alicerce360 · textos gerados pelo JavaScript (PT, EN, ES).
   Textos das páginas ficam no HTML e em src/i18n/*.json. */
var A3_UI = {
  pt: {
    'skip': 'Pular para o conteúdo',
    'wa.default': 'Olá! Vim pelo site do Alicerce360 e quero saber mais.',
    'toast.copied': 'Copiado para a área de transferência.',
    'lang.suggest': 'Este site também está disponível em {lang}.',
    'lang.switch': 'Mudar',
    'lang.keep': 'Manter português',
    'lang.name.en': 'inglês', 'lang.name.es': 'espanhol', 'lang.name.pt': 'português',
    'lang.changed': 'Idioma alterado para português.',
    /* FAB */
    'fab.label': 'Fale com a gente',
    'fab.open': 'Abrir opções de contato',
    'fab.close': 'Fechar opções de contato',
    'fab.wa': 'WhatsApp', 'fab.mail': 'E-mail', 'fab.tel': 'Ligar', 'fab.ai': 'Pergunte ao Ali (assistente)',
    'fab.ctt': 'Página de contato', 'fab.map': 'Como chegar', 'fab.ig': 'Instagram', 'fab.li': 'LinkedIn', 'fab.fb': 'Facebook',
    'totop': 'Voltar ao topo',
    /* doca */
    'dock.a11y': 'Acessibilidade', 'dock.cookie': 'Preferências de cookies', 'dock.libras': 'Tradução em Libras',
    /* acessibilidade */
    'a11y.title': 'Acessibilidade',
    'a11y.close': 'Fechar painel de acessibilidade',
    'a11y.text': 'Texto', 'a11y.colors': 'Cores e contraste', 'a11y.reading': 'Leitura e navegação', 'a11y.motion.h': 'Movimento e mídia',
    'a11y.size': 'Tamanho do texto', 'a11y.smaller': 'Diminuir texto', 'a11y.bigger': 'Aumentar texto',
    'a11y.contrast': 'Alto contraste', 'a11y.gray': 'Escala de cinza', 'a11y.links': 'Destacar links',
    'a11y.font': 'Fonte legível', 'a11y.spacing': 'Espaçar texto', 'a11y.guide': 'Régua de leitura',
    'a11y.cursor': 'Cursor ampliado', 'a11y.motion': 'Pausar animações', 'a11y.noimg': 'Ocultar imagens',
    'a11y.read': 'Ouvir a página', 'a11y.stop': 'Parar leitura', 'a11y.libras': 'Libras (VLibras)',
    'a11y.reset': 'Restaurar padrão', 'a11y.statement': 'Declaração de acessibilidade',
    'a11y.keys': 'Atalhos de teclado',
    'a11y.k1': 'ir para o conteúdo', 'a11y.k2': 'ir para o menu', 'a11y.k3': 'ir para o rodapé', 'a11y.k4': 'abrir este painel',
    'a11y.on': 'ativado', 'a11y.off': 'desativado',
    'a11y.noread': 'Seu navegador não oferece leitura em voz alta.',
    /* cookies */
    'ck.title': 'Sua privacidade, suas regras',
    'ck.text': 'Usamos apenas o essencial para o site funcionar e lembrar suas escolhas. Recursos opcionais (como mapa incorporado e assistente com IA) só são ativados com a sua permissão. Você pode mudar de ideia quando quiser.',
    'ck.policy': 'Política de Cookies',
    'ck.accept': 'Aceitar todos', 'ck.reject': 'Rejeitar opcionais', 'ck.custom': 'Personalizar',
    'ck.save': 'Salvar minhas escolhas', 'ck.prefs': 'Preferências de privacidade',
    'ck.intro': 'Escolha quais categorias podem ser usadas. Categorias essenciais não podem ser desligadas porque o site não funciona sem elas. Sua escolha fica registrada com um identificador anônimo e vale por 12 meses.',
    'ck.always': 'Sempre ativos', 'ck.details': 'Ver detalhes', 'ck.none': 'Nenhum em uso no momento. Nada será ativado sem a sua permissão.',
    'ck.name': 'Nome', 'ck.purpose': 'Finalidade', 'ck.duration': 'Duração',
    'ck.id': 'ID do consentimento', 'ck.date': 'Registrado em', 'ck.saved': 'Preferências de privacidade salvas.',
    'ck.close': 'Fechar',
    'ck.c.necessary': 'Essenciais', 'ck.d.necessary': 'Garantem segurança, navegação, registro do seu consentimento e as preferências que você pedir (idioma e acessibilidade). Também carregamos o VLibras, ferramenta pública de acessibilidade do Governo Federal.',
    'ck.c.functional': 'Funcionais', 'ck.d.functional': 'Ativam conteúdos de terceiros que você escolhe usar, como o mapa do Google na página de contato e o assistente com inteligência artificial.',
    'ck.c.analytics': 'Estatísticas', 'ck.d.analytics': 'Medição de audiência para melhorar o site, com dados agregados.',
    'ck.c.marketing': 'Marketing', 'ck.d.marketing': 'Anúncios e remarketing.',
    'ck.i.consent': 'Guarda sua escolha de privacidade', 'ck.i.lang': 'Lembra o idioma escolhido', 'ck.i.a11y': 'Lembra suas preferências de acessibilidade',
    'ck.i.mascot': 'Lembra se você minimizou o mascote', 'ck.i.vlibras': 'Tradução para Libras (Governo Federal)', 'ck.i.maps': 'Mapa incorporado (Google)', 'ck.i.ai': 'Envio das perguntas ao provedor de IA',
    'ck.12m': '12 meses', 'ck.persist': 'Até você limpar o navegador', 'ck.session': 'Sessão', 'ck.third': 'Definida pelo terceiro',
    /* mascote */
    'm.hello': 'Oi! Eu sou o Ali, o mascote do Alicerce360. Role a página que eu vou junto!',
    'm.idle': 'Ficou com alguma dúvida? Clique em mim e pergunte.',
    'm.fast': 'Ufa! Que rapidez! Tem muita coisa boa no caminho…',
    'm.sleep': 'Zzz… clique para me acordar.',
    'm.top': 'De volta ao topo! Quer ver os planos?',
    'm.bottom': 'Chegamos ao fim! Que tal falar com um especialista?',
    'm.hide': 'Esconder o mascote', 'm.show': 'Mostrar o mascote Ali', 'm.ask': 'Pergunte ao Ali',
    /* chat */
    'ch.title': 'Ali · Assistente Alicerce360',
    'ch.local': 'Base de conhecimento', 'ch.ai': 'IA conectada (FreeLLMAPI)',
    'ch.greet': 'Olá! Sou o Ali. Posso explicar planos, hospedagem, LGPD e recursos da intranet — ou te levar a um especialista humano. Como posso ajudar?',
    'ch.ph': 'Escreva sua pergunta…', 'ch.send': 'Enviar pergunta', 'ch.close': 'Fechar assistente',
    'ch.note': 'Não envie dados pessoais sensíveis. Respostas automáticas podem conter imprecisões: confirme com nossa equipe.',
    'ch.fallback': 'Ainda não sei responder isso com segurança. Prefere falar com uma pessoa? [Chamar no WhatsApp]({wa}) ou [enviar mensagem](/contato/).',
    'ch.err': 'Não consegui consultar a IA agora, então respondi pela base local.',
    'ch.consent': 'Para usar a IA, suas perguntas serão enviadas ao nosso servidor de IA. Ative a categoria "Funcionais" nas preferências de cookies ou continue com as respostas da base local.',
    'ch.s1': 'Quanto custa?', 'ch.s2': 'Tem teste grátis?', 'ch.s3': 'Hospedagem com e-mail', 'ch.s4': 'Como fica a LGPD?', 'ch.s5': 'Falar com uma pessoa',
    /* preços */
    'pr.month': '/mês', 'pr.upto': 'até {n} usuários', 'pr.peruser': '≈ {v} por usuário/mês',
    'pr.yearly': '{v} cobrados por ano · você economiza {s}', 'pr.monthly': 'Cobrança mensal, sem fidelidade',
    'pr.self': 'Licença para instalar no seu servidor (hospedagem por sua conta)', 'pr.cloud': 'Inclui hospedagem gerenciada, backup e SSL',
    'pr.big': 'Mais de 1.000 usuários? Temos proposta sob medida.',
    'pr.choose': 'Quero o plano {p}', 'pr.msg': 'Olá! Tenho interesse no plano {p} do Alicerce360 ({u}, {b}, {h}). Podem me enviar uma proposta?',
    'pr.b.m': 'cobrança mensal', 'pr.b.y': 'cobrança anual', 'pr.h.cloud': 'na nuvem EBAEM', 'pr.h.self': 'no meu servidor',
    'sim.users': '{n} colaboradores', 'sim.save': 'de economia estimada em 12 meses', 'sim.pct': '{p}% a menos que pagar por usuário',
    'sim.more': 'Acima de 1.000 colaboradores: comparação feita com a faixa de 1.000; peça proposta sob medida.',
    'sim.none': 'Nessa faixa, o valor por usuário é parecido — o ganho está nos recursos de conformidade e na posse dos dados.',
    'host.month': '/mês', 'host.yearly': '{v} por ano · 2 meses grátis', 'host.monthly': 'Cobrança mensal, sem fidelidade',
    'host.msg': 'Olá! Quero contratar a hospedagem {p} ({b}).',
    /* formulários */
    'f.required': 'Preencha este campo.', 'f.email': 'Informe um e-mail válido.', 'f.consent': 'Para continuar, marque a caixa de concordância.',
    'f.ok.wa': 'Pronto! Abrimos o WhatsApp com sua mensagem preenchida. Protocolo de referência: {p}.',
    'f.ok.mail': 'Pronto! Abrimos seu aplicativo de e-mail com a mensagem preenchida. Protocolo de referência: {p}.',
    'f.ok.hint': 'Se nada abriu, escreva para {m} informando o protocolo.',
    'f.subject': 'Alicerce360 · {t} · {p}', 'f.proto': 'Protocolo',
    'f.t.contact': 'Contato', 'f.t.titular': 'Solicitação de titular (LGPD)', 'f.t.integrity': 'Relato de integridade', 'f.t.referral': 'Indicação de cliente', 'f.t.trial': 'Teste grátis de 30 dias', 'f.t.partner': 'Parceria',
    'dom.empty': 'Digite um domínio para pesquisar.',
    /* demonstrações */
    'demo.ack': 'Ciente registrado às {h} · hash {x}', 'demo.verify.ok': 'Trilha íntegra: {n} registros conferidos', 'demo.verify.bad': 'Alerta: o registro #{r} foi alterado fora do sistema',
    'demo.unlock': 'Quiz aprovado com {n}% — Módulo 2 liberado!', 'demo.ticket': 'Protocolo {p} avançou para: {s}',
    'demo.st.1': 'Triagem', 'demo.st.2': 'Em análise', 'demo.st.3': 'Respondido', 'demo.st.4': 'Concluído',
    'map.load': 'Carregar mapa',
    'reveal.touch': 'Toque para revelar',
    /* papel 3D */
    'p.off': 'Câmera desligada', 'p.loading': 'Carregando detector de mãos…', 'p.show': 'Mostre a palma da mão para a câmera',
    'p.hand': 'Mão detectada: abra para desamassar, feche para amassar', 'p.nocam': 'Câmera indisponível — use o controle deslizante ou arraste',
    'p.done': 'Desamassado! Norma viva, versão controlada.', 'p.drag': 'Arraste para cima para desamassar', 'p.camoff': 'Desligar câmera', 'p.camon': 'Ativar câmera',
    'p.par': 'Mova o mouse (ou incline o celular) e veja a profundidade real', 'p.gyro': 'Ativar inclinação do celular',
    'p.doc1': 'PROCEDIMENTO', 'p.doc2': 'Versão impressa', 'p.doc3': 'NÃO CONTROLADA', 'p.doc4': 'Quem leu? Ninguém sabe.',
    'p.ok1': 'POLÍTICA DE QUALIDADE', 'p.ok2': 'Versão 3.2 · vigente', 'p.ok3': '98% de ciência registrada', 'p.ok4': 'Trilha de auditoria íntegra',
    'p.note': 'Lembrete: revisar a política!', 'p.old': 'Assinada em 2019'
  },
  en: {
    'skip': 'Skip to content',
    'wa.default': 'Hi! I found you on the Alicerce360 website and would like to know more.',
    'toast.copied': 'Copied to clipboard.',
    'lang.suggest': 'This website is also available in {lang}.',
    'lang.switch': 'Switch', 'lang.keep': 'Keep Portuguese',
    'lang.name.en': 'English', 'lang.name.es': 'Spanish', 'lang.name.pt': 'Portuguese',
    'lang.changed': 'Language changed to English.',
    'fab.label': 'Talk to us', 'fab.open': 'Open contact options', 'fab.close': 'Close contact options',
    'fab.wa': 'WhatsApp', 'fab.mail': 'Email', 'fab.tel': 'Call us', 'fab.ai': 'Ask Ali (assistant)',
    'fab.ctt': 'Contact page', 'fab.map': 'Directions', 'fab.ig': 'Instagram', 'fab.li': 'LinkedIn', 'fab.fb': 'Facebook',
    'totop': 'Back to top',
    'dock.a11y': 'Accessibility', 'dock.cookie': 'Cookie preferences', 'dock.libras': 'Brazilian Sign Language (Libras)',
    'a11y.title': 'Accessibility', 'a11y.close': 'Close accessibility panel',
    'a11y.text': 'Text', 'a11y.colors': 'Colors and contrast', 'a11y.reading': 'Reading and navigation', 'a11y.motion.h': 'Motion and media',
    'a11y.size': 'Text size', 'a11y.smaller': 'Decrease text', 'a11y.bigger': 'Increase text',
    'a11y.contrast': 'High contrast', 'a11y.gray': 'Grayscale', 'a11y.links': 'Highlight links',
    'a11y.font': 'Readable font', 'a11y.spacing': 'Text spacing', 'a11y.guide': 'Reading guide',
    'a11y.cursor': 'Large cursor', 'a11y.motion': 'Pause animations', 'a11y.noimg': 'Hide images',
    'a11y.read': 'Read page aloud', 'a11y.stop': 'Stop reading', 'a11y.libras': 'Libras (VLibras)',
    'a11y.reset': 'Reset', 'a11y.statement': 'Accessibility statement',
    'a11y.keys': 'Keyboard shortcuts',
    'a11y.k1': 'go to content', 'a11y.k2': 'go to menu', 'a11y.k3': 'go to footer', 'a11y.k4': 'open this panel',
    'a11y.on': 'on', 'a11y.off': 'off', 'a11y.noread': 'Your browser does not support text-to-speech.',
    'ck.title': 'Your privacy, your rules',
    'ck.text': 'We only use what is essential for the website to work and to remember your choices. Optional features (such as the embedded map and the AI assistant) are only enabled with your permission. You can change your mind at any time.',
    'ck.policy': 'Cookie Policy',
    'ck.accept': 'Accept all', 'ck.reject': 'Reject optional', 'ck.custom': 'Customize',
    'ck.save': 'Save my choices', 'ck.prefs': 'Privacy preferences',
    'ck.intro': 'Choose which categories may be used. Essential categories cannot be turned off because the website does not work without them. Your choice is recorded with an anonymous identifier and is valid for 12 months.',
    'ck.always': 'Always on', 'ck.details': 'See details', 'ck.none': 'None in use at the moment. Nothing will be enabled without your permission.',
    'ck.name': 'Name', 'ck.purpose': 'Purpose', 'ck.duration': 'Duration',
    'ck.id': 'Consent ID', 'ck.date': 'Recorded on', 'ck.saved': 'Privacy preferences saved.', 'ck.close': 'Close',
    'ck.c.necessary': 'Essential', 'ck.d.necessary': 'Ensure security, navigation, the record of your consent and the preferences you request (language and accessibility). We also load VLibras, the Brazilian Federal Government public accessibility tool.',
    'ck.c.functional': 'Functional', 'ck.d.functional': 'Enable third-party content you choose to use, such as the Google map on the contact page and the artificial intelligence assistant.',
    'ck.c.analytics': 'Statistics', 'ck.d.analytics': 'Audience measurement to improve the website, using aggregated data.',
    'ck.c.marketing': 'Marketing', 'ck.d.marketing': 'Ads and remarketing.',
    'ck.i.consent': 'Stores your privacy choice', 'ck.i.lang': 'Remembers the chosen language', 'ck.i.a11y': 'Remembers your accessibility preferences',
    'ck.i.mascot': 'Remembers whether you minimized the mascot', 'ck.i.vlibras': 'Libras translation (Federal Government)', 'ck.i.maps': 'Embedded map (Google)', 'ck.i.ai': 'Sends your questions to the AI provider',
    'ck.12m': '12 months', 'ck.persist': 'Until you clear your browser', 'ck.session': 'Session', 'ck.third': 'Set by the third party',
    'm.hello': "Hi! I'm Ali, the Alicerce360 mascot. Scroll down and I'll come along!",
    'm.idle': 'Got a question? Click me and ask.',
    'm.fast': 'Whoa, that was fast! Lots of good stuff along the way…',
    'm.sleep': 'Zzz… click to wake me up.',
    'm.top': 'Back to the top! Want to see the plans?',
    'm.bottom': "We've reached the end! How about talking to a specialist?",
    'm.hide': 'Hide the mascot', 'm.show': 'Show Ali the mascot', 'm.ask': 'Ask Ali',
    'ch.title': 'Ali · Alicerce360 Assistant', 'ch.local': 'Knowledge base', 'ch.ai': 'AI connected (FreeLLMAPI)',
    'ch.greet': "Hello! I'm Ali. I can explain plans, hosting, data protection and intranet features — or connect you with a human specialist. How can I help?",
    'ch.ph': 'Type your question…', 'ch.send': 'Send question', 'ch.close': 'Close assistant',
    'ch.note': 'Do not share sensitive personal data. Automated answers may contain inaccuracies: please confirm with our team.',
    'ch.fallback': "I can't answer that reliably yet. Would you rather talk to a person? [Chat on WhatsApp]({wa}) or [send a message](/contato/).",
    'ch.err': "I couldn't reach the AI right now, so I answered from the local knowledge base.",
    'ch.consent': 'To use AI, your questions will be sent to our AI server. Enable the "Functional" category in cookie preferences or keep using knowledge-base answers.',
    'ch.s1': 'How much is it?', 'ch.s2': 'Is there a free trial?', 'ch.s3': 'Hosting with email', 'ch.s4': 'What about LGPD?', 'ch.s5': 'Talk to a person',
    'pr.month': '/month', 'pr.upto': 'up to {n} users', 'pr.peruser': '≈ {v} per user/month',
    'pr.yearly': '{v} billed yearly · you save {s}', 'pr.monthly': 'Monthly billing, no lock-in',
    'pr.self': 'License to install on your own server (hosting on your side)', 'pr.cloud': 'Includes managed hosting, backup and SSL',
    'pr.big': 'More than 1,000 users? We have a tailored proposal.',
    'pr.choose': 'I want the {p} plan', 'pr.msg': 'Hi! I am interested in the Alicerce360 {p} plan ({u}, {b}, {h}). Could you send me a proposal?',
    'pr.b.m': 'monthly billing', 'pr.b.y': 'yearly billing', 'pr.h.cloud': 'on EBAEM cloud', 'pr.h.self': 'on my own server',
    'sim.users': '{n} employees', 'sim.save': 'estimated savings over 12 months', 'sim.pct': '{p}% less than paying per user',
    'sim.more': 'Over 1,000 employees: compared with the 1,000 tier; ask for a tailored proposal.',
    'sim.none': 'In this range the per-user value is similar — the gain lies in compliance features and data ownership.',
    'host.month': '/month', 'host.yearly': '{v} per year · 2 months free', 'host.monthly': 'Monthly billing, no lock-in',
    'host.msg': 'Hi! I would like to sign up for the {p} hosting plan ({b}).',
    'f.required': 'Please fill in this field.', 'f.email': 'Please enter a valid email.', 'f.consent': 'To continue, please tick the consent box.',
    'f.ok.wa': 'Done! We opened WhatsApp with your message filled in. Reference number: {p}.',
    'f.ok.mail': 'Done! We opened your email app with the message filled in. Reference number: {p}.',
    'f.ok.hint': 'If nothing opened, write to {m} quoting the reference number.',
    'f.subject': 'Alicerce360 · {t} · {p}', 'f.proto': 'Reference',
    'f.t.contact': 'Contact', 'f.t.titular': 'Data subject request (LGPD)', 'f.t.integrity': 'Integrity report', 'f.t.referral': 'Customer referral', 'f.t.trial': '30-day free trial', 'f.t.partner': 'Partnership',
    'dom.empty': 'Type a domain to search.',
    'demo.ack': 'Acknowledged at {h} · hash {x}', 'demo.verify.ok': 'Trail intact: {n} records verified', 'demo.verify.bad': 'Alert: record #{r} was altered outside the system',
    'demo.unlock': 'Quiz passed with {n}% — Module 2 unlocked!', 'demo.ticket': 'Ticket {p} moved to: {s}',
    'demo.st.1': 'Triage', 'demo.st.2': 'Under review', 'demo.st.3': 'Answered', 'demo.st.4': 'Closed',
    'map.load': 'Load map', 'reveal.touch': 'Tap to reveal',
    'p.off': 'Camera off', 'p.loading': 'Loading hand detector…', 'p.show': 'Show your palm to the camera',
    'p.hand': 'Hand detected: open to smooth it out, close to crumple', 'p.nocam': 'Camera unavailable — use the slider or drag',
    'p.done': 'Smoothed out! A living, controlled standard.', 'p.drag': 'Drag up to smooth out the paper', 'p.camoff': 'Turn camera off', 'p.camon': 'Turn camera on',
    'p.par': 'Move your mouse (or tilt your phone) to see real depth', 'p.gyro': 'Enable phone tilt',
    'p.doc1': 'PROCEDURE', 'p.doc2': 'Printed version', 'p.doc3': 'UNCONTROLLED', 'p.doc4': 'Who read it? Nobody knows.',
    'p.ok1': 'QUALITY POLICY', 'p.ok2': 'Version 3.2 · in force', 'p.ok3': '98% acknowledgement recorded', 'p.ok4': 'Audit trail intact',
    'p.note': 'Reminder: review the policy!', 'p.old': 'Signed in 2019'
  },
  es: {
    'skip': 'Saltar al contenido',
    'wa.default': '¡Hola! Vi el sitio de Alicerce360 y quiero saber más.',
    'toast.copied': 'Copiado al portapapeles.',
    'lang.suggest': 'Este sitio también está disponible en {lang}.',
    'lang.switch': 'Cambiar', 'lang.keep': 'Mantener portugués',
    'lang.name.en': 'inglés', 'lang.name.es': 'español', 'lang.name.pt': 'portugués',
    'lang.changed': 'Idioma cambiado a español.',
    'fab.label': 'Habla con nosotros', 'fab.open': 'Abrir opciones de contacto', 'fab.close': 'Cerrar opciones de contacto',
    'fab.wa': 'WhatsApp', 'fab.mail': 'Correo', 'fab.tel': 'Llamar', 'fab.ai': 'Pregúntale a Ali (asistente)',
    'fab.ctt': 'Página de contacto', 'fab.map': 'Cómo llegar', 'fab.ig': 'Instagram', 'fab.li': 'LinkedIn', 'fab.fb': 'Facebook',
    'totop': 'Volver arriba',
    'dock.a11y': 'Accesibilidad', 'dock.cookie': 'Preferencias de cookies', 'dock.libras': 'Lengua de señas brasileña (Libras)',
    'a11y.title': 'Accesibilidad', 'a11y.close': 'Cerrar panel de accesibilidad',
    'a11y.text': 'Texto', 'a11y.colors': 'Colores y contraste', 'a11y.reading': 'Lectura y navegación', 'a11y.motion.h': 'Movimiento y medios',
    'a11y.size': 'Tamaño del texto', 'a11y.smaller': 'Reducir texto', 'a11y.bigger': 'Aumentar texto',
    'a11y.contrast': 'Alto contraste', 'a11y.gray': 'Escala de grises', 'a11y.links': 'Resaltar enlaces',
    'a11y.font': 'Fuente legible', 'a11y.spacing': 'Espaciar texto', 'a11y.guide': 'Guía de lectura',
    'a11y.cursor': 'Cursor grande', 'a11y.motion': 'Pausar animaciones', 'a11y.noimg': 'Ocultar imágenes',
    'a11y.read': 'Escuchar la página', 'a11y.stop': 'Detener lectura', 'a11y.libras': 'Libras (VLibras)',
    'a11y.reset': 'Restablecer', 'a11y.statement': 'Declaración de accesibilidad',
    'a11y.keys': 'Atajos de teclado',
    'a11y.k1': 'ir al contenido', 'a11y.k2': 'ir al menú', 'a11y.k3': 'ir al pie de página', 'a11y.k4': 'abrir este panel',
    'a11y.on': 'activado', 'a11y.off': 'desactivado', 'a11y.noread': 'Tu navegador no ofrece lectura en voz alta.',
    'ck.title': 'Tu privacidad, tus reglas',
    'ck.text': 'Usamos solo lo esencial para que el sitio funcione y recuerde tus elecciones. Las funciones opcionales (como el mapa incrustado y el asistente con IA) solo se activan con tu permiso. Puedes cambiar de opinión cuando quieras.',
    'ck.policy': 'Política de Cookies',
    'ck.accept': 'Aceptar todas', 'ck.reject': 'Rechazar opcionales', 'ck.custom': 'Personalizar',
    'ck.save': 'Guardar mis elecciones', 'ck.prefs': 'Preferencias de privacidad',
    'ck.intro': 'Elige qué categorías se pueden usar. Las categorías esenciales no se pueden desactivar porque el sitio no funciona sin ellas. Tu elección queda registrada con un identificador anónimo y es válida por 12 meses.',
    'ck.always': 'Siempre activas', 'ck.details': 'Ver detalles', 'ck.none': 'Ninguna en uso por ahora. Nada se activará sin tu permiso.',
    'ck.name': 'Nombre', 'ck.purpose': 'Finalidad', 'ck.duration': 'Duración',
    'ck.id': 'ID del consentimiento', 'ck.date': 'Registrado el', 'ck.saved': 'Preferencias de privacidad guardadas.', 'ck.close': 'Cerrar',
    'ck.c.necessary': 'Esenciales', 'ck.d.necessary': 'Garantizan seguridad, navegación, el registro de tu consentimiento y las preferencias que solicites (idioma y accesibilidad). También cargamos VLibras, herramienta pública de accesibilidad del Gobierno Federal de Brasil.',
    'ck.c.functional': 'Funcionales', 'ck.d.functional': 'Activan contenidos de terceros que eliges usar, como el mapa de Google en la página de contacto y el asistente con inteligencia artificial.',
    'ck.c.analytics': 'Estadísticas', 'ck.d.analytics': 'Medición de audiencia para mejorar el sitio, con datos agregados.',
    'ck.c.marketing': 'Marketing', 'ck.d.marketing': 'Anuncios y remarketing.',
    'ck.i.consent': 'Guarda tu elección de privacidad', 'ck.i.lang': 'Recuerda el idioma elegido', 'ck.i.a11y': 'Recuerda tus preferencias de accesibilidad',
    'ck.i.mascot': 'Recuerda si minimizaste la mascota', 'ck.i.vlibras': 'Traducción a Libras (Gobierno Federal)', 'ck.i.maps': 'Mapa incrustado (Google)', 'ck.i.ai': 'Envío de tus preguntas al proveedor de IA',
    'ck.12m': '12 meses', 'ck.persist': 'Hasta que limpies el navegador', 'ck.session': 'Sesión', 'ck.third': 'Definida por el tercero',
    'm.hello': '¡Hola! Soy Ali, la mascota de Alicerce360. ¡Desplázate y te acompaño!',
    'm.idle': '¿Tienes alguna duda? Haz clic en mí y pregunta.',
    'm.fast': '¡Uf, qué rapidez! Hay muchas cosas buenas en el camino…',
    'm.sleep': 'Zzz… haz clic para despertarme.',
    'm.top': '¡De vuelta arriba! ¿Quieres ver los planes?',
    'm.bottom': '¡Llegamos al final! ¿Qué tal hablar con un especialista?',
    'm.hide': 'Ocultar la mascota', 'm.show': 'Mostrar a Ali, la mascota', 'm.ask': 'Pregúntale a Ali',
    'ch.title': 'Ali · Asistente Alicerce360', 'ch.local': 'Base de conocimiento', 'ch.ai': 'IA conectada (FreeLLMAPI)',
    'ch.greet': '¡Hola! Soy Ali. Puedo explicarte planes, hosting, protección de datos y funciones de la intranet, o ponerte en contacto con un especialista. ¿Cómo te ayudo?',
    'ch.ph': 'Escribe tu pregunta…', 'ch.send': 'Enviar pregunta', 'ch.close': 'Cerrar asistente',
    'ch.note': 'No compartas datos personales sensibles. Las respuestas automáticas pueden contener imprecisiones: confírmalas con nuestro equipo.',
    'ch.fallback': 'Todavía no sé responder eso con seguridad. ¿Prefieres hablar con una persona? [Escribir por WhatsApp]({wa}) o [enviar un mensaje](/contato/).',
    'ch.err': 'No pude consultar la IA ahora, así que respondí con la base local.',
    'ch.consent': 'Para usar la IA, tus preguntas se enviarán a nuestro servidor de IA. Activa la categoría "Funcionales" en las preferencias de cookies o sigue con las respuestas de la base local.',
    'ch.s1': '¿Cuánto cuesta?', 'ch.s2': '¿Hay prueba gratis?', 'ch.s3': 'Hosting con correo', 'ch.s4': '¿Y la LGPD?', 'ch.s5': 'Hablar con una persona',
    'pr.month': '/mes', 'pr.upto': 'hasta {n} usuarios', 'pr.peruser': '≈ {v} por usuario/mes',
    'pr.yearly': '{v} facturados al año · ahorras {s}', 'pr.monthly': 'Facturación mensual, sin permanencia',
    'pr.self': 'Licencia para instalar en tu propio servidor (hosting por tu cuenta)', 'pr.cloud': 'Incluye hosting gestionado, copias de seguridad y SSL',
    'pr.big': '¿Más de 1.000 usuarios? Tenemos una propuesta a medida.',
    'pr.choose': 'Quiero el plan {p}', 'pr.msg': '¡Hola! Me interesa el plan {p} de Alicerce360 ({u}, {b}, {h}). ¿Me pueden enviar una propuesta?',
    'pr.b.m': 'facturación mensual', 'pr.b.y': 'facturación anual', 'pr.h.cloud': 'en la nube de EBAEM', 'pr.h.self': 'en mi propio servidor',
    'sim.users': '{n} colaboradores', 'sim.save': 'de ahorro estimado en 12 meses', 'sim.pct': '{p}% menos que pagar por usuario',
    'sim.more': 'Más de 1.000 colaboradores: comparado con la franja de 1.000; solicita una propuesta a medida.',
    'sim.none': 'En esta franja el valor por usuario es similar: la ganancia está en las funciones de cumplimiento y en la propiedad de los datos.',
    'host.month': '/mes', 'host.yearly': '{v} al año · 2 meses gratis', 'host.monthly': 'Facturación mensual, sin permanencia',
    'host.msg': '¡Hola! Quiero contratar el hosting {p} ({b}).',
    'f.required': 'Completa este campo.', 'f.email': 'Introduce un correo válido.', 'f.consent': 'Para continuar, marca la casilla de conformidad.',
    'f.ok.wa': '¡Listo! Abrimos WhatsApp con tu mensaje completado. Número de referencia: {p}.',
    'f.ok.mail': '¡Listo! Abrimos tu aplicación de correo con el mensaje completado. Número de referencia: {p}.',
    'f.ok.hint': 'Si no se abrió nada, escribe a {m} indicando el número de referencia.',
    'f.subject': 'Alicerce360 · {t} · {p}', 'f.proto': 'Referencia',
    'f.t.contact': 'Contacto', 'f.t.titular': 'Solicitud del titular (LGPD)', 'f.t.integrity': 'Reporte de integridad', 'f.t.referral': 'Recomendación de cliente', 'f.t.trial': 'Prueba gratis de 30 días', 'f.t.partner': 'Alianza',
    'dom.empty': 'Escribe un dominio para buscar.',
    'demo.ack': 'Conformidad registrada a las {h} · hash {x}', 'demo.verify.ok': 'Registro íntegro: {n} entradas verificadas', 'demo.verify.bad': 'Alerta: la entrada #{r} fue alterada fuera del sistema',
    'demo.unlock': '¡Quiz aprobado con {n}%! Módulo 2 desbloqueado.', 'demo.ticket': 'El protocolo {p} avanzó a: {s}',
    'demo.st.1': 'Clasificación', 'demo.st.2': 'En análisis', 'demo.st.3': 'Respondido', 'demo.st.4': 'Cerrado',
    'map.load': 'Cargar mapa', 'reveal.touch': 'Toca para revelar',
    'p.off': 'Cámara apagada', 'p.loading': 'Cargando detector de manos…', 'p.show': 'Muestra la palma de la mano a la cámara',
    'p.hand': 'Mano detectada: ábrela para alisar, ciérrala para arrugar', 'p.nocam': 'Cámara no disponible: usa el control deslizante o arrastra',
    'p.done': '¡Alisado! Norma viva, versión controlada.', 'p.drag': 'Arrastra hacia arriba para alisar el papel', 'p.camoff': 'Apagar cámara', 'p.camon': 'Activar cámara',
    'p.par': 'Mueve el ratón (o inclina el móvil) y verás la profundidad real', 'p.gyro': 'Activar inclinación del móvil',
    'p.doc1': 'PROCEDIMIENTO', 'p.doc2': 'Versión impresa', 'p.doc3': 'NO CONTROLADA', 'p.doc4': '¿Quién lo leyó? Nadie sabe.',
    'p.ok1': 'POLÍTICA DE CALIDAD', 'p.ok2': 'Versión 3.2 · vigente', 'p.ok3': '98% de conformidad registrada', 'p.ok4': 'Registro de auditoría íntegro',
    'p.note': '¡Recordatorio: revisar la política!', 'p.old': 'Firmada en 2019'
  }
};

/* Base de conhecimento do assistente (respostas locais e contexto para a IA). */
var A3_KB = [
  { k: ['preco', 'precos', 'custa', 'valor', 'valores', 'plano', 'planos', 'mensalidade', 'price', 'pricing', 'cost', 'plan', 'precio', 'cuanto', 'costo'],
    pt: 'Os planos da intranet são cobrados por faixa de colaboradores, não por usuário: Essencial a partir de R$ 290/mês, Profissional a partir de R$ 590/mês e Enterprise a partir de R$ 990/mês (até 50 usuários). No plano anual você paga 10 meses e leva 12. Simule sua faixa em [Planos e preços](/planos/).',
    en: 'Intranet plans are priced by employee tier, not per user: Essential from R$ 290/month, Professional from R$ 590/month and Enterprise from R$ 990/month (up to 50 users). With yearly billing you pay 10 months and get 12. Simulate your tier at [Plans and pricing](/planos/).',
    es: 'Los planes de la intranet se cobran por franja de colaboradores, no por usuario: Esencial desde R$ 290/mes, Profesional desde R$ 590/mes y Enterprise desde R$ 990/mes (hasta 50 usuarios). Con el plan anual pagas 10 meses y tienes 12. Simula tu franja en [Planes y precios](/planos/).' },
  { k: ['teste', 'gratis', 'gratuito', 'trial', 'free', 'demo', 'demonstracao', 'prueba', 'testar'],
    pt: 'Sim! O teste grátis dura 30 dias, com todos os módulos liberados e sem limite de usuários, sem cartão de crédito. Ao final, a intranet entra em modo somente leitura — nada é apagado — até você contratar. [Pedir meu teste](/planos/#teste).',
    en: 'Yes! The free trial lasts 30 days, with every module enabled and no user limit, no credit card required. At the end, the intranet switches to read-only — nothing is deleted — until you subscribe. [Request my trial](/planos/#teste).',
    es: '¡Sí! La prueba gratis dura 30 días, con todos los módulos habilitados y sin límite de usuarios, sin tarjeta de crédito. Al final, la intranet pasa a modo solo lectura — no se borra nada — hasta que contrates. [Pedir mi prueba](/planos/#teste).' },
  { k: ['usuario', 'usuarios', 'por usuario', 'licenca por usuario', 'per user', 'seat', 'seats', 'colaboradores'],
    pt: 'No Alicerce360 você não paga por usuário: o preço é fixo por faixa (50, 100, 200, 500 ou 1.000 colaboradores). Isso costuma sair bem mais barato que intranets cobradas por cabeça — veja o simulador em [Planos](/planos/#simulador).',
    en: 'With Alicerce360 you do not pay per user: the price is fixed per tier (50, 100, 200, 500 or 1,000 employees). That is usually far cheaper than per-seat intranets — try the simulator on [Plans](/planos/#simulador).',
    es: 'Con Alicerce360 no pagas por usuario: el precio es fijo por franja (50, 100, 200, 500 o 1.000 colaboradores). Suele salir mucho más barato que las intranets cobradas por usuario: prueba el simulador en [Planes](/planos/#simulador).' },
  { k: ['hospedagem', 'hosting', 'servidor', 'site', 'sites', 'cpanel', 'alojamiento', 'vps'],
    pt: 'Temos hospedagem gerenciada para sites e e-mails: SSL grátis, backup diário, antivírus e firewall no servidor, cPanel e suporte em português. Planos a partir de R$ 34,90/mês. Veja em [Hospedagem](/hospedagem/).',
    en: 'We offer managed hosting for websites and email: free SSL, daily backups, server-side antivirus and firewall, cPanel and support in Portuguese. Plans from R$ 34.90/month. See [Hosting](/hospedagem/).',
    es: 'Tenemos hosting gestionado para sitios y correos: SSL gratis, copia de seguridad diaria, antivirus y firewall en el servidor, cPanel y soporte en portugués. Planes desde R$ 34,90/mes. Mira [Hosting](/hospedagem/).' },
  { k: ['email', 'e-mail', 'correio', 'webmail', 'caixa', 'correo', 'mail'],
    pt: 'Todos os planos de hospedagem incluem e-mail profissional com seu domínio (webmail, IMAP/SMTP no celular e no Outlook), antispam e autenticação SPF, DKIM e DMARC configurada. Se preferir, a EBAEM também revende Microsoft 365 e Google Workspace. [Ver planos de hospedagem](/hospedagem/).',
    en: 'All hosting plans include professional email on your domain (webmail, IMAP/SMTP on phones and Outlook), anti-spam and SPF, DKIM and DMARC authentication set up. If you prefer, EBAEM also resells Microsoft 365 and Google Workspace. [See hosting plans](/hospedagem/).',
    es: 'Todos los planes de hosting incluyen correo profesional con tu dominio (webmail, IMAP/SMTP en el móvil y en Outlook), antispam y autenticación SPF, DKIM y DMARC configurada. Si lo prefieres, EBAEM también revende Microsoft 365 y Google Workspace. [Ver planes de hosting](/hospedagem/).' },
  { k: ['backup', 'copia', 'restauracao', 'restaurar', 'restore'],
    pt: 'Backup diário automático com retenção de 7 a 30 dias conforme o plano, restauração em poucos cliques pelo painel e cópia externa (offsite) nos planos Pro e VPS. [Detalhes](/hospedagem/#recursos).',
    en: 'Automatic daily backups kept for 7 to 30 days depending on the plan, restore in a few clicks from the panel, and an offsite copy on the Pro and VPS plans. [Details](/hospedagem/#recursos).',
    es: 'Copia de seguridad diaria automática con retención de 7 a 30 días según el plan, restauración en pocos clics desde el panel y copia externa en los planes Pro y VPS. [Detalles](/hospedagem/#recursos).' },
  { k: ['ssl', 'https', 'certificado', 'antivirus', 'virus', 'malware', 'firewall', 'waf', 'seguranca', 'security', 'seguridad'],
    pt: 'Segurança vem de fábrica: SSL gratuito e renovado automaticamente, antivírus e antimalware no servidor, firewall de aplicação, proteção contra força bruta e monitoramento. Na intranet, há ainda trilha de auditoria encadeada por hash e 2FA. [Segurança](/intranet/#seguranca).',
    en: 'Security comes built in: free auto-renewing SSL, server-side antivirus and anti-malware, web application firewall, brute-force protection and monitoring. The intranet adds a hash-chained audit trail and 2FA. [Security](/intranet/#seguranca).',
    es: 'La seguridad viene de fábrica: SSL gratuito con renovación automática, antivirus y antimalware en el servidor, firewall de aplicaciones, protección contra fuerza bruta y monitoreo. La intranet añade un registro de auditoría encadenado por hash y 2FA. [Seguridad](/intranet/#seguranca).' },
  { k: ['lgpd', 'privacidade', 'dados pessoais', 'titular', 'dpo', 'encarregado', 'privacy', 'gdpr', 'datos'],
    pt: 'A LGPD está no DNA do produto: canal do titular com protocolo, registro de aceites com hash, exportação de dados e anonimato real no canal de denúncias. Para exercer seus direitos junto à EBAEM, use o [Portal do Titular](/lgpd/#portal) ou escreva para lgpd@ebaem.com.br.',
    en: 'Data protection is part of the product DNA: data subject channel with ticket numbers, hash-based acceptance records, data export and real anonymity in the whistleblowing channel. To exercise your rights with EBAEM, use the [Data Subject Portal](/lgpd/#portal) or email lgpd@ebaem.com.br.',
    es: 'La protección de datos está en el ADN del producto: canal del titular con protocolo, registro de aceptaciones con hash, exportación de datos y anonimato real en el canal de denuncias. Para ejercer tus derechos ante EBAEM, usa el [Portal del Titular](/lgpd/#portal) o escribe a lgpd@ebaem.com.br.' },
  { k: ['compliance', 'denuncia', 'integridade', 'etica', 'anonimo', 'ouvidoria', 'whistleblowing', 'integrity', 'report'],
    pt: 'O canal de integridade aceita relatos anônimos, sem registro de IP, com protocolo para acompanhar. Para relatar algo sobre a EBAEM, use o [Canal de Integridade](/compliance/#canal) ou ouvidoria@ebaem.com.br. Na sua intranet, o mesmo recurso fica disponível para seus colaboradores.',
    en: 'The integrity channel accepts anonymous reports, without IP logging, with a ticket number for follow-up. To report something about EBAEM, use the [Integrity Channel](/compliance/#canal) or ouvidoria@ebaem.com.br. In your intranet, the same feature is available to your employees.',
    es: 'El canal de integridad acepta reportes anónimos, sin registro de IP, con protocolo para seguimiento. Para reportar algo sobre EBAEM, usa el [Canal de Integridad](/compliance/#canal) u ouvidoria@ebaem.com.br. En tu intranet, el mismo recurso está disponible para tus colaboradores.' },
  { k: ['wordpress', 'requisito', 'requisitos', 'php', 'instalar', 'instalacao', 'plugin', 'install', 'requirements'],
    pt: 'O Alicerce360 é um plugin para WordPress 6.6+ com PHP 8.2+ e MySQL 8 / MariaDB 10.6+, pensado para rodar até em hospedagem compartilhada cPanel. Você pode usar a nossa nuvem gerenciada ou instalar no seu servidor com licença. [Ver planos](/planos/).',
    en: 'Alicerce360 is a plugin for WordPress 6.6+ with PHP 8.2+ and MySQL 8 / MariaDB 10.6+, designed to run even on shared cPanel hosting. You can use our managed cloud or install it on your own server with a license. [See plans](/planos/).',
    es: 'Alicerce360 es un plugin para WordPress 6.6+ con PHP 8.2+ y MySQL 8 / MariaDB 10.6+, pensado para funcionar incluso en hosting compartido cPanel. Puedes usar nuestra nube gestionada o instalarlo en tu servidor con licencia. [Ver planes](/planos/).' },
  { k: ['implantacao', 'prazo', 'quanto tempo', 'onboarding', 'setup', 'implantar', 'implementation', 'implementacion'],
    pt: 'A implantação é guiada por um assistente: marca, módulos, login, estrutura, canais e políticas a partir de modelos. Um ambiente básico fica pronto em poucos dias, com o método de implantação da EBAEM. [Como funciona](/intranet/#implantacao).',
    en: 'Setup is guided by a wizard: branding, modules, login, structure, channels and policies from templates. A basic environment is ready in a few days, following EBAEM’s implementation method. [How it works](/intranet/#implantacao).',
    es: 'La implementación es guiada por un asistente: marca, módulos, inicio de sesión, estructura, canales y políticas a partir de plantillas. Un entorno básico queda listo en pocos días, con el método de implementación de EBAEM. [Cómo funciona](/intranet/#implantacao).' },
  { k: ['workplace', 'meta', 'sharepoint', 'migrar', 'migracao', 'outline', 'notion', 'migration', 'migracion'],
    pt: 'O Workplace da Meta foi encerrado em 01/06/2026 — o Alicerce360 é uma casa nova, com feed, grupos e chat, e seus dados ficam com você. Também importamos bases do Outline e ajudamos na migração de conteúdos. [Fale com a gente](/contato/).',
    en: 'Meta’s Workplace shut down on 1 June 2026 — Alicerce360 is a new home with feed, groups and chat, and you keep your data. We also import Outline knowledge bases and help migrate content. [Talk to us](/contato/).',
    es: 'Workplace de Meta cerró el 01/06/2026: Alicerce360 es un nuevo hogar, con feed, grupos y chat, y tus datos quedan contigo. También importamos bases de Outline y ayudamos a migrar contenidos. [Habla con nosotros](/contato/).' },
  { k: ['modulo', 'modulos', 'recurso', 'recursos', 'funcionalidade', 'funcionalidades', 'feature', 'features', 'funciones'],
    pt: 'São 35 módulos em evolução: comunicação (feed, avisos, e-mails), políticas com aceite, canais de Compliance e LGPD, documentos, treinamentos com certificado QR, pesquisas, Kanban, CRM, reembolsos, atestados técnicos, vagas e banco de talentos, entre outros. [Ver todos](/intranet/#modulos) e o [tour de telas](/telas/).',
    en: 'There are 35 evolving modules: communication (feed, announcements, emails), policies with acknowledgement, Compliance and LGPD channels, documents, training with QR certificates, surveys, Kanban, CRM, expense claims, technical certificates, jobs and talent pool, and more. [See all](/intranet/#modulos) and the [screen tour](/telas/).',
    es: 'Son 35 módulos en evolución: comunicación (feed, avisos, correos), políticas con aceptación, canales de Compliance y LGPD, documentos, capacitaciones con certificado QR, encuestas, Kanban, CRM, reembolsos, certificados técnicos, vacantes y banco de talentos, entre otros. [Ver todos](/intranet/#modulos) y el [tour de pantallas](/telas/).' },
  { k: ['treinamento', 'curso', 'certificado', 'lms', 'quiz', 'prova', 'training', 'course', 'capacitacion'],
    pt: 'Os treinamentos têm regras de progressão (sequência, quiz entre módulos, prova final, pesquisa de reação) e emitem certificado com QR Code verificável publicamente — evidência pronta para ISO 9001. [Ver a tela](/telas/#treinamentos).',
    en: 'Training courses have progression rules (sequence, quizzes between modules, final exam, reaction survey) and issue certificates with a publicly verifiable QR code — evidence ready for ISO 9001. [See the screen](/telas/#treinamentos).',
    es: 'Las capacitaciones tienen reglas de progresión (secuencia, quiz entre módulos, examen final, encuesta de reacción) y emiten certificado con código QR verificable públicamente: evidencia lista para ISO 9001. [Ver la pantalla](/telas/#treinamentos).' },
  { k: ['libras', 'acessibilidade', 'acessivel', 'deficiencia', 'accessibility', 'accesibilidad', 'contraste'],
    pt: 'Este site tem VLibras (tradução em Libras), painel de acessibilidade (contraste, fonte legível, régua de leitura, pausar animações, leitura em voz alta) e navegação por teclado. A intranet segue a meta WCAG 2.2 AA. [Declaração de acessibilidade](/acessibilidade/).',
    en: 'This website has VLibras (Brazilian Sign Language), an accessibility panel (contrast, readable font, reading guide, pause animations, read aloud) and keyboard navigation. The intranet targets WCAG 2.2 AA. [Accessibility statement](/acessibilidade/).',
    es: 'Este sitio tiene VLibras (lengua de señas brasileña), panel de accesibilidad (contraste, fuente legible, guía de lectura, pausar animaciones, lectura en voz alta) y navegación por teclado. La intranet sigue la meta WCAG 2.2 AA. [Declaración de accesibilidad](/acessibilidade/).' },
  { k: ['contato', 'humano', 'pessoa', 'atendente', 'especialista', 'telefone', 'whatsapp', 'falar', 'human', 'person', 'contact', 'contacto', 'persona'],
    pt: 'Claro! Fale com a equipe da EBAEM pelo [WhatsApp]({wa}), pelo telefone (61) 98128-6479 ou pelo e-mail contato@ebaem.com.br — de segunda a sexta, das 8h às 18h (Brasília). [Página de contato](/contato/).',
    en: 'Of course! Reach the EBAEM team via [WhatsApp]({wa}), phone +55 61 98128-6479 or contato@ebaem.com.br — Monday to Friday, 8am to 6pm (Brasília time). [Contact page](/contato/).',
    es: '¡Claro! Habla con el equipo de EBAEM por [WhatsApp]({wa}), por teléfono +55 61 98128-6479 o por correo contato@ebaem.com.br, de lunes a viernes de 8 a 18 h (hora de Brasilia). [Página de contacto](/contato/).' },
  { k: ['ebaem', 'fabricante', 'empresa', 'quem', 'sobre', 'about', 'company', 'quienes'],
    pt: 'O Alicerce360 é desenvolvido, licenciado e usado pela EBAEM — Empresa Brasileira de Assessoria Executiva e Multidisciplinar, de Brasília, especialista em governança, LGPD, compliance e normas ISO. A própria EBAEM é a primeira cliente. [Conheça](/sobre/).',
    en: 'Alicerce360 is developed, licensed and used by EBAEM — a Brasília-based executive and multidisciplinary advisory firm specialized in governance, data protection, compliance and ISO standards. EBAEM itself is the first customer. [Learn more](/sobre/).',
    es: 'Alicerce360 es desarrollado, licenciado y usado por EBAEM, empresa de asesoría ejecutiva y multidisciplinaria de Brasilia, especialista en gobernanza, protección de datos, compliance y normas ISO. La propia EBAEM es la primera clienta. [Conoce más](/sobre/).' },
  { k: ['roadmap', 'disponivel', 'pronto', 'quando', 'fase', 'versao', 'available', 'when', 'disponible'],
    pt: 'Somos transparentes: a Fundação (núcleo, licenças e auditoria) já está pronta e os módulos chegam em fases ao longo do roadmap. Clientes fundadores ajudam a priorizar e têm condições especiais. [Ver roadmap](/intranet/#roadmap).',
    en: 'We are transparent: the Foundation (core, licensing and audit) is ready and modules arrive in phases along the roadmap. Founding customers help prioritize and get special terms. [See roadmap](/intranet/#roadmap).',
    es: 'Somos transparentes: la Fundación (núcleo, licencias y auditoría) ya está lista y los módulos llegan por fases a lo largo del roadmap. Los clientes fundadores ayudan a priorizar y tienen condiciones especiales. [Ver roadmap](/intranet/#roadmap).' },
  { k: ['cancelar', 'cancelamento', 'reembolso', 'arrependimento', 'fidelidade', 'contrato', 'cancel', 'refund', 'cancelacion'],
    pt: 'No plano mensal não há fidelidade. Compras on-line por consumidor têm 7 dias de arrependimento (CDC, art. 49). Ao encerrar, você exporta seus dados — nada é apagado sem aviso. Regras completas na [Política de Comercialização](/politica-comercial/).',
    en: 'Monthly plans have no lock-in. Online consumer purchases have a 7-day cooling-off period (Brazilian Consumer Code, art. 49). When you leave, you export your data — nothing is deleted without notice. Full rules in the [Sales Policy](/politica-comercial/).',
    es: 'En el plan mensual no hay permanencia. Las compras en línea de consumidores tienen 7 días de desistimiento (Código de Defensa del Consumidor de Brasil, art. 49). Al terminar, exportas tus datos: nada se borra sin aviso. Reglas completas en la [Política de Comercialización](/politica-comercial/).' },
  { k: ['dados', 'onde ficam', 'propriedade', 'exportar', 'aprisionamento', 'lock-in', 'soberania', 'data', 'ownership'],
    pt: 'Seus dados são seus: ficam no seu WordPress (na nossa nuvem ou no seu servidor), sem aprisionamento, com exportação a qualquer momento. Mesmo com a licença vencida, a intranet fica em somente leitura para consulta e exportação.',
    en: 'Your data is yours: it lives in your WordPress (on our cloud or your server), with no lock-in and export at any time. Even with an expired license, the intranet stays read-only for viewing and exporting.',
    es: 'Tus datos son tuyos: están en tu WordPress (en nuestra nube o en tu servidor), sin dependencia y con exportación en cualquier momento. Incluso con la licencia vencida, la intranet queda en solo lectura para consulta y exportación.' },
  { k: ['marca', 'personalizar', 'template', 'templates', 'tema', 'cores', 'logo', 'brand', 'theme', 'plantilla'],
    pt: 'A intranet fica com a cara da sua empresa: 10 templates visuais (Corporativo, Social, Revista, Hub de Serviços, Qualidade & Compliance e outros), cores, logos, megamenu e modo escuro. Experimente trocar o template no [tour de telas](/telas/#templates).',
    en: 'The intranet carries your brand: 10 visual templates (Corporate, Social, Magazine, Service Hub, Quality & Compliance and more), colors, logos, mega menu and dark mode. Try switching templates in the [screen tour](/telas/#templates).',
    es: 'La intranet tiene la cara de tu empresa: 10 plantillas visuales (Corporativa, Social, Revista, Hub de Servicios, Calidad y Compliance y otras), colores, logos, megamenú y modo oscuro. Prueba cambiar la plantilla en el [tour de pantallas](/telas/#templates).' },
  { k: ['celular', 'mobile', 'app', 'aplicativo', 'pwa', 'android', 'iphone', 'movil'],
    pt: 'Funciona no celular como aplicativo (PWA), com notificações push, leitura de QR Code e foto de notas fiscais para reembolsos — sem precisar de loja de apps. [Ver a tela](/telas/#mobile).',
    en: 'It works on phones as an app (PWA), with push notifications, QR code scanning and receipt photos for expense claims — no app store needed. [See the screen](/telas/#mobile).',
    es: 'Funciona en el móvil como aplicación (PWA), con notificaciones push, lectura de códigos QR y foto de facturas para reembolsos, sin tienda de aplicaciones. [Ver la pantalla](/telas/#mobile).' },
  { k: ['indicar', 'indicacao', 'parceiro', 'parceria', 'revenda', 'comissao', 'referral', 'partner', 'reseller', 'socio'],
    pt: 'Indique uma empresa: quando ela vira cliente, você ganha benefícios (como mensalidade grátis) ou comissão recorrente, se for parceiro. [Programa de indicação](/clientes/#indique).',
    en: 'Refer a company: when it becomes a customer you get benefits (such as a free month) or recurring commission if you are a partner. [Referral program](/clientes/#indique).',
    es: 'Recomienda una empresa: cuando se convierte en cliente, obtienes beneficios (como una mensualidad gratis) o comisión recurrente si eres socio. [Programa de recomendación](/clientes/#indique).' }
];
