/* CoreCyber · textos gerados pelo JavaScript (PT, EN, ES).
   Textos das páginas ficam no HTML e em src/i18n/*.json. */
var CC_UI = {
  pt: {
    'skip': 'Pular para o conteúdo',
    'wa.default': 'Olá! Vim pelo site do CoreCyber e quero saber mais.',
    'toast.copied': 'Copiado para a área de transferência.',
    'lang.suggest': 'Este site também está disponível em {lang}.',
    'lang.switch': 'Mudar',
    'lang.keep': 'Manter português',
    'lang.name.en': 'inglês', 'lang.name.es': 'espanhol', 'lang.name.pt': 'português',
    'lang.changed': 'Idioma alterado para português.',
    /* FAB */
    'fab.label': 'Fale com a gente',
    'fab.open': 'Abrir opções de contato',
    'fab.close': 'Fechar opções de contato',
    'fab.wa': 'WhatsApp', 'fab.mail': 'E-mail', 'fab.tel': 'Ligar', 'fab.ai': 'Pergunte ao Cy (assistente)',
    'fab.ctt': 'Página de contato', 'fab.map': 'Como chegar', 'fab.ig': 'Instagram', 'fab.li': 'LinkedIn', 'fab.fb': 'Facebook',
    'totop': 'Voltar ao topo',
    /* doca */
    'dock.a11y': 'Acessibilidade', 'dock.cookie': 'Preferências de cookies', 'dock.libras': 'Tradução em Libras',
    /* acessibilidade */
    'a11y.title': 'Acessibilidade',
    'a11y.close': 'Fechar painel de acessibilidade',
    'a11y.text': 'Texto', 'a11y.colors': 'Cores e contraste', 'a11y.reading': 'Leitura e navegação', 'a11y.motion.h': 'Movimento e mídia',
    'a11y.size': 'Tamanho do texto', 'a11y.smaller': 'Diminuir texto', 'a11y.bigger': 'Aumentar texto',
    'a11y.contrast': 'Alto contraste', 'a11y.gray': 'Escala de cinza', 'a11y.links': 'Destacar links',
    'a11y.font': 'Fonte legível', 'a11y.spacing': 'Espaçar texto', 'a11y.guide': 'Régua de leitura',
    'a11y.cursor': 'Cursor ampliado', 'a11y.motion': 'Pausar animações', 'a11y.noimg': 'Ocultar imagens',
    'a11y.read': 'Ouvir a página', 'a11y.stop': 'Parar leitura', 'a11y.libras': 'Libras (VLibras)',
    'a11y.reset': 'Restaurar padrão', 'a11y.statement': 'Declaração de acessibilidade',
    'a11y.keys': 'Atalhos de teclado',
    'a11y.k1': 'ir para o conteúdo', 'a11y.k2': 'ir para o menu', 'a11y.k3': 'ir para o rodapé', 'a11y.k4': 'abrir este painel',
    'a11y.on': 'ativado', 'a11y.off': 'desativado',
    'a11y.noread': 'Seu navegador não oferece leitura em voz alta.',
    /* cookies */
    'ck.title': 'Sua privacidade, suas regras',
    'ck.text': 'Somos uma empresa de segurança: usamos só o essencial para o site funcionar e lembrar suas escolhas. Recursos opcionais (mapa incorporado e assistente com IA) só são ativados com a sua permissão. Nada de rastreadores de anúncios. Você pode mudar de ideia quando quiser.',
    'ck.policy': 'Política de Cookies',
    'ck.accept': 'Aceitar todos', 'ck.reject': 'Rejeitar opcionais', 'ck.custom': 'Personalizar',
    'ck.save': 'Salvar minhas escolhas', 'ck.prefs': 'Preferências de privacidade',
    'ck.intro': 'Escolha quais categorias podem ser usadas. Categorias essenciais não podem ser desligadas porque o site não funciona sem elas. Sua escolha fica registrada com um identificador anônimo e vale por 12 meses.',
    'ck.always': 'Sempre ativos', 'ck.details': 'Ver detalhes', 'ck.none': 'Nenhum em uso no momento. Nada será ativado sem a sua permissão.',
    'ck.name': 'Nome', 'ck.purpose': 'Finalidade', 'ck.duration': 'Duração',
    'ck.id': 'ID do consentimento', 'ck.date': 'Registrado em', 'ck.saved': 'Preferências de privacidade salvas.',
    'ck.close': 'Fechar',
    'ck.c.necessary': 'Essenciais', 'ck.d.necessary': 'Garantem segurança, navegação, registro do seu consentimento e as preferências que você pedir (idioma e acessibilidade). Também carregamos o VLibras, ferramenta pública de acessibilidade do Governo Federal.',
    'ck.c.functional': 'Funcionais', 'ck.d.functional': 'Ativam conteúdos de terceiros que você escolhe usar, como o mapa do Google na página de contato e o assistente Cy com inteligência artificial.',
    'ck.c.analytics': 'Estatísticas', 'ck.d.analytics': 'Medição de audiência para melhorar o site, com dados agregados.',
    'ck.c.marketing': 'Marketing', 'ck.d.marketing': 'Anúncios e remarketing.',
    'ck.i.consent': 'Guarda sua escolha de privacidade', 'ck.i.lang': 'Lembra o idioma escolhido', 'ck.i.a11y': 'Lembra suas preferências de acessibilidade',
    'ck.i.mascot': 'Lembra se você minimizou o mascote', 'ck.i.vlibras': 'Tradução para Libras (Governo Federal)', 'ck.i.maps': 'Mapa incorporado (Google)', 'ck.i.ai': 'Envio das perguntas ao servidor de IA',
    'ck.12m': '12 meses', 'ck.persist': 'Até você limpar o navegador', 'ck.session': 'Sessão', 'ck.third': 'Definida pelo terceiro',
    /* mascote */
    'm.hello': 'Oi! Eu sou o Cy, o sentinela do CoreCyber. Role a página que eu vou vigiando junto!',
    'm.idle': 'Ficou com alguma dúvida? Clique em mim e pergunte.',
    'm.fast': 'Opa, que velocidade! Detectei muita coisa boa no caminho…',
    'm.sleep': 'Zzz… sentinela em modo econômico. Clique para me acordar.',
    'm.top': 'De volta ao topo! Quer ver o que a internet sabe sobre a sua empresa?',
    'm.bottom': 'Varredura da página concluída: zero ameaças! Que tal falar com um especialista?',
    'm.hide': 'Esconder o mascote', 'm.show': 'Mostrar o mascote Cy', 'm.ask': 'Pergunte ao Cy',
    'm.dns.good': 'Boa! Seu e-mail está bem protegido. O diagnóstico completo olha muito mais.',
    'm.dns.bad': 'Hmm… encontrei pontos de atenção. Quer que a equipe olhe com calma?',
    /* chat */
    'ch.title': 'Cy · Assistente CoreCyber',
    'ch.local': 'Base de conhecimento', 'ch.ai': 'IA conectada (FreeLLMAPI)',
    'ch.greet': 'Olá! Sou o Cy. Posso explicar o que o CoreCyber faz, planos, diagnóstico gratuito, LGPD e o que está no roadmap — ou te levar a um especialista humano. Como posso ajudar?',
    'ch.ph': 'Escreva sua pergunta…', 'ch.send': 'Enviar pergunta', 'ch.close': 'Fechar assistente',
    'ch.note': 'Não envie senhas nem dados pessoais sensíveis. Respostas automáticas podem conter imprecisões: confirme com nossa equipe.',
    'ch.fallback': 'Ainda não sei responder isso com segurança. Prefere falar com uma pessoa? [Chamar no WhatsApp]({wa}) ou [enviar mensagem](/contato/).',
    'ch.err': 'Não consegui consultar a IA agora, então respondi pela base local.',
    'ch.consent': 'Para usar a IA, suas perguntas serão enviadas ao nosso servidor de IA. Ative a categoria "Funcionais" nas preferências de cookies ou continue com as respostas da base local.',
    'ch.s1': 'Quanto custa?', 'ch.s2': 'Diagnóstico gratuito', 'ch.s3': 'O que o agente coleta?', 'ch.s4': 'Tem SIEM e EDR?', 'ch.s5': 'Falar com uma pessoa',
    /* planos */
    'plan.essencial': 'Essencial', 'plan.profissional': 'Profissional', 'plan.avancado': 'Avançado',
    'pr.month': '/mês', 'pr.upto': 'até {n} ativos', 'pr.perasset': '≈ {v} por ativo/mês',
    'pr.yearly': '{v} cobrados por ano · você economiza {s}', 'pr.monthly': 'Cobrança mensal, sem fidelidade',
    'pr.dedicated': 'Instância dedicada (nuvem privada) — sob confirmação técnica', 'pr.cloud': 'Nuvem CoreCyber gerenciada pela EBAEM, com atualizações inclusas',
    'pr.big': 'Mais de 500 ativos? Temos proposta sob medida.',
    'pr.choose': 'Quero o plano {p}', 'pr.msg': 'Olá! Tenho interesse no plano {p} do CoreCyber ({u}, {b}, {h}). Podem me enviar uma proposta?',
    'pr.b.m': 'cobrança mensal', 'pr.b.y': 'cobrança anual', 'pr.h.cloud': 'na nuvem CoreCyber', 'pr.h.ded': 'em instância dedicada',
    /* simulador */
    'sim.assets': '{n} ativos', 'sim.factor': '{p}% do preço de referência',
    'sim.save': 'de economia estimada em 12 meses', 'sim.pct': '{p}% a menos do que montar a pilha com ferramentas separadas',
    'sim.plan': 'CoreCyber {p} (anual)',
    'sim.pick': 'Marque ao menos uma ferramenta que você compraria separadamente.',
    'sim.more': 'Acima de 500 ativos o valor do CoreCyber é estimado proporcionalmente; peça proposta sob medida.',
    'sim.roadmap': 'Atenção: SIEM e EDR completo estão no roadmap do CoreCyber. Hoje o plano Avançado entrega monitoração por agente, conformidade e correlação — compare com esse cuidado.',
    'sim.none': 'Nessa combinação o valor é parecido — o ganho está em um só painel, um só idioma e um só contrato.',
    /* formulários */
    'f.required': 'Preencha este campo.', 'f.email': 'Informe um e-mail válido.', 'f.consent': 'Para continuar, marque a caixa de concordância.',
    'f.ok.wa': 'Pronto! Abrimos o WhatsApp com sua mensagem preenchida. Protocolo de referência: {p}.',
    'f.ok.mail': 'Pronto! Abrimos seu aplicativo de e-mail com a mensagem preenchida. Protocolo de referência: {p}.',
    'f.ok.hint': 'Se nada abriu, escreva para {m} informando o protocolo.',
    'f.subject': 'CoreCyber · {t} · {p}', 'f.proto': 'Protocolo',
    'f.t.contact': 'Contato', 'f.t.titular': 'Solicitação de titular (LGPD)', 'f.t.integrity': 'Relato de integridade', 'f.t.referral': 'Indicação de cliente',
    'f.t.diagnostic': 'Diagnóstico gratuito de exposição', 'f.t.poc': 'Prova de conceito de 30 dias', 'f.t.partner': 'Parceria / MSSP', 'f.t.disclosure': 'Relato de vulnerabilidade', 'f.t.demo': 'Demonstração guiada',
    /* verificação de DNS */
    'dns.invalid': 'Digite um domínio válido, por exemplo: suaempresa.com.br',
    'dns.wait': 'Consultando o DNS público de {d}…',
    'dns.fail': 'Não foi possível consultar o DNS público agora. Tente de novo em instantes ou peça o diagnóstico completo.',
    'dns.nx': 'O domínio {d} não foi encontrado no DNS. Confira a grafia.',
    'dns.title': 'Proteção de e-mail e DNS de {d}',
    'dns.sub': 'Leitura de registros públicos, sem tocar nos seus servidores.',
    'dns.spf.none': 'Sem SPF: qualquer servidor pode tentar enviar e-mail em nome do seu domínio.',
    'dns.spf.multi': 'Há mais de um registro SPF — isso invalida a verificação. Mantenha apenas um.',
    'dns.spf.soft': 'SPF permissivo (+all ou ?all) — proteção fraca contra falsificação.',
    'dns.spf.ok': 'SPF publicado e restritivo.',
    'dns.dmarc.none': 'Sem DMARC: e-mails falsos com o seu domínio podem chegar às caixas de entrada.',
    'dns.dmarc.none.p': 'DMARC em modo apenas monitoramento (p=none): falsificações ainda são entregues.',
    'dns.dmarc.ok': 'DMARC ativo com política {p}.',
    'dns.sec.ok': 'DNSSEC validado: respostas do DNS assinadas.',
    'dns.sec.no': 'Sem DNSSEC validado: respostas do DNS podem ser forjadas no caminho.',
    'dns.caa.ok': 'CAA publicado: só autoridades autorizadas emitem certificados.',
    'dns.caa.no': 'Sem CAA: qualquer autoridade certificadora pode emitir certificado para o domínio.',
    'dns.mx.ok': '{n} servidor(es) de e-mail encontrados.',
    'dns.mx.no': 'Nenhum servidor de e-mail (MX) — normal se o domínio não recebe e-mails.',
    'dns.sts.ok': 'MTA-STS publicado: entrega de e-mail exige criptografia.',
    'dns.sts.no': 'Sem MTA-STS (recomendado para quem recebe e-mail).',
    'dns.rpt.ok': 'TLS-RPT publicado: você recebe relatórios de falhas de criptografia.',
    'dns.rpt.no': 'Sem TLS-RPT (opcional, ajuda a detectar ataques à entrega de e-mail).',
    'dns.more': 'Isso é só a superfície da superfície. O diagnóstico completo do CoreCyber verifica portas, TLS, cabeçalhos, subdomínios esquecidos e exposições conhecidas.',
    'dns.cta': 'Quero o diagnóstico completo',
    'dns.note': 'A consulta foi feita pelo seu navegador diretamente ao DNS público do Google (com o da Cloudflare como reserva). A EBAEM não recebe o domínio digitado.',
    /* demonstrações */
    'demo.ok': 'Feito! (demonstração)',
    'demo.scan.run': 'Varrendo…', 'demo.scan.done': 'Concluída às {h}',
    'demo.scan.toast': 'Varredura concluída — achados novos: {n} · resolvidos desde a última execução: {r}.',
    'demo.cycle': 'Status atualizado: {s}. Registrado na linha do tempo.',
    'demo.soar': 'Regra testada: caso CASE-2026-{n} aberto e alerta enviado ao Telegram.',
    'demo.qr': 'Documento autêntico · protocolo REL-2026-0{n} · conferido às {h}.',
    'demo.glpi': 'Chamado GLPI #{n} aberto automaticamente e vinculado ao caso.',
    'demo.decom': 'Certificado de descomissionamento DSC-2026-{n} emitido com QR.',
    'demo.export': 'Exportação gerada (exemplo de demonstração).',
    'demo.status': 'Status page atualizada para o público às {h}.',
    'demo.agent': 'Correção enviada. A pessoa na máquina pode aceitar ou recusar.',
    'st.open': 'Aberta', 'st.fixing': 'Em correção', 'st.fixed': 'Corrigida', 'st.validated': 'Validada no reteste',
    'st.pending': 'Pendente', 'st.waiting': 'Aguardando aceite na máquina', 'st.applied': 'Aplicada',
    'st.draft': 'Rascunho', 'st.review': 'Em revisão', 'st.approved': 'Aprovada · PDF com QR',
    'st.c.open': 'Aberto', 'st.c.inv': 'Investigando', 'st.c.cont': 'Contido', 'st.c.res': 'Resolvido', 'st.c.closed': 'Fechado',
    'st.up': 'Operacional', 'st.maint': 'Em manutenção (1 h)', 'st.accepted': 'Risco aceito com justificativa',
    'map.load': 'Carregar mapa',
    'reveal.touch': 'Toque para revelar',
    /* papel 3D */
    'p.off': 'Câmera desligada', 'p.loading': 'Carregando detector de mãos…', 'p.show': 'Mostre a palma da mão para a câmera',
    'p.hand': 'Mão detectada: abra para desamassar, feche para amassar', 'p.nocam': 'Câmera indisponível — use o controle deslizante ou arraste',
    'p.done': 'Desamassado! Risco priorizado, evidência verificável.', 'p.drag': 'Arraste para cima para desamassar', 'p.camoff': 'Desligar câmera', 'p.camon': 'Ativar câmera',
    'p.par': 'Mova o mouse (ou incline o celular) e veja a profundidade real', 'p.gyro': 'Ativar inclinação do celular',
    'p.doc1': 'RELATÓRIO DE PENTEST', 'p.doc2': 'Versão impressa · 2023', 'p.doc3': 'DESATUALIZADO', 'p.doc4': '240 páginas. Quem corrigiu o quê?',
    'p.ok1': 'LAUDO DE EXPOSIÇÃO', 'p.ok2': 'CoreCyber · atualizado agora', 'p.ok3': 'Risco 82 → 41 em 30 dias', 'p.ok4': 'Autêntico: QR verificável',
    'p.note': 'Trocar a senha do firewall!!', 'p.oldh': 'PLANILHA DE CVEs', 'p.old': 'vulns_v7_FINAL_agora_vai.xlsx',
    'g.br': 'Sua empresa'
  },
  en: {
    'skip': 'Skip to content',
    'wa.default': 'Hi! I found you on the CoreCyber website and would like to know more.',
    'toast.copied': 'Copied to clipboard.',
    'lang.suggest': 'This website is also available in {lang}.',
    'lang.switch': 'Switch', 'lang.keep': 'Keep Portuguese',
    'lang.name.en': 'English', 'lang.name.es': 'Spanish', 'lang.name.pt': 'Portuguese',
    'lang.changed': 'Language changed to English.',
    'fab.label': 'Talk to us', 'fab.open': 'Open contact options', 'fab.close': 'Close contact options',
    'fab.wa': 'WhatsApp', 'fab.mail': 'Email', 'fab.tel': 'Call us', 'fab.ai': 'Ask Cy (assistant)',
    'fab.ctt': 'Contact page', 'fab.map': 'Directions', 'fab.ig': 'Instagram', 'fab.li': 'LinkedIn', 'fab.fb': 'Facebook',
    'totop': 'Back to top',
    'dock.a11y': 'Accessibility', 'dock.cookie': 'Cookie preferences', 'dock.libras': 'Brazilian Sign Language (Libras)',
    'a11y.title': 'Accessibility', 'a11y.close': 'Close accessibility panel',
    'a11y.text': 'Text', 'a11y.colors': 'Colors and contrast', 'a11y.reading': 'Reading and navigation', 'a11y.motion.h': 'Motion and media',
    'a11y.size': 'Text size', 'a11y.smaller': 'Decrease text', 'a11y.bigger': 'Increase text',
    'a11y.contrast': 'High contrast', 'a11y.gray': 'Grayscale', 'a11y.links': 'Highlight links',
    'a11y.font': 'Readable font', 'a11y.spacing': 'Text spacing', 'a11y.guide': 'Reading guide',
    'a11y.cursor': 'Large cursor', 'a11y.motion': 'Pause animations', 'a11y.noimg': 'Hide images',
    'a11y.read': 'Read page aloud', 'a11y.stop': 'Stop reading', 'a11y.libras': 'Libras (VLibras)',
    'a11y.reset': 'Reset', 'a11y.statement': 'Accessibility statement',
    'a11y.keys': 'Keyboard shortcuts',
    'a11y.k1': 'go to content', 'a11y.k2': 'go to menu', 'a11y.k3': 'go to footer', 'a11y.k4': 'open this panel',
    'a11y.on': 'on', 'a11y.off': 'off', 'a11y.noread': 'Your browser does not support text-to-speech.',
    'ck.title': 'Your privacy, your rules',
    'ck.text': 'We are a security company: we only use what is essential for the website to work and remember your choices. Optional features (embedded map and AI assistant) are only enabled with your permission. No ad trackers. You can change your mind at any time.',
    'ck.policy': 'Cookie Policy',
    'ck.accept': 'Accept all', 'ck.reject': 'Reject optional', 'ck.custom': 'Customize',
    'ck.save': 'Save my choices', 'ck.prefs': 'Privacy preferences',
    'ck.intro': 'Choose which categories may be used. Essential categories cannot be turned off because the website does not work without them. Your choice is recorded with an anonymous identifier and is valid for 12 months.',
    'ck.always': 'Always on', 'ck.details': 'See details', 'ck.none': 'None in use at the moment. Nothing will be enabled without your permission.',
    'ck.name': 'Name', 'ck.purpose': 'Purpose', 'ck.duration': 'Duration',
    'ck.id': 'Consent ID', 'ck.date': 'Recorded on', 'ck.saved': 'Privacy preferences saved.', 'ck.close': 'Close',
    'ck.c.necessary': 'Essential', 'ck.d.necessary': 'Ensure security, navigation, the record of your consent and the preferences you request (language and accessibility). We also load VLibras, the Brazilian Federal Government public accessibility tool.',
    'ck.c.functional': 'Functional', 'ck.d.functional': 'Enable third-party content you choose to use, such as the Google map on the contact page and the Cy AI assistant.',
    'ck.c.analytics': 'Statistics', 'ck.d.analytics': 'Audience measurement to improve the website, using aggregated data.',
    'ck.c.marketing': 'Marketing', 'ck.d.marketing': 'Ads and remarketing.',
    'ck.i.consent': 'Stores your privacy choice', 'ck.i.lang': 'Remembers the chosen language', 'ck.i.a11y': 'Remembers your accessibility preferences',
    'ck.i.mascot': 'Remembers whether you minimized the mascot', 'ck.i.vlibras': 'Libras translation (Federal Government)', 'ck.i.maps': 'Embedded map (Google)', 'ck.i.ai': 'Sends your questions to the AI server',
    'ck.12m': '12 months', 'ck.persist': 'Until you clear your browser', 'ck.session': 'Session', 'ck.third': 'Set by the third party',
    'm.hello': "Hi! I'm Cy, the CoreCyber sentinel. Scroll down and I'll keep watch along the way!",
    'm.idle': 'Got a question? Click me and ask.',
    'm.fast': 'Whoa, what speed! I detected lots of good stuff along the way…',
    'm.sleep': 'Zzz… sentinel in power-saving mode. Click to wake me up.',
    'm.top': 'Back to the top! Want to see what the internet knows about your company?',
    'm.bottom': 'Page scan complete: zero threats! How about talking to a specialist?',
    'm.hide': 'Hide the mascot', 'm.show': 'Show Cy the mascot', 'm.ask': 'Ask Cy',
    'm.dns.good': 'Nice! Your email is well protected. The full assessment looks at much more.',
    'm.dns.bad': 'Hmm… I found some points of attention. Want our team to take a closer look?',
    'ch.title': 'Cy · CoreCyber Assistant', 'ch.local': 'Knowledge base', 'ch.ai': 'AI connected (FreeLLMAPI)',
    'ch.greet': "Hello! I'm Cy. I can explain what CoreCyber does, plans, the free assessment, data protection and what is on the roadmap — or connect you with a human specialist. How can I help?",
    'ch.ph': 'Type your question…', 'ch.send': 'Send question', 'ch.close': 'Close assistant',
    'ch.note': 'Do not share passwords or sensitive personal data. Automated answers may contain inaccuracies: please confirm with our team.',
    'ch.fallback': "I can't answer that reliably yet. Would you rather talk to a person? [Chat on WhatsApp]({wa}) or [send a message](/contato/).",
    'ch.err': "I couldn't reach the AI right now, so I answered from the local knowledge base.",
    'ch.consent': 'To use AI, your questions will be sent to our AI server. Enable the "Functional" category in cookie preferences or keep using knowledge-base answers.',
    'ch.s1': 'How much is it?', 'ch.s2': 'Free assessment', 'ch.s3': 'What does the agent collect?', 'ch.s4': 'Is there SIEM and EDR?', 'ch.s5': 'Talk to a person',
    'plan.essencial': 'Essential', 'plan.profissional': 'Professional', 'plan.avancado': 'Advanced',
    'pr.month': '/month', 'pr.upto': 'up to {n} assets', 'pr.perasset': '≈ {v} per asset/month',
    'pr.yearly': '{v} billed yearly · you save {s}', 'pr.monthly': 'Monthly billing, no lock-in',
    'pr.dedicated': 'Dedicated instance (private cloud) — subject to technical confirmation', 'pr.cloud': 'CoreCyber cloud managed by EBAEM, updates included',
    'pr.big': 'More than 500 assets? We have a tailored proposal.',
    'pr.choose': 'I want the {p} plan', 'pr.msg': 'Hi! I am interested in the CoreCyber {p} plan ({u}, {b}, {h}). Could you send me a proposal?',
    'pr.b.m': 'monthly billing', 'pr.b.y': 'yearly billing', 'pr.h.cloud': 'on the CoreCyber cloud', 'pr.h.ded': 'on a dedicated instance',
    'sim.assets': '{n} assets', 'sim.factor': '{p}% of the reference price',
    'sim.save': 'estimated savings over 12 months', 'sim.pct': '{p}% less than building the stack with separate tools',
    'sim.plan': 'CoreCyber {p} (yearly)',
    'sim.pick': 'Tick at least one tool you would buy separately.',
    'sim.more': 'Above 500 assets the CoreCyber price is estimated proportionally; ask for a tailored proposal.',
    'sim.roadmap': 'Note: SIEM and full EDR are on the CoreCyber roadmap. Today the Advanced plan delivers agent-based monitoring, compliance and correlation — compare with that in mind.',
    'sim.none': 'With this combination the price is similar — the gain is one console, one language and one contract.',
    'f.required': 'Please fill in this field.', 'f.email': 'Please enter a valid email.', 'f.consent': 'To continue, please tick the consent box.',
    'f.ok.wa': 'Done! We opened WhatsApp with your message filled in. Reference number: {p}.',
    'f.ok.mail': 'Done! We opened your email app with the message filled in. Reference number: {p}.',
    'f.ok.hint': 'If nothing opened, write to {m} quoting the reference number.',
    'f.subject': 'CoreCyber · {t} · {p}', 'f.proto': 'Reference',
    'f.t.contact': 'Contact', 'f.t.titular': 'Data subject request (LGPD)', 'f.t.integrity': 'Integrity report', 'f.t.referral': 'Customer referral',
    'f.t.diagnostic': 'Free exposure assessment', 'f.t.poc': '30-day proof of concept', 'f.t.partner': 'Partnership / MSSP', 'f.t.disclosure': 'Vulnerability report', 'f.t.demo': 'Guided demo',
    'dns.invalid': 'Type a valid domain, for example: yourcompany.com',
    'dns.wait': 'Querying public DNS for {d}…',
    'dns.fail': 'We could not query public DNS right now. Try again shortly or request the full assessment.',
    'dns.nx': 'The domain {d} was not found in DNS. Please check the spelling.',
    'dns.title': 'Email and DNS protection for {d}',
    'dns.sub': 'Reading public records, without touching your servers.',
    'dns.spf.none': 'No SPF: any server can try to send email on behalf of your domain.',
    'dns.spf.multi': 'There is more than one SPF record — that breaks verification. Keep only one.',
    'dns.spf.soft': 'Permissive SPF (+all or ?all) — weak protection against spoofing.',
    'dns.spf.ok': 'SPF published and restrictive.',
    'dns.dmarc.none': 'No DMARC: spoofed emails using your domain may reach inboxes.',
    'dns.dmarc.none.p': 'DMARC in monitoring-only mode (p=none): spoofed messages are still delivered.',
    'dns.dmarc.ok': 'DMARC active with policy {p}.',
    'dns.sec.ok': 'DNSSEC validated: DNS answers are signed.',
    'dns.sec.no': 'No validated DNSSEC: DNS answers could be forged in transit.',
    'dns.caa.ok': 'CAA published: only authorized authorities may issue certificates.',
    'dns.caa.no': 'No CAA: any certificate authority may issue certificates for the domain.',
    'dns.mx.ok': '{n} mail server(s) found.',
    'dns.mx.no': 'No mail server (MX) — normal if the domain does not receive email.',
    'dns.sts.ok': 'MTA-STS published: email delivery requires encryption.',
    'dns.sts.no': 'No MTA-STS (recommended for domains that receive email).',
    'dns.rpt.ok': 'TLS-RPT published: you receive reports about encryption failures.',
    'dns.rpt.no': 'No TLS-RPT (optional, helps detect attacks on email delivery).',
    'dns.more': 'This is only the surface of the surface. The full CoreCyber assessment checks ports, TLS, headers, forgotten subdomains and known exposures.',
    'dns.cta': 'I want the full assessment',
    'dns.note': 'The query was made by your browser directly to Google Public DNS (with Cloudflare as a fallback). EBAEM does not receive the domain you typed.',
    'demo.ok': 'Done! (demo)',
    'demo.scan.run': 'Scanning…', 'demo.scan.done': 'Finished at {h}',
    'demo.scan.toast': 'Scan finished — new findings: {n} · resolved since the last run: {r}.',
    'demo.cycle': 'Status updated: {s}. Recorded on the timeline.',
    'demo.soar': 'Rule tested: case CASE-2026-{n} opened and alert sent to Telegram.',
    'demo.qr': 'Authentic document · reference REL-2026-0{n} · checked at {h}.',
    'demo.glpi': 'GLPI ticket #{n} opened automatically and linked to the case.',
    'demo.decom': 'Decommissioning certificate DSC-2026-{n} issued with QR.',
    'demo.export': 'Export generated (demo example).',
    'demo.status': 'Public status page updated at {h}.',
    'demo.agent': 'Fix sent. The person at the machine can accept or decline it.',
    'st.open': 'Open', 'st.fixing': 'Being fixed', 'st.fixed': 'Fixed', 'st.validated': 'Validated on retest',
    'st.pending': 'Pending', 'st.waiting': 'Awaiting approval on the device', 'st.applied': 'Applied',
    'st.draft': 'Draft', 'st.review': 'Under review', 'st.approved': 'Approved · PDF with QR',
    'st.c.open': 'Open', 'st.c.inv': 'Investigating', 'st.c.cont': 'Contained', 'st.c.res': 'Resolved', 'st.c.closed': 'Closed',
    'st.up': 'Operational', 'st.maint': 'Under maintenance (1 h)', 'st.accepted': 'Risk accepted with justification',
    'map.load': 'Load map', 'reveal.touch': 'Tap to reveal',
    'p.off': 'Camera off', 'p.loading': 'Loading hand detector…', 'p.show': 'Show your palm to the camera',
    'p.hand': 'Hand detected: open to smooth it out, close to crumple', 'p.nocam': 'Camera unavailable — use the slider or drag',
    'p.done': 'Smoothed out! Risk prioritized, verifiable evidence.', 'p.drag': 'Drag up to smooth out the paper', 'p.camoff': 'Turn camera off', 'p.camon': 'Turn camera on',
    'p.par': 'Move your mouse (or tilt your phone) to see real depth', 'p.gyro': 'Enable phone tilt',
    'p.doc1': 'PENTEST REPORT', 'p.doc2': 'Printed version · 2023', 'p.doc3': 'OUTDATED', 'p.doc4': '240 pages. Who fixed what?',
    'p.ok1': 'EXPOSURE REPORT', 'p.ok2': 'CoreCyber · updated now', 'p.ok3': 'Risk 82 → 41 in 30 days', 'p.ok4': 'Authentic: verifiable QR',
    'p.note': 'Change the firewall password!!', 'p.oldh': 'CVE SPREADSHEET', 'p.old': 'vulns_v7_FINAL_really.xlsx',
    'g.br': 'Your company'
  },
  es: {
    'skip': 'Saltar al contenido',
    'wa.default': '¡Hola! Vi el sitio de CoreCyber y quiero saber más.',
    'toast.copied': 'Copiado al portapapeles.',
    'lang.suggest': 'Este sitio también está disponible en {lang}.',
    'lang.switch': 'Cambiar', 'lang.keep': 'Mantener portugués',
    'lang.name.en': 'inglés', 'lang.name.es': 'español', 'lang.name.pt': 'portugués',
    'lang.changed': 'Idioma cambiado a español.',
    'fab.label': 'Hable con nosotros', 'fab.open': 'Abrir opciones de contacto', 'fab.close': 'Cerrar opciones de contacto',
    'fab.wa': 'WhatsApp', 'fab.mail': 'Correo', 'fab.tel': 'Llamar', 'fab.ai': 'Pregunte a Cy (asistente)',
    'fab.ctt': 'Página de contacto', 'fab.map': 'Cómo llegar', 'fab.ig': 'Instagram', 'fab.li': 'LinkedIn', 'fab.fb': 'Facebook',
    'totop': 'Volver arriba',
    'dock.a11y': 'Accesibilidad', 'dock.cookie': 'Preferencias de cookies', 'dock.libras': 'Lengua de señas brasileña (Libras)',
    'a11y.title': 'Accesibilidad', 'a11y.close': 'Cerrar panel de accesibilidad',
    'a11y.text': 'Texto', 'a11y.colors': 'Colores y contraste', 'a11y.reading': 'Lectura y navegación', 'a11y.motion.h': 'Movimiento y medios',
    'a11y.size': 'Tamaño del texto', 'a11y.smaller': 'Reducir texto', 'a11y.bigger': 'Aumentar texto',
    'a11y.contrast': 'Alto contraste', 'a11y.gray': 'Escala de grises', 'a11y.links': 'Resaltar enlaces',
    'a11y.font': 'Fuente legible', 'a11y.spacing': 'Espaciar texto', 'a11y.guide': 'Guía de lectura',
    'a11y.cursor': 'Cursor grande', 'a11y.motion': 'Pausar animaciones', 'a11y.noimg': 'Ocultar imágenes',
    'a11y.read': 'Escuchar la página', 'a11y.stop': 'Detener lectura', 'a11y.libras': 'Libras (VLibras)',
    'a11y.reset': 'Restablecer', 'a11y.statement': 'Declaración de accesibilidad',
    'a11y.keys': 'Atajos de teclado',
    'a11y.k1': 'ir al contenido', 'a11y.k2': 'ir al menú', 'a11y.k3': 'ir al pie de página', 'a11y.k4': 'abrir este panel',
    'a11y.on': 'activado', 'a11y.off': 'desactivado', 'a11y.noread': 'Su navegador no ofrece lectura en voz alta.',
    'ck.title': 'Su privacidad, sus reglas',
    'ck.text': 'Somos una empresa de seguridad: usamos solo lo esencial para que el sitio funcione y recuerde sus elecciones. Las funciones opcionales (mapa incrustado y asistente con IA) solo se activan con su permiso. Sin rastreadores publicitarios. Puede cambiar de opinión cuando quiera.',
    'ck.policy': 'Política de Cookies',
    'ck.accept': 'Aceptar todas', 'ck.reject': 'Rechazar opcionales', 'ck.custom': 'Personalizar',
    'ck.save': 'Guardar mis elecciones', 'ck.prefs': 'Preferencias de privacidad',
    'ck.intro': 'Elija qué categorías se pueden usar. Las categorías esenciales no se pueden desactivar porque el sitio no funciona sin ellas. Su elección queda registrada con un identificador anónimo y es válida por 12 meses.',
    'ck.always': 'Siempre activas', 'ck.details': 'Ver detalles', 'ck.none': 'Ninguna en uso por ahora. Nada se activará sin su permiso.',
    'ck.name': 'Nombre', 'ck.purpose': 'Finalidad', 'ck.duration': 'Duración',
    'ck.id': 'ID del consentimiento', 'ck.date': 'Registrado el', 'ck.saved': 'Preferencias de privacidad guardadas.', 'ck.close': 'Cerrar',
    'ck.c.necessary': 'Esenciales', 'ck.d.necessary': 'Garantizan seguridad, navegación, el registro de su consentimiento y las preferencias que solicite (idioma y accesibilidad). También cargamos VLibras, herramienta pública de accesibilidad del Gobierno Federal de Brasil.',
    'ck.c.functional': 'Funcionales', 'ck.d.functional': 'Activan contenidos de terceros que elige usar, como el mapa de Google en la página de contacto y el asistente Cy con inteligencia artificial.',
    'ck.c.analytics': 'Estadísticas', 'ck.d.analytics': 'Medición de audiencia para mejorar el sitio, con datos agregados.',
    'ck.c.marketing': 'Marketing', 'ck.d.marketing': 'Anuncios y remarketing.',
    'ck.i.consent': 'Guarda su elección de privacidad', 'ck.i.lang': 'Recuerda el idioma elegido', 'ck.i.a11y': 'Recuerda sus preferencias de accesibilidad',
    'ck.i.mascot': 'Recuerda si minimizó la mascota', 'ck.i.vlibras': 'Traducción a Libras (Gobierno Federal)', 'ck.i.maps': 'Mapa incrustado (Google)', 'ck.i.ai': 'Envío de sus preguntas al servidor de IA',
    'ck.12m': '12 meses', 'ck.persist': 'Hasta que limpie el navegador', 'ck.session': 'Sesión', 'ck.third': 'Definida por el tercero',
    'm.hello': '¡Hola! Soy Cy, el centinela de CoreCyber. ¡Desplácese y le acompaño vigilando!',
    'm.idle': '¿Tiene alguna duda? Haga clic en mí y pregunte.',
    'm.fast': '¡Uy, qué velocidad! Detecté muchas cosas buenas en el camino…',
    'm.sleep': 'Zzz… centinela en modo ahorro. Haga clic para despertarme.',
    'm.top': '¡De vuelta arriba! ¿Quiere ver lo que internet sabe de su empresa?',
    'm.bottom': 'Escaneo de la página terminado: ¡cero amenazas! ¿Qué tal hablar con un especialista?',
    'm.hide': 'Ocultar la mascota', 'm.show': 'Mostrar a Cy, la mascota', 'm.ask': 'Pregunte a Cy',
    'm.dns.good': '¡Bien! Su correo está bien protegido. El diagnóstico completo revisa mucho más.',
    'm.dns.bad': 'Mmm… encontré puntos de atención. ¿Quiere que el equipo lo revise con calma?',
    'ch.title': 'Cy · Asistente CoreCyber', 'ch.local': 'Base de conocimiento', 'ch.ai': 'IA conectada (FreeLLMAPI)',
    'ch.greet': '¡Hola! Soy Cy. Puedo explicarle qué hace CoreCyber, los planes, el diagnóstico gratuito, la protección de datos y lo que está en el roadmap, o ponerle en contacto con un especialista. ¿Cómo le ayudo?',
    'ch.ph': 'Escriba su pregunta…', 'ch.send': 'Enviar pregunta', 'ch.close': 'Cerrar asistente',
    'ch.note': 'No comparta contraseñas ni datos personales sensibles. Las respuestas automáticas pueden contener imprecisiones: confírmelas con nuestro equipo.',
    'ch.fallback': 'Todavía no sé responder eso con seguridad. ¿Prefiere hablar con una persona? [Escribir por WhatsApp]({wa}) o [enviar un mensaje](/contato/).',
    'ch.err': 'No pude consultar la IA ahora, así que respondí con la base local.',
    'ch.consent': 'Para usar la IA, sus preguntas se enviarán a nuestro servidor de IA. Active la categoría "Funcionales" en las preferencias de cookies o siga con las respuestas de la base local.',
    'ch.s1': '¿Cuánto cuesta?', 'ch.s2': 'Diagnóstico gratuito', 'ch.s3': '¿Qué recopila el agente?', 'ch.s4': '¿Tiene SIEM y EDR?', 'ch.s5': 'Hablar con una persona',
    'plan.essencial': 'Esencial', 'plan.profissional': 'Profesional', 'plan.avancado': 'Avanzado',
    'pr.month': '/mes', 'pr.upto': 'hasta {n} activos', 'pr.perasset': '≈ {v} por activo/mes',
    'pr.yearly': '{v} facturados al año · ahorra {s}', 'pr.monthly': 'Facturación mensual, sin permanencia',
    'pr.dedicated': 'Instancia dedicada (nube privada), sujeta a confirmación técnica', 'pr.cloud': 'Nube CoreCyber gestionada por EBAEM, con actualizaciones incluidas',
    'pr.big': '¿Más de 500 activos? Tenemos una propuesta a medida.',
    'pr.choose': 'Quiero el plan {p}', 'pr.msg': '¡Hola! Me interesa el plan {p} de CoreCyber ({u}, {b}, {h}). ¿Me pueden enviar una propuesta?',
    'pr.b.m': 'facturación mensual', 'pr.b.y': 'facturación anual', 'pr.h.cloud': 'en la nube CoreCyber', 'pr.h.ded': 'en instancia dedicada',
    'sim.assets': '{n} activos', 'sim.factor': '{p}% del precio de referencia',
    'sim.save': 'de ahorro estimado en 12 meses', 'sim.pct': '{p}% menos que armar la pila con herramientas separadas',
    'sim.plan': 'CoreCyber {p} (anual)',
    'sim.pick': 'Marque al menos una herramienta que compraría por separado.',
    'sim.more': 'Por encima de 500 activos el valor de CoreCyber se estima proporcionalmente; solicite una propuesta a medida.',
    'sim.roadmap': 'Atención: SIEM y EDR completo están en el roadmap de CoreCyber. Hoy el plan Avanzado ofrece monitoreo por agente, cumplimiento y correlación; compare con ese cuidado.',
    'sim.none': 'Con esta combinación el valor es similar: la ganancia está en una sola consola, un solo idioma y un solo contrato.',
    'f.required': 'Complete este campo.', 'f.email': 'Introduzca un correo válido.', 'f.consent': 'Para continuar, marque la casilla de conformidad.',
    'f.ok.wa': '¡Listo! Abrimos WhatsApp con su mensaje completado. Número de referencia: {p}.',
    'f.ok.mail': '¡Listo! Abrimos su aplicación de correo con el mensaje completado. Número de referencia: {p}.',
    'f.ok.hint': 'Si no se abrió nada, escriba a {m} indicando el número de referencia.',
    'f.subject': 'CoreCyber · {t} · {p}', 'f.proto': 'Referencia',
    'f.t.contact': 'Contacto', 'f.t.titular': 'Solicitud del titular (LGPD)', 'f.t.integrity': 'Reporte de integridad', 'f.t.referral': 'Recomendación de cliente',
    'f.t.diagnostic': 'Diagnóstico gratuito de exposición', 'f.t.poc': 'Prueba de concepto de 30 días', 'f.t.partner': 'Alianza / MSSP', 'f.t.disclosure': 'Reporte de vulnerabilidad', 'f.t.demo': 'Demostración guiada',
    'dns.invalid': 'Escriba un dominio válido, por ejemplo: suempresa.com',
    'dns.wait': 'Consultando el DNS público de {d}…',
    'dns.fail': 'No fue posible consultar el DNS público ahora. Inténtelo de nuevo en unos instantes o solicite el diagnóstico completo.',
    'dns.nx': 'El dominio {d} no se encontró en el DNS. Revise la ortografía.',
    'dns.title': 'Protección de correo y DNS de {d}',
    'dns.sub': 'Lectura de registros públicos, sin tocar sus servidores.',
    'dns.spf.none': 'Sin SPF: cualquier servidor puede intentar enviar correos en nombre de su dominio.',
    'dns.spf.multi': 'Hay más de un registro SPF, y eso invalida la verificación. Mantenga solo uno.',
    'dns.spf.soft': 'SPF permisivo (+all o ?all): protección débil contra la suplantación.',
    'dns.spf.ok': 'SPF publicado y restrictivo.',
    'dns.dmarc.none': 'Sin DMARC: correos falsos con su dominio pueden llegar a las bandejas de entrada.',
    'dns.dmarc.none.p': 'DMARC solo en modo monitoreo (p=none): las suplantaciones siguen entregándose.',
    'dns.dmarc.ok': 'DMARC activo con política {p}.',
    'dns.sec.ok': 'DNSSEC validado: respuestas del DNS firmadas.',
    'dns.sec.no': 'Sin DNSSEC validado: las respuestas del DNS podrían falsificarse en el camino.',
    'dns.caa.ok': 'CAA publicado: solo autoridades autorizadas emiten certificados.',
    'dns.caa.no': 'Sin CAA: cualquier autoridad certificadora puede emitir certificados para el dominio.',
    'dns.mx.ok': '{n} servidor(es) de correo encontrados.',
    'dns.mx.no': 'Ningún servidor de correo (MX): normal si el dominio no recibe correos.',
    'dns.sts.ok': 'MTA-STS publicado: la entrega de correo exige cifrado.',
    'dns.sts.no': 'Sin MTA-STS (recomendado para quien recibe correo).',
    'dns.rpt.ok': 'TLS-RPT publicado: recibe informes de fallas de cifrado.',
    'dns.rpt.no': 'Sin TLS-RPT (opcional, ayuda a detectar ataques a la entrega de correo).',
    'dns.more': 'Esto es solo la superficie de la superficie. El diagnóstico completo de CoreCyber revisa puertos, TLS, encabezados, subdominios olvidados y exposiciones conocidas.',
    'dns.cta': 'Quiero el diagnóstico completo',
    'dns.note': 'La consulta la hizo su navegador directamente al DNS público de Google (con el de Cloudflare como respaldo). EBAEM no recibe el dominio escrito.',
    'demo.ok': '¡Hecho! (demostración)',
    'demo.scan.run': 'Escaneando…', 'demo.scan.done': 'Terminado a las {h}',
    'demo.scan.toast': 'Escaneo terminado: hallazgos nuevos: {n} · resueltos desde la última ejecución: {r}.',
    'demo.cycle': 'Estado actualizado: {s}. Registrado en la línea de tiempo.',
    'demo.soar': 'Regla probada: caso CASE-2026-{n} abierto y alerta enviada a Telegram.',
    'demo.qr': 'Documento auténtico · protocolo REL-2026-0{n} · verificado a las {h}.',
    'demo.glpi': 'Ticket GLPI #{n} abierto automáticamente y vinculado al caso.',
    'demo.decom': 'Certificado de desmantelamiento DSC-2026-{n} emitido con QR.',
    'demo.export': 'Exportación generada (ejemplo de demostración).',
    'demo.status': 'Página de estado pública actualizada a las {h}.',
    'demo.agent': 'Corrección enviada. La persona en la máquina puede aceptarla o rechazarla.',
    'st.open': 'Abierta', 'st.fixing': 'En corrección', 'st.fixed': 'Corregida', 'st.validated': 'Validada en la nueva prueba',
    'st.pending': 'Pendiente', 'st.waiting': 'Esperando aceptación en el equipo', 'st.applied': 'Aplicada',
    'st.draft': 'Borrador', 'st.review': 'En revisión', 'st.approved': 'Aprobada · PDF con QR',
    'st.c.open': 'Abierto', 'st.c.inv': 'Investigando', 'st.c.cont': 'Contenido', 'st.c.res': 'Resuelto', 'st.c.closed': 'Cerrado',
    'st.up': 'Operativo', 'st.maint': 'En mantenimiento (1 h)', 'st.accepted': 'Riesgo aceptado con justificación',
    'map.load': 'Cargar mapa', 'reveal.touch': 'Toque para revelar',
    'p.off': 'Cámara apagada', 'p.loading': 'Cargando detector de manos…', 'p.show': 'Muestre la palma de la mano a la cámara',
    'p.hand': 'Mano detectada: ábrala para alisar, ciérrela para arrugar', 'p.nocam': 'Cámara no disponible: use el control deslizante o arrastre',
    'p.done': '¡Alisado! Riesgo priorizado, evidencia verificable.', 'p.drag': 'Arrastre hacia arriba para alisar el papel', 'p.camoff': 'Apagar cámara', 'p.camon': 'Activar cámara',
    'p.par': 'Mueva el ratón (o incline el móvil) y verá la profundidad real', 'p.gyro': 'Activar inclinación del móvil',
    'p.doc1': 'INFORME DE PENTEST', 'p.doc2': 'Versión impresa · 2023', 'p.doc3': 'DESACTUALIZADO', 'p.doc4': '240 páginas. ¿Quién corrigió qué?',
    'p.ok1': 'INFORME DE EXPOSICIÓN', 'p.ok2': 'CoreCyber · actualizado ahora', 'p.ok3': 'Riesgo 82 → 41 en 30 días', 'p.ok4': 'Auténtico: QR verificable',
    'p.note': '¡¡Cambiar la contraseña del firewall!!', 'p.oldh': 'PLANILLA DE CVEs', 'p.old': 'vulns_v7_FINAL_ahora_si.xlsx',
    'g.br': 'Su empresa'
  }
};

/* Base de conhecimento do assistente (respostas locais e contexto para a IA). */
var CC_KB = [
  { k: ['preco', 'precos', 'custa', 'valor', 'valores', 'plano', 'planos', 'mensalidade', 'orcamento', 'price', 'pricing', 'cost', 'plan', 'precio', 'cuanto', 'costo'],
    pt: 'Os planos são cobrados por faixa de ativos monitorados (25, 50, 100, 250 ou 500), em reais e sem variação cambial: Essencial a partir de R$ 490/mês, Profissional a partir de R$ 990/mês e Avançado a partir de R$ 1.890/mês (faixa de 25 ativos). No anual você paga 10 meses e leva 12. Simule em [Planos e preços](/planos/).',
    en: 'Plans are priced by tier of monitored assets (25, 50, 100, 250 or 500), in Brazilian reais with no exchange-rate exposure: Essential from R$ 490/month, Professional from R$ 990/month and Advanced from R$ 1,890/month (25-asset tier). With yearly billing you pay 10 months and get 12. Try it on [Plans and pricing](/planos/).',
    es: 'Los planes se cobran por franja de activos monitoreados (25, 50, 100, 250 o 500), en reales y sin variación cambiaria: Esencial desde R$ 490/mes, Profesional desde R$ 990/mes y Avanzado desde R$ 1.890/mes (franja de 25 activos). En el plan anual paga 10 meses y tiene 12. Simúlelo en [Planes y precios](/planos/).' },
  { k: ['ativo', 'ativos', 'conta como', 'asset', 'assets', 'activo', 'activos'],
    pt: 'Cada domínio, subdomínio relevante, IP público, API, computador ou servidor monitorado conta como 1 ativo. Monitores de disponibilidade e relatórios não contam. Acima de 500 ativos fazemos proposta sob medida. [Política de Comercialização](/politica-comercial/).',
    en: 'Each monitored domain, relevant subdomain, public IP, API, computer or server counts as 1 asset. Uptime monitors and reports do not count. Above 500 assets we build a tailored proposal. [Sales Policy](/politica-comercial/).',
    es: 'Cada dominio, subdominio relevante, IP pública, API, computadora o servidor monitoreado cuenta como 1 activo. Los monitores de disponibilidad y los informes no cuentan. Por encima de 500 activos hacemos una propuesta a medida. [Política de Comercialización](/politica-comercial/).' },
  { k: ['teste', 'gratis', 'gratuito', 'diagnostico', 'trial', 'free', 'poc', 'prova de conceito', 'demo', 'demonstracao', 'prueba', 'assessment'],
    pt: 'Você pode começar sem pagar nada: o diagnóstico gratuito de exposição externa é não invasivo e chega em até 2 dias úteis (basta comprovar que o domínio é seu). Depois, há prova de conceito de 30 dias com até 25 ativos. [Pedir diagnóstico](/diagnostico-gratuito/).',
    en: 'You can start for free: the external exposure assessment is non-invasive and delivered within 2 business days (you just need to prove you own the domain). Then there is a 30-day proof of concept with up to 25 assets. [Request assessment](/diagnostico-gratuito/).',
    es: 'Puede empezar sin pagar: el diagnóstico gratuito de exposición externa no es invasivo y llega en hasta 2 días hábiles (solo debe demostrar que el dominio es suyo). Luego hay una prueba de concepto de 30 días con hasta 25 activos. [Pedir diagnóstico](/diagnostico-gratuito/).' },
  { k: ['o que e', 'oque', 'faz', 'funcionalidade', 'funcionalidades', 'recursos', 'modulos', 'what is', 'features', 'que es', 'funciones', 'plataforma'],
    pt: 'O CoreCyber reúne num só painel: superfície de ataque externa (varredura a cada 10 minutos), disponibilidade e status pages, vulnerabilidades priorizadas por CVSS, EPSS e KEV, segurança de código e APIs, inteligência de ameaças diária, monitoração de computadores por agente, 193 controles ISO/LGPD, casos de incidente e 32 tipos de relatório com QR. [Conheça a plataforma](/plataforma/).',
    en: 'CoreCyber brings together in one console: external attack surface (scans every 10 minutes), uptime and status pages, vulnerabilities prioritized by CVSS, EPSS and KEV, code and API security, daily threat intelligence, agent-based device monitoring, 193 ISO/LGPD controls, incident cases and 32 report types with QR. [See the platform](/plataforma/).',
    es: 'CoreCyber reúne en una sola consola: superficie de ataque externa (escaneo cada 10 minutos), disponibilidad y páginas de estado, vulnerabilidades priorizadas por CVSS, EPSS y KEV, seguridad de código y APIs, inteligencia de amenazas diaria, monitoreo de equipos por agente, 193 controles ISO/LGPD, casos de incidente y 32 tipos de informe con QR. [Conozca la plataforma](/plataforma/).' },
  { k: ['superficie', 'easm', 'varredura', 'scan', 'subdominio', 'subdominios', 'portas', 'fingerprint', 'externo', 'escaneo', 'surface'],
    pt: 'O FingerPrint faz varredura externa não invasiva de sites, APIs e subdomínios: portas, SSL/TLS, cabeçalhos, exposições conhecidas, WAF, SPF/DMARC e acessibilidade. O monitoramento contínuo roda a cada 10 minutos e avisa sobre achado crítico novo ou subdomínio novo. [Ver a tela](/telas/#superficie).',
    en: 'FingerPrint runs non-invasive external scans of websites, APIs and subdomains: ports, SSL/TLS, headers, known exposures, WAF, SPF/DMARC and accessibility. Continuous monitoring runs every 10 minutes and alerts on new critical findings or new subdomains. [See the screen](/telas/#superficie).',
    es: 'FingerPrint realiza escaneos externos no invasivos de sitios, APIs y subdominios: puertos, SSL/TLS, encabezados, exposiciones conocidas, WAF, SPF/DMARC y accesibilidad. El monitoreo continuo corre cada 10 minutos y avisa de hallazgos críticos nuevos o subdominios nuevos. [Ver la pantalla](/telas/#superficie).' },
  { k: ['vulnerabilidade', 'vulnerabilidades', 'cve', 'kev', 'epss', 'cvss', 'prioriza', 'priorizacao', 'sla', 'vulnerability', 'vulnerabilidad'],
    pt: 'A fila de vulnerabilidades combina gravidade (CVSS), probabilidade de exploração (EPSS) e o catálogo de falhas exploradas ativamente (KEV): o que é atacado de verdade sobe para o topo. Há SLA por severidade (7 a 90 dias), aceite de risco com justificativa e passo a passo de correção. [Ver a tela](/telas/#vulnerabilidades).',
    en: 'The vulnerability queue combines severity (CVSS), exploitation probability (EPSS) and the catalog of actively exploited flaws (KEV): what is really being attacked rises to the top. There are severity SLAs (7 to 90 days), risk acceptance with justification and step-by-step remediation. [See the screen](/telas/#vulnerabilidades).',
    es: 'La cola de vulnerabilidades combina gravedad (CVSS), probabilidad de explotación (EPSS) y el catálogo de fallas explotadas activamente (KEV): lo que realmente se ataca sube al primer lugar. Hay SLA por severidad (7 a 90 días), aceptación de riesgo con justificación y guía de corrección paso a paso. [Ver la pantalla](/telas/#vulnerabilidades).' },
  { k: ['agente', 'endpoint', 'computador', 'notebook', 'windows', 'linux', 'coleta', 'coletado', 'monitora', 'agent', 'collect', 'equipo', 'recopila'],
    pt: 'O agente roda em Windows (como serviço), Linux, Docker, WordPress e Android. Ele coleta saúde da máquina, criptografia de disco, antivírus, atualizações pendentes, inventário e 17 verificações de conformidade. Ele NÃO lê arquivos, NÃO captura tela ou teclas e NÃO registra navegação; localização só com consentimento. macOS ainda não é suportado. [Detalhes](/plataforma/#ativos).',
    en: 'The agent runs on Windows (as a service), Linux, Docker, WordPress and Android. It collects device health, disk encryption, antivirus, pending updates, inventory and 17 compliance checks. It does NOT read files, capture screens or keystrokes or record browsing; location only with consent. macOS is not supported yet. [Details](/plataforma/#ativos).',
    es: 'El agente funciona en Windows (como servicio), Linux, Docker, WordPress y Android. Recopila salud del equipo, cifrado de disco, antivirus, actualizaciones pendientes, inventario y 17 verificaciones de cumplimiento. NO lee archivos, NO captura pantalla ni teclas y NO registra la navegación; ubicación solo con consentimiento. macOS aún no es compatible. [Detalles](/plataforma/#ativos).' },
  { k: ['iso', '27001', '27701', '22301', 'conformidade', 'controles', 'aplicabilidade', 'soa', 'auditoria', 'compliance iso', 'cumplimiento'],
    pt: 'São 193 controles de ISO/IEC 27001:2022, 27017, 27018, 27701, ISO 22301 e LGPD, cada um com situação calculada a partir das evidências. A Declaração de Aplicabilidade sai aprovada por versão, em PDF com QR. [Ver a tela](/telas/#conformidade).',
    en: 'There are 193 controls from ISO/IEC 27001:2022, 27017, 27018, 27701, ISO 22301 and Brazil’s LGPD, each with a status calculated from evidence. The Statement of Applicability is approved per version, as a PDF with QR. [See the screen](/telas/#conformidade).',
    es: 'Son 193 controles de ISO/IEC 27001:2022, 27017, 27018, 27701, ISO 22301 y la LGPD de Brasil, cada uno con su estado calculado a partir de evidencias. La Declaración de Aplicabilidad se aprueba por versión, en PDF con QR. [Ver la pantalla](/telas/#conformidade).' },
  { k: ['siem', 'edr', 'xdr', 'ndr', 'soc', 'logs', 'deteccao', 'detection', 'roadmap', 'deteccion'],
    pt: 'Transparência total: hoje o CoreCyber faz detecções correlacionadas por regras, casos de incidente com GLPI e automação de alertas. SIEM com coleta de logs, EDR completo (com isolamento de máquina) e NDR estão no roadmap — e nós avisamos clientes antes de cada lançamento. [Ver roadmap](/plataforma/#roadmap).',
    en: 'Full transparency: today CoreCyber delivers rule-based correlated detections, incident cases with GLPI and alert automation. SIEM with log collection, full EDR (with device isolation) and NDR are on the roadmap — and we tell customers before each release. [See roadmap](/plataforma/#roadmap).',
    es: 'Transparencia total: hoy CoreCyber ofrece detecciones correlacionadas por reglas, casos de incidente con GLPI y automatización de alertas. SIEM con recolección de logs, EDR completo (con aislamiento de equipos) y NDR están en el roadmap, y avisamos a los clientes antes de cada lanzamiento. [Ver roadmap](/plataforma/#roadmap).' },
  { k: ['ia', 'inteligencia artificial', 'gpt', 'chatgpt', 'llm', 'ai', 'machine learning', 'preditiva'],
    pt: 'Hoje a IA é opcional e serve para personalizar o texto do laudo de exposição. O assistente de IA dentro da plataforma e a IA preditiva estão no roadmap, como add-on — entre na lista de espera pelo [contato](/contato/). Eu, o Cy, sou o assistente do site.',
    en: 'Today AI is optional and is used to tailor the exposure report text. The in-platform AI assistant and predictive AI are on the roadmap as an add-on — join the waiting list via [contact](/contato/). I, Cy, am the website assistant.',
    es: 'Hoy la IA es opcional y sirve para personalizar el texto del informe de exposición. El asistente de IA dentro de la plataforma y la IA predictiva están en el roadmap, como complemento: únase a la lista de espera en [contacto](/contato/). Yo, Cy, soy el asistente del sitio.' },
  { k: ['integracao', 'integracoes', 'glpi', 'telegram', 'slack', 'webhook', 'teams', 'whatsapp alerta', 'integration', 'integracion'],
    pt: 'Alertas e integrações: e-mail com modelos editáveis, Telegram, Slack, webhook, GLPI (API v1 e a nova API v2 com OAuth2, abrindo e fechando chamados sozinho), Google Drive para cópia dos relatórios e login com Google, Microsoft ou certificado ICP-Brasil. Teams e WhatsApp estão em evolução.',
    en: 'Alerts and integrations: email with editable templates, Telegram, Slack, webhook, GLPI (API v1 and the new API v2 with OAuth2, opening and closing tickets automatically), Google Drive for report copies, and sign-in with Google, Microsoft or an ICP-Brasil digital certificate. Teams and WhatsApp are in progress.',
    es: 'Alertas e integraciones: correo con plantillas editables, Telegram, Slack, webhook, GLPI (API v1 y la nueva API v2 con OAuth2, que abre y cierra tickets solo), Google Drive para copias de informes e inicio de sesión con Google, Microsoft o certificado ICP-Brasil. Teams y WhatsApp están en evolución.' },
  { k: ['relatorio', 'relatorios', 'laudo', 'qr', 'pdf', 'autenticidade', 'report', 'reports', 'informe'],
    pt: 'São 32 tipos de relatório em PDF ou DOCX, cada um com protocolo e QR Code que qualquer pessoa confere numa página pública de autenticidade — ótimo para auditorias, diretoria e licitações. [Ver a tela](/telas/#relatorios).',
    en: 'There are 32 report types in PDF or DOCX, each with a reference number and QR code anyone can check on a public authenticity page — great for audits, boards and public tenders. [See the screen](/telas/#relatorios).',
    es: 'Son 32 tipos de informe en PDF o DOCX, cada uno con protocolo y código QR que cualquiera puede verificar en una página pública de autenticidad: ideal para auditorías, directorio y licitaciones. [Ver la pantalla](/telas/#relatorios).' },
  { k: ['mssp', 'revenda', 'parceiro', 'parceria', 'white label', 'multiempresa', 'msp', 'partner', 'reseller', 'socio'],
    pt: 'O CoreCyber é multiempresa de nascença: empresas administradoras enxergam seus clientes com isolamento testado (3.951 verificações, 0 falhas). Para MSSPs e revendas há plano com marca própria e SLA, sob consulta. [Fale com a gente](/contato/).',
    en: 'CoreCyber is multi-tenant by design: managing companies see their customers with tested isolation (3,951 checks, 0 failures). For MSSPs and resellers there is a white-label plan with SLA, on request. [Talk to us](/contato/).',
    es: 'CoreCyber es multiempresa desde su origen: las empresas administradoras ven a sus clientes con aislamiento probado (3.951 verificaciones, 0 fallas). Para MSSP y revendedores hay un plan con marca propia y SLA, bajo consulta. [Hable con nosotros](/contato/).' },
  { k: ['concorrente', 'concorrentes', 'comparar', 'comparativo', 'diferenca', 'diferencial', 'mercado', 'competitor', 'compare', 'competencia'],
    pt: 'O diferencial é unificar: em vez de cinco ferramentas, cinco contratos em dólar e cinco telas em inglês, um só painel em português, com preço em reais, conformidade ISO/LGPD nativa e suporte da EBAEM em Brasília. Veja o [comparativo honesto](/comparativo/), inclusive onde ainda estamos evoluindo.',
    en: 'The edge is unification: instead of five tools, five dollar contracts and five English-only screens, one console in Portuguese, priced in reais, with native ISO/LGPD compliance and support from EBAEM in Brasília. See the [honest comparison](/comparativo/), including where we are still evolving.',
    es: 'La diferencia es unificar: en lugar de cinco herramientas, cinco contratos en dólares y cinco pantallas en inglés, una sola consola en portugués, con precio en reales, cumplimiento ISO/LGPD nativo y soporte de EBAEM en Brasilia. Mire la [comparación honesta](/comparativo/), incluso donde aún estamos evolucionando.' },
  { k: ['seguranca da plataforma', 'seguro', 'protecao', '2fa', 'mfa', 'senha', 'certificado digital', 'icp', 'secure', 'seguridad'],
    pt: 'A plataforma tem perfis por função, 2º fator, login com Google, Microsoft ou certificado ICP-Brasil, sessão que expira por inatividade, logs de auditoria, segredos cifrados e isolamento entre empresas testado automaticamente. [Central de Confiança](/confianca/).',
    en: 'The platform has role-based profiles, second factor, sign-in with Google, Microsoft or an ICP-Brasil certificate, sessions that expire on inactivity, audit logs, encrypted secrets and automatically tested tenant isolation. [Trust Center](/confianca/).',
    es: 'La plataforma tiene perfiles por función, segundo factor, inicio de sesión con Google, Microsoft o certificado ICP-Brasil, sesión que expira por inactividad, registros de auditoría, secretos cifrados y aislamiento entre empresas probado automáticamente. [Centro de Confianza](/confianca/).' },
  { k: ['lgpd', 'privacidade', 'dados pessoais', 'titular', 'dpo', 'encarregado', 'privacy', 'gdpr', 'datos'],
    pt: 'Para exercer seus direitos junto à EBAEM, use o [Portal do Titular](/lgpd/#portal) ou escreva para lgpd@ebaem.com.br — resposta completa em até 15 dias. Dentro da plataforma, o CoreCyber ajuda sua empresa com ROPA, pedidos de titulares com protocolo e controles ISO 27701.',
    en: 'To exercise your rights with EBAEM, use the [Data Subject Portal](/lgpd/#portal) or write to lgpd@ebaem.com.br — full answer within 15 days. Inside the platform, CoreCyber helps your company with RoPA, data subject requests with ticket numbers and ISO 27701 controls.',
    es: 'Para ejercer sus derechos ante EBAEM, use el [Portal del Titular](/lgpd/#portal) o escriba a lgpd@ebaem.com.br, con respuesta completa en hasta 15 días. Dentro de la plataforma, CoreCyber ayuda a su empresa con el registro de tratamientos, solicitudes de titulares con protocolo y controles ISO 27701.' },
  { k: ['vulnerabilidade no site', 'reportar', 'bug', 'falha', 'divulgacao', 'disclosure', 'bounty', 'security.txt', 'reporte'],
    pt: 'Encontrou uma falha no CoreCyber? Obrigado! Siga a [Política de Divulgação Responsável](/divulgacao-responsavel/) e escreva para seguranca@ebaem.com.br. Confirmamos o recebimento em até 3 dias úteis.',
    en: 'Found a flaw in CoreCyber? Thank you! Follow the [Responsible Disclosure Policy](/divulgacao-responsavel/) and write to seguranca@ebaem.com.br. We acknowledge receipt within 3 business days.',
    es: '¿Encontró una falla en CoreCyber? ¡Gracias! Siga la [Política de Divulgación Responsable](/divulgacao-responsavel/) y escriba a seguranca@ebaem.com.br. Confirmamos la recepción en hasta 3 días hábiles.' },
  { k: ['compliance', 'denuncia', 'integridade', 'etica', 'anonimo', 'ouvidoria', 'whistleblowing', 'integrity'],
    pt: 'O Canal de Integridade aceita relatos anônimos, com protocolo para acompanhar e proteção contra retaliação. Use o [Canal de Integridade](/compliance/#canal) ou ouvidoria@ebaem.com.br.',
    en: 'The Integrity Channel accepts anonymous reports, with a ticket number for follow-up and protection against retaliation. Use the [Integrity Channel](/compliance/#canal) or ouvidoria@ebaem.com.br.',
    es: 'El Canal de Integridad acepta reportes anónimos, con protocolo de seguimiento y protección contra represalias. Use el [Canal de Integridad](/compliance/#canal) u ouvidoria@ebaem.com.br.' },
  { k: ['contato', 'humano', 'pessoa', 'atendente', 'especialista', 'telefone', 'whatsapp', 'falar', 'human', 'person', 'contact', 'contacto', 'persona'],
    pt: 'Claro! Fale com a equipe da EBAEM pelo [WhatsApp]({wa}), pelo telefone (61) 98128-6479 ou pelo e-mail contato@ebaem.com.br — de segunda a sexta, das 8h às 18h (Brasília). [Página de contato](/contato/).',
    en: 'Of course! Reach the EBAEM team via [WhatsApp]({wa}), phone +55 61 98128-6479 or contato@ebaem.com.br — Monday to Friday, 8am to 6pm (Brasília time). [Contact page](/contato/).',
    es: '¡Claro! Hable con el equipo de EBAEM por [WhatsApp]({wa}), por teléfono +55 61 98128-6479 o por correo contato@ebaem.com.br, de lunes a viernes de 8 a 18 h (hora de Brasilia). [Página de contacto](/contato/).' },
  { k: ['ebaem', 'fabricante', 'empresa', 'quem', 'sobre', 'about', 'company', 'quienes', 'brasileira', 'nacional'],
    pt: 'O CoreCyber é desenvolvido, licenciado e usado pela EBAEM — Empresa Brasileira de Assessoria Executiva e Multidisciplinar, de Brasília, especialista em governança, LGPD, compliance, normas ISO e tecnologia. A própria EBAEM é a primeira cliente. [Conheça](/sobre/).',
    en: 'CoreCyber is developed, licensed and used by EBAEM — a Brasília-based executive and multidisciplinary advisory firm specialized in governance, data protection, compliance, ISO standards and technology. EBAEM itself is the first customer. [Learn more](/sobre/).',
    es: 'CoreCyber es desarrollado, licenciado y usado por EBAEM, empresa de asesoría ejecutiva y multidisciplinaria de Brasilia, especialista en gobernanza, protección de datos, compliance, normas ISO y tecnología. La propia EBAEM es la primera clienta. [Conozca más](/sobre/).' },
  { k: ['cliente', 'clientes', 'quem usa', 'case', 'cases', 'referencia', 'customers', 'who uses'],
    pt: 'A EBAEM usa o CoreCyber no próprio dia a dia, e organizações como ASSBAN, MOORE e MIDNAL estão em implantação. Indique uma empresa e ganhe benefícios no [programa de indicação](/clientes/#indique).',
    en: 'EBAEM uses CoreCyber every day, and organizations such as ASSBAN, MOORE and MIDNAL are being onboarded. Refer a company and earn benefits through the [referral program](/clientes/#indique).',
    es: 'EBAEM usa CoreCyber en su día a día, y organizaciones como ASSBAN, MOORE y MIDNAL están en implementación. Recomiende una empresa y gane beneficios en el [programa de recomendación](/clientes/#indique).' },
  { k: ['cancelar', 'cancelamento', 'reembolso', 'arrependimento', 'fidelidade', 'contrato', 'sair', 'exportar', 'cancel', 'refund', 'cancelacion'],
    pt: 'No plano mensal não há fidelidade. Ao encerrar, você tem 30 dias para exportar seus dados e pode receber um certificado de descomissionamento. Regras completas na [Política de Comercialização](/politica-comercial/).',
    en: 'Monthly plans have no lock-in. When you leave, you have 30 days to export your data and can receive a decommissioning certificate. Full rules in the [Sales Policy](/politica-comercial/).',
    es: 'En el plan mensual no hay permanencia. Al terminar, tiene 30 días para exportar sus datos y puede recibir un certificado de desmantelamiento. Reglas completas en la [Política de Comercialización](/politica-comercial/).' },
  { k: ['sap', 'racf', 'mainframe', 'erp', 'segregacao'],
    pt: 'Raro no mercado: o CoreCyber faz auditoria de acessos SAP e RACF (mainframe), com dossiê de evidências, segregação de funções, conciliações cruzadas e laudo autenticado por QR. É contratado por projeto. [Saiba mais](/plataforma/#auditorias).',
    en: 'Rare on the market: CoreCyber audits SAP and RACF (mainframe) access, with an evidence dossier, segregation of duties, cross reconciliations and a QR-authenticated report. It is contracted per project. [Learn more](/plataforma/#auditorias).',
    es: 'Raro en el mercado: CoreCyber audita accesos SAP y RACF (mainframe), con dossier de evidencias, segregación de funciones, conciliaciones cruzadas e informe autenticado por QR. Se contrata por proyecto. [Más información](/plataforma/#auditorias).' },
  { k: ['idioma', 'idiomas', 'ingles', 'espanhol', 'language', 'languages', 'english', 'spanish', 'lengua'],
    pt: 'A plataforma fala 8 idiomas: português, inglês, espanhol, italiano, francês, chinês, japonês e russo. Este site está em português, inglês e espanhol, com Libras pelo VLibras.',
    en: 'The platform speaks 8 languages: Portuguese, English, Spanish, Italian, French, Chinese, Japanese and Russian. This website is in Portuguese, English and Spanish, with Brazilian Sign Language via VLibras.',
    es: 'La plataforma habla 8 idiomas: portugués, inglés, español, italiano, francés, chino, japonés y ruso. Este sitio está en portugués, inglés y español, con lengua de señas brasileña mediante VLibras.' },
  { k: ['libras', 'acessibilidade', 'acessivel', 'deficiencia', 'accessibility', 'accesibilidad', 'contraste'],
    pt: 'Este site tem VLibras (tradução em Libras), painel de acessibilidade (contraste, fonte legível, régua de leitura, pausar animações, leitura em voz alta) e navegação por teclado. E o CoreCyber também verifica a acessibilidade WCAG dos sites dos clientes. [Declaração de acessibilidade](/acessibilidade/).',
    en: 'This website has VLibras (Brazilian Sign Language), an accessibility panel (contrast, readable font, reading guide, pause animations, read aloud) and keyboard navigation. CoreCyber also checks WCAG accessibility on customer websites. [Accessibility statement](/acessibilidade/).',
    es: 'Este sitio tiene VLibras (lengua de señas brasileña), panel de accesibilidad (contraste, fuente legible, guía de lectura, pausar animaciones, lectura en voz alta) y navegación por teclado. CoreCyber también verifica la accesibilidad WCAG de los sitios de los clientes. [Declaración de accesibilidad](/acessibilidade/).' },
  { k: ['disponibilidade', 'uptime', 'status page', 'statuspage', 'fora do ar', 'monitoramento de site', 'availability', 'disponibilidad'],
    pt: 'O módulo de disponibilidade monitora sites e serviços (HTTP/S e TCP), mede uptime, latência e meta de SLA, avisa antes de o certificado ou o domínio vencer e publica status pages com a sua marca. Pode até abrir e fechar chamados no GLPI sozinho. [Ver a tela](/telas/#disponibilidade).',
    en: 'The availability module monitors websites and services (HTTP/S and TCP), measures uptime, latency and SLA targets, warns before certificates or domains expire and publishes status pages with your brand. It can even open and close GLPI tickets on its own. [See the screen](/telas/#disponibilidade).',
    es: 'El módulo de disponibilidad monitorea sitios y servicios (HTTP/S y TCP), mide uptime, latencia y meta de SLA, avisa antes de que venza el certificado o el dominio y publica páginas de estado con su marca. Incluso puede abrir y cerrar tickets en GLPI solo. [Ver la pantalla](/telas/#disponibilidade).' },
  { k: ['mac', 'macos', 'apple', 'iphone', 'ios', 'android', 'celular', 'app', 'aplicativo', 'mobile'],
    pt: 'Há app para Android (com autoatualização) e agentes para Windows, Linux, Docker e WordPress. O app iOS está em preparação e o macOS ainda não é suportado — avisaremos quando chegar.',
    en: 'There is an Android app (with auto-update) and agents for Windows, Linux, Docker and WordPress. The iOS app is being prepared and macOS is not supported yet — we will let you know when it arrives.',
    es: 'Hay app para Android (con actualización automática) y agentes para Windows, Linux, Docker y WordPress. La app iOS está en preparación y macOS aún no es compatible; avisaremos cuando llegue.' }
];
